### ISSUE TITLE
filtering dns servers are used although require_nofilter is used

### ISSUE THREAD

**Issue by Thermi** [DNSCrypt/dnscrypt-proxy#1021]
This started to happen last week. The config was not changed after the setup some months ago. Seems like some DNS servers started to filter but they're still listed as non-filtering.
dnscrypt version 2.0.31 is used.

**Comment by jedisct1** [comment]
Hi,

And thanks!

The resolvers lists are independent from this project, so issues regarding resolvers are better open here: https://github.com/DNSCrypt/dnscrypt-resolvers

Some servers may have started to filter ads or another unwanted content. If they are listed with the `no filter` tag, the tag can definitely be updated. But in order to do so, having the resolver names and some sample domains being blocked would be useful :)

Thanks!
