### ISSUE TITLE
Blacklist Memory Usage

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [DNSCrypt/dnscrypt-proxy#106]
I'm currently using dnsmasq for my blacklist and dnscrypt-proxy for dns resolving.
I have a quite large blacklist, the file size is arround 90mb.

When I'm loading this blacklist on dnsmasq, it uses arround 30% memory of my raspberry pi 2, (~330mb).
When I try to load that list on dnscrypt-proxy, so I can skip dnsmasq completely, it'll use over 100% of the memory and will make my pi crash. And the loading process is still not done when it reaches 100% of memory usage.

**Comment by jedisct1** [comment]
A 90 Mb list is totally nuts. You should really try to optimize it. Instead of blocking `a.example.com` and `b.example.com`, just block `example.com`. There are probably many duplicates and overlaps in your list.

dnscrypt-proxy handles patterns such as `ads.*` or `*sex*` or `tracker*.example.*`. Take advantage of these, and your list will become very small.

Pull requests to reduce memory usage without sacrificing performance would also be welcome.
