### ISSUE TITLE
The DNS records in the forwarding_rules can't be cached

### ISSUE THREAD

**Issue by floating-cat** [DNSCrypt/dnscrypt-proxy#1073]
dnscrypt-proxy version: 2.0.33.
OS: Arch Linux.

The steps to reproduce:
1. Add a rule `www.example.com 8.8.8.8` to forwarding_rules file, and use this file in dnscrypt-proxy config.
2. Restart dnscrypt-proxy.
3. `dig @127.0.0.1 www.example.com` twice.

Actual behavior:
The query time of 2nd dig is not 0 msec.

Expected behavior:
This DNS record is cached, so the query time of 2nd dig is 0 msec.

**Comment by jedisct1** [comment]
Hi!

This is intentional. Forwarding’s primary use case is to redirect internal domains to the local router.
The router’s DNS server handles DHCP-assigned devices that come and go, so we don’t want caching here, especially negative caching.

If you try to print something and get an error that the printer doesn’t exist because you forgot to turn it on, you want your device to see it as soon as you turn it on. Caching would be very frustrating.

And forwarding doesn’t have any security, this is plain unauthenticated DNS. So it was really meant to be used with local servers only. Disabling caching avoids troubleshooting issues.

Maybe something that can be implemented later is the ability to use a specific (secure) resolver for a domain. But that would be a completely new feature.
