### ISSUE TITLE
Whitelist/blacklist weirdness with latest beta..broken interwebs - try #2

### ISSUE THREAD

**Issue by stylemessiah** [DNSCrypt/dnscrypt-proxy#1083]
Did you miss the part where it worked just fine with the previous version? As it wasnt being blocked at all, and without ANY whitelisting for yourtv.com.au
In reply to your post on https://github.com/DNSCrypt/dnscrypt-proxy/issues/1082

Closed in haste with no real explanation.....

Ive had edgekey blocked for years, a sit hosts a LOT of analytics gathering servers (via squid originally and then dnsscrypt-proxy - because my blacklist build script has been with me for years) , and sites that i want to access whitelisted...again this hasnt been an issue, until this latest beta....

Hardly seems like a my side issue :)

You may not agree with my choices on whitelisting and blacklisting, but they worked fine under squid for years and then more recently dnscrypt-proxy until this release....

Please supply a valid reason why all of a sudden this is an issue...something has changed in your code, its creating a bug for which ive submitted an issue. 

Posting an opinion isnt an answer....

Cheers

**Comment by jedisct1** [comment]
Due to popular demand, and as mentioned in the change log, blacklists/whitelists are now applied to aliases (`CNAME`). The site you [mentioned](#1082 ) is an alias to something you are blocking.

If you want to block an entire domain but not subdomains, or specific names pointing to it, you can add exceptions to the whitelist file.
