### ISSUE TITLE
A very German issue (dnscrypt-proxy as local DoT server)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1093]
Hello Frank,
thank you for implementing this feature already:
> dnscrypt-proxy can now act as a local **DoH** server

As you have seen in the title I'd like you to also add this feature for the **DoT** protocol.
You may ask why? The reason is simple: AVM, a German router manufacturer with 60% market penetration in Germany. All major telcos in Germany like Telekom and 1und1 use AVM hardware (Fritz!box) as well as numerous cable providers.

This December they will roll out DoT support in hardware:
https://translate.google.cl/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fwww.heise.de%2Fnewsticker%2Fmeldung%2FFritzOS-7-19-Bessere-WLAN-Verschluesselung-WPA3-fuer-AVMs-Fritzboxen-4597676.html

Image of the router's GUI:
https://www.heise.de/imgs/18/2/7/9/6/4/2/9/Bildschirmfoto_von_2019-11-28_10-58-26-aec1738ae5b9974b.png

(All LAN devices automatically receive hostnames like raspberry.fritz.box and the like. So it could be entered as text as DoT server.)

I am asking you now, since it is more likely that you will be forthcoming to implement this than a faceless tech company. Please bring the local DoT support to dnscrypt-proxy. You already have local DoH in place. And you will help millions of people in Germany as well as possibly Austria and other countries AVM sells their cable, vdsl and dsl routers to.

Currently only 2 DoT servers exist for German users that are provided by non-US sources:
https://fr.wikipedia.org/wiki/Digitalcourage
https://fr.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_Num%C3%A9rique

dnscrypt-proxy would allow access to over a hundred servers that can be trusted.

Sorry for the wall of text, but I had to explain that this is actually a meaningful addition that is not just for myself but everyone who is in IT and owns AVM hardware. It is easier to feed the router with DoT data from dnscrypt-proxy than changing the DNS server manually of every device. Especially for IoT, phones and TVs.

**Comment by ibksturm** [comment]
@cipherninja 

salü, du könntest auch folgende dot server nehmen

https://digitalcourage.de/support/zensurfreier-dns-server

https://www.digitale-gesellschaft.ch/dns/

aaah die hast du schon, grad erst jetzt gesehen

https://ffmuc.net/wiki/doku.php?id=knb:dohdot (freifunk münchen)

https://www.switch.ch/security/info/public-dns/

https://www.trash.net/dienste/offener-dns-resolver/

https://ibksturm.synology.me (meiner)



notabene Frank mag DoT aus Gründen nicht, die hat er hier in github schon mal Gründlich ausgeführt

**Comment by jedisct1** [comment]
Hi @cipherninja,

Are they planning to require DoT to be used, i.e. make it impossible to use regular DNS ? 

From the article and UI, it doesn't look like this is the case, and DoT will even come disabled by default.

**Comment by ghost** [comment]
@ibksturm 
Merci for these suggestions, having more than two servers is always good!
Yeah DoT and DoH both have their pros and cons. I don't want to start a war. Fact is it will be very hard to get this router manufacturer to add more protocols. They just picked what was easiest for themselves to implement.

@jedisct1 
Currently they implement it either as DoT preferred (if enabled) with (optional) fallback to unencrypted IPv4 or IPv6 servers. They are just offering it as a long requested feature.

**Comment by dodmi** [comment]
@cipherninja I don't see, where's the benefit of your feature request. As I understand, you like to realize this setup:
Client uses FritzBox as DNS (configured dynamically by DHCP)
FritzBox uses DNSCrypt-Proxy as DNS (configured statically as DoT)
DNSCrypt-Proxy does the name resolution over the internet (at any configured DoH or DNSCrypt server)

But as the (default) client will send its DNS queries to the FritzBox unencrypted, the queries can be read inside your LAN. Therefore encrypting the queries between FritzBox and (internal) DNSCrypt-Proxy does not protect the DNS queries from being visible in the LAN. Just assign a fixed ip to your machine running DNSCrypt-Proxy and use it as default DNS-Server in your FritzBox. 

If you really like a DoT capable DNS proxy, look at https://github.com/AdguardTeam/dnsproxy it can act as DNS/DoT/DoH-Server and is able to query DoT, DoH and DNSCrypt servers. But it's no match for DNSCrypt-Proxy. It lacks the variety of configuration and blocking options.

@ibksturm @jedisct1 I know, the topic with implementing DoT was already discussed. But I see one advantage from DoT over DoH: While DoH uses the same port as HTTPS, DoT uses the designated port 853 and can therefore be easily separated from standard HTTPS traffic. (You can also say it's a disadvantage).
But many security softwares inspect HTTPS traffic for Malware. This isn't needed for DNS requests, but they use the same port with DoH, so it would get analysed. The problem is, that security software does this by acting as man in the middle and therefore intercepts the TLS encryption. The certificates, which are seen by DNSCrypt-Proxy are not the ones used in the original certificate chain, so the Stamp containing a certificate hash won't fit to the actual seen certificate hashes and therefore doesn't work to configure a DoH server.
A second argument for implementing DoT support would be, that the [stamp format definition](https://dnscrypt.info/stamps-specifications) supports DoT servers, so with DoT support, any stamp a user adds to the config, could be handled correctly.

**Comment by ghost** [comment]
@jedisct1 
No problem, it was a nice to have but not must have. I just have less fallback this way if the two raspberries go down.

@Big--Mike 
Since the issue is close I see no point to explain in detail, but I had good reasons, but thank you for the idea of a workaround.
