### ISSUE TITLE
Strange issue with some websites, blocked sites getting suffixed to domain.

### ISSUE THREAD

**Issue by njscorpion** [DNSCrypt/dnscrypt-proxy#1098]
how do i block *.edgesuite.net without blocking indiatoday.in? because while trying access some sites like indiatoday.in, imdb.com, hooq.tv etc edgesuite.net is suffixed to the domain name (don't know why?!?) because of this the actual site is getting blocked.

I hope i am able to convey my strange situation, if not i can provide more details as needed!

i am using dnscrypt 2.0.34 and windows 10

Following are the partial logs and blacklists

[Content of blacklist.txt]
`edgesuite.net`

[Content of blocked.log]
```
[2019-12-08 00:21:46]	127.0.0.1	indiatoday.in.edgesuite.net	*.edgesuite.net
[2019-12-08 00:22:46]	127.0.0.1	indiatoday.in.edgesuite.net	*.edgesuite.net
[2019-12-08 00:22:46]	127.0.0.1	indiatoday.in.edgesuite.net	*.edgesuite.net
```

[Content of query.log]
`[2019-12-08 00:21:46]	127.0.0.1	www.indiatoday.in	A	REJECT	306ms	aaflalo-me-gcp`
Following are the partial logs and blacklists

Thanks & Regards.

**Comment by jedisct1** [comment]
`edgesuite.net` is Akamai. It's a content delivery network that many major websites use to deliver their content. It probably delivers 20% of the internet. 

You probably never want to block this unless you really understand what it is.

If you really want to do it (which is very weird, it's like blocking all websites hosted by Amazon), you can add hostnames to the whitelist file.

**Comment by njscorpion** [comment]
Ok! it got added to my blacklist this week, when i generated it. will add it to my white list. 

Thank a lot

**Comment by stylemessiah** [comment]
The blacklisting will override any whitelisting if theres a root domain in the blacklist, this is why i have asked 5 times now for the CNAME listing to be toggleable, because it breaks fucntionality of well established blacklists....

But you seem to close these issue reports and ignore feedback, because its like screaming at a brick wall....

Ive removed dnscrypt-proxy from my PC until you actually take feedback seriously....
