### ISSUE TITLE
Is there a way to change the format of date/time in the logs?

### ISSUE THREAD

**Issue by rr0ss0rr** [DNSCrypt/dnscrypt-proxy#1112]
Hi .. I've been looking at the logs lately and the EPOCH date is meaningless to me without manually converting.  Is there a way to change the date format to something else?

Thanks

**Comment by jedisct1** [comment]
Timestamps in logs are in local time (or whatever your system has been configured with).

But you can't change the format, sorry.

**Comment by welwood08** [comment]
I just happened to be looking at the logging code and realised what you meant by "EPOCH date". If you simply want a human-readable date format, use `tsv` instead of `ltsv` as your log format - the only information you lose is "cached", but if a query is cached then the server is also set to "-" so it's effectively the same.

**Comment by rr0ss0rr** [comment]
Great! .. Thanks for the follow up.

**Comment by jedisct1** [comment]
Ahhh, I thought it was a way to mean UTC timestamps.

Yes, `ltsv` is mainly designed to be parsed by scripts and log processors, not by humans :)
