### ISSUE TITLE
Disabling DNSSEC ideally per domain, if not possible entirely.

### ISSUE THREAD

**Issue by gaia** [DNSCrypt/dnscrypt-proxy#1118]
## Subject

* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description

I use portable dnscrypt-proxy for win64 (current version), and several times a day I get a Name Resolution Error (or similar message, as indicated by chrome), always on the same domain. After hitting CTRL-F5 a few times, the target page comes up.

The resolvers are quad9 (configured per their recommendation linked at the [bottom of this page](https://www.quad9.net/dnscryptlive/)).

This ONLY happens to one domain I visit frequently, and this domains has DNSSEC enabled. **I would like to config DNScrypt-proxy to disable DNSSEC, at least for this domain. Is this possible? If not, I'd rather disable DNSSEC entirely.**

**Comment by jedisct1** [comment]
Hi,

If a domain is not properly configured, a validating DNSSEC resolver will return an error and no usable data at all.

This is done by the resolver; a client cannot do anything about it - if it could, it would completely destroy the purpose of DNSSEC.

But wait, there is hope :)

One thing you can do is, for that specific domain, to use a different resolver. That can be done with the [forwarding](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding) feature. Cisco resolvers, for example, don't support DNSSEC, so you can use them just for that domain.

Another possible workaround is to configure `dnscrypt-proxy` to directly return the IP address instead of asking a resolver. The [cloaking](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Cloaking) features can do that.

**Comment by gaia** [comment]
Hey

Forwarding sounds like a great option. as long as Cisco resolvers support DoH. I imagine they do, otherwise it wouldn't be suggested. I entered

`problemdomain.com 208.67.222.222,208.67.220.220`

in `forwarding-rules.toml`. Let's see how that works...

Thanks!!
