### ISSUE TITLE
Automatic blacklist 

### ISSUE THREAD

**Issue by JuliusBairaktaris** [DNSCrypt/dnscrypt-proxy#1127]
Maybe implement a feature to automatically download a blacklist file using github sources?

**Comment by jedisct1** [comment]
A bit of postprocessing is often needed to properly extract domain names, normalize them, remove redundant/overlapping entries, remove false positives...

In order to do so, there is already a script that does most of these, and people also add their own sauce to build lists that fit their needs.

Just downloading lists would offer zero optimization or customization. So it's better left as an external process.
