### ISSUE TITLE
[Feature Request] DoH back-end

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#1136]
I tried use dnscrypt-proxy as DoH back-end for nginx. Proxy crashed if `cert_file` and `cert_key_file` disabled in main config. Add support http requests, if cert file and key disabled.

**Comment by jedisct1** [comment]
It didn't crash, but `[FATAL] open : no such file or directory` (because the file names were empty) was not a very useful error message. So it has been changed to be more explicit about the fact that a local DoH service requires a certificate.

The local DoH service is a minimal DoH implementation meant to be used locally, from local web browsers. It was not designed to be exposed externally. Using it that way, even behind `nginx` would be slow, non standard conformant and insecure.

**Comment by black-cerberon** [comment]
Why insecure?

**Comment by jedisct1** [comment]
An untrusted client could easily crash it. See [rust-doh](https://github.com/jedisct1/rust-doh) if you want to run a DoH server.
