### ISSUE TITLE
cloudflare not found

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1140]
https://ibb.co/pJHbjHD
https://ibb.co/1zZ8twT

`./dnscrypt-proxy` command
`cloudflare` not found

**Comment by jumpsmm7** [comment]
I concur with this statement. My logs say the hash failed. neither cloudflare servers not found.

**Comment by zhfreal** [comment]
[2020-01-08 10:29:06] [INFO] [cloudflare] TLS version: 303 - Protocol: h2 - Cipher suite: 49195
[2020-01-08 10:29:06] [ERROR] Certificate hash [eb7525f88f0d9458f81a995019bfd34cb89ccdc957e7b0ef315f10f897638118] not found for [cloudflare]

**Comment by zhfreal** [comment]
same here

**Comment by zhfreal** [comment]
DNS Stamps is not correct?

**Comment by jumpsmm7** [comment]
either that or cloudflare outage.

**Comment by jumpsmm7** [comment]
https://github.com/DNSCrypt/dnscrypt-resolvers/commit/aa4454354505189d2bde4e71664871277ed45957

here is the updated info on the servers committed 8 minutes ago

**Comment by ghost** [comment]
Connected. thx !! 

https://1.1.1.1/help#eyJpc0NmIjoiWWVzIiwiaXNEb3QiOiJObyIsImlzRG9oIjoiWWVzIiwicmVzb2x2ZXJJcC0xLjEuMS4xIjoiWWVzIiwicmVzb2x2ZXJJcC0xLjAuMC4xIjoiWWVzIiwicmVzb2x2ZXJJcC0yNjA2OjQ3MDA6NDcwMDo6MTExMSI6Ik5vIiwicmVzb2x2ZXJJcC0yNjA2OjQ3MDA6NDcwMDo6MTAwMSI6Ik5vIiwiZGF0YWNlbnRlckxvY2F0aW9uIjoiSUNOIiwiaXNXYXJwIjoiTm8iLCJpc3BOYW1lIjoiQ2xvdWRmbGFyZSIsImlzcEFzbiI6IjEzMzM1In0=

**Comment by tve** [comment]
Why was this simply closed? Is this going to recur the next time they make a change? Is there no way to make dnscache-proxy more robust? This broke in the middle of the night for me and caused quite some havoc.

**Comment by jedisct1** [comment]
Ignoring an entry if the certificate is invalid is the expected behavior.

"More robust" would be not verifying certificates.

If you don't care much about security, hashes can be removed from Cloudflare's stamp. But unless they frequently change their certificate chain to the point that it's impossible to keep up, we should probably not go that route.

The best way to deal with configuration or resolver failure is to use more than a single resolver. 

And if the information for a resolver is incorrect or outdated, report it ([here](https://github.com/dnscrypt/dnscrypt-resolvers) as the problem is in a list, not in the software) so that the relevant list can be updated as soon as possible.
