### ISSUE TITLE
TOML error message

### ISSUE THREAD

**Issue by jonba2019na** [DNSCrypt/dnscrypt-proxy#1170]
Hi everyone, I'm new to programming and linux environments in general, in any case I tried setting up the proxy on tails (based on debian) 4.2.2 - with persistent volume, according to the instructions provided on https://www.linuxuprising.com/2018/10/install-and-enable-dnscrypt-proxy-2-in.html, I've set the network card dns on 127.0.2.1 and left the oher option on automatic dhcp, I've edited the dnscrypt-proxy.toml file as provided in the configuration section of the wiki, with some filters (dnssec,ipv4, no log, etc.) and leaving server names blank, and in an other case with specific servers leaving the filter part put and specifing the stamps. In both cases, I've edited the dnscrypt-proxy.socket file with listen and data stream set on 127.0.2.1.Once I restart netmanager and the proxy service and socket through command line, the output (I repeat in both of the above mentioned cases , the first of which leaving blank serrver names ,and  the second of which, specifying them) thorugh systemctl status is:
1. that the socket is active and listening on both streams of the before mentioned addresses
2.Whereas for the service it says that it has failed, displaying the following message: cannot load TOML value of type [ ] interface {} into a Go string. How can I solve this problem?

If you happen to need any other info, just contact me, or reply, thanks in advance for any suggestions.

**Comment by jedisct1** [comment]
Start with the example configuration file, and change only one thing at a time.

That way, whenever there is a mistake somewhere, you know that it's in the previous change.

**Comment by jonba2019na** [comment]
Dear jedisct1,

I've uninstalled and reinstalled dnscrypt-proxy,through command line, once I run both the service and socket (always on command obviously, and without editing nor the toml file nor the socket one), I get the following messsage : 

[NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolver [9.9.9.9:53]

[NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolver [9.9.9.9:53]

[CRITICAL] Unable to use source [public-resolvers]: [write udp 192.168.1.4:54957->9.9.9.9:53: write: operation not permitted]
 [FATAL] No servers configured
.

Should I try changing file permissions in var/cache folder,where according to the original (untouched) toml file,  the resolver list is downloaded? Or what else could I do?

**Comment by jedisct1** [comment]
This installation procedure way too complicated for my limited knowledge of systemd.

On Linux (and MacOS, and Windows) I would just install it with `./dnscrypt-proxy -service install` as [documented](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux#installation-on-linux-overview). I've never done it differently.

**Comment by jonba2019na** [comment]
Thanks anyways

**Comment by iWARR** [comment]
I can say I often have same issues on Android. It's relative to how fallback resolver works. Probably, because it's hard to make a universal fallback scheme for different OS. On Windows it's not bad, but on Android it needs for improvements.

Sometimes I need to **enable Internet connectoin + Reboot** several times before dnscrypt-proxy will make a proper connection and will be able download *.md files. It's a fact.

To make things better, try set DNS: 127.0.0.1 instead of 192.168.1.4 in your Wi-Fi Network settings. In fact, dnscrypt-proxy will start working a bit reliable (first connection / updating *.md).

For example, on Android cellphone, **dnscrypt-proxy + Wi-Fi** scheme works a bit predictable then **dnscrypt-proxy + Mobile**, because I can set for Wi-Fi DNS: 127.0.0.1 | 127.0.0.1. But there no way to do it for Mobile Network. And I can get the same error:

[CRITICAL] Unable to use source [public-resolvers]: [write udp **Mobile DNS IP:Port** -> **Fallback DNS IP:Port** write: operation not permitted]

or other errors with resolving githubusercontent.com / downloading *.md files

On Android I use "Override DNS" to override 127.0.0.1 for the both Wi-Fi & Mobile networks. It should be enough, but not always.  Setting the same value 127.0.0.1 also in the Wi-Fi Network properties helps a bit. Then I have in logs:

**Wi-Fi Network :**
... `127.0.0.1` `example.com` ...

**Mobile Network:**
... `Mobile DNS IP`  `example.com` ...

And the first variant works a bit more reliable, than the second one... In spite of "Override DNS" overrides 127.0.0.1 for both...

Since v2.0.38 the reability becomes better, but I'm afraid it's still not enough for the stable first launch / updating *.md files time to time. May be "Override DNS" app need for updating, I don't know..
