### ISSUE TITLE
more than one computer and same public ip to dnscrypt server or relay

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1185]
Subject
I am a Windows user and i have a question about dnscrypt proxy 2
## Description

Hi, i use your app with Windows 10 and 7. All is well and stable and your app is very usefull for hide dns queries from ISP.

I wanted to know, 

1) in case i use same server or relay from two differents computers (running dnscrypt proxy 2) with same public ip. Or more.
How the two signals (or more) are used by server?
Is it permitted by dnscrypt proxy functionality?

2) about port, can i choose a special port for servers or relays or must i use default one?
exemple server:443.

In two cases, if 2) is possible and 1) not, must i set different ports for each computers (toml) on same ip and server or relay?

*** I cannot use dnscrypt proxy with my modem).

Thanks

Regards

Samuel P

**Comment by jedisct1** [comment]
Yes, you can use the same server from multiple devices behind the same router, just like multiple devices can connect to the same website at the same time.

TCP/IP was designed for this, having both source and IP ports for each connection or datagram. Your router will know how to properly dispatch incoming packets to the originating device.

You must use a port that the server listens to, or it will not be able to reply. 443 is the most common one because this is the least likely to be blocked.

**Comment by ghost** [comment]
Thanks for answer.

Samuel P
