### ISSUE TITLE
DNSSEC or not?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1187]
Subject
DNSSEC or not?

* I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

Hi, i use dnscrypt proxy 2 with Windows 10 as well.

But i just see lot of servers haven't DNSSEC. For example, all criptostorm servers aren't DNSSEC.

I just want to know why? Must i use only DNSSEC servers? What is the real difference?
I understand if you give this resolvers, all is ok but.... i understand too, DNSSEC is a security to authenticate the results from the dns queries, so it's important.

Same side, dnscrypt v2 exists from long time, do you think, in 2020, the dnscrypt servers should implement all dnscrypt v2?

*** Actually, the dnscrypt v2 resolvers from the public list aren't indicated by app to use v2 but v1. From some month they were in v2.

Thanks

Samuel P

**Comment by black-cerberon** [comment]
DNSSEC defend you from DNS Spoofing.

**Comment by jedisct1** [comment]
If you are on the fence between two servers with similar latency, one doing DNSSEC validation, the other one not doing it, pick the one doing DNSSEC.

Otherwise, unfortunately, DNSSEC has never proven to be useful for anything in practice.

DNSSEC spoofing happens at ISP level or on your network, and DNSCrypt provides much better protection.

Domains that are hijacked are hijacked at registrar level, and DNSSEC is completely useless against that.

**Comment by ghost** [comment]
The Jedisct1 for answer.
That's what i was thinking about DNSSEC. Nice function but for a minimum risk.
Needed only when this is a choice between with or without.

But, technically, it will be nice to have DNSSEC on all servers. I'm not engineer (you do a nice work) and i don't know if it's hard to implement in a server.
Same thing for dnscrypt v2...

It will be very nice to provide for freedom the best level you can.

If i was dnscrypt actor, i should ask to every nice guy and there dnscrypt servers, to provide DNSSEC and dnscrypt v2 as normality...

regards

Samuel
