### ISSUE TITLE
About cache

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1190]
Subject
"cache"

* [ ] I have a question about dnscrypt proxy as a windows user

Hi,

I use dnscrypt proxy 2 x64 as well, and continu to learn how to use.

I use a good connection, SSD and a good CPU, and after some tests i've understand i can use dns without cache.

can i delete the option?

Thanks

regards

Samuel

**Comment by jedisct1** [comment]
Caching is to avoid network connections, so that if the same thing is asked twice, the response will be sent from the cache rather than asking the server the same thing over and over again.

Caching improves speed and privacy, but also reliability since if the server has a temporary outage or is slow, responses can be served from the cache.

The SSD and CPU are irrelevant.

You can lower the default value, which is already pretty small. Or disable it with `cache = false`, but it's usually not a good idea.

**Comment by ghost** [comment]
Hi and thanks so much to take time to answer.

So, for privacy, you recommand to use cache? Really?

I was thinking cache could be a vulnerabilty fur user data, if "someone" can access to cache from Wild.
But i understand if query is resolved locally (by cache) it doesn't need to send it on servers.

So ok, i will try cache.

1 * Have you informations about how to use cache the better way (options settings)?

1b When i shutdown computer, does the cache been deleted?

2 * About cache, i know there is a windows dns service (cache), a dns cache (prefetch) in the internet explorer (firefox for example) and this of dnscrypt proxy.

3 * Have you recommandations using those caches for better privacy?
(I use to disable windows dns cache and disable too, firefox prefetch).

4* What happened if i set the system dns option to true? does it use only system dns cache and not the app cache?
What is the best for privacy? I think windows maybe have a better cache?
In case of i use system dns cache true, can i set (app) cache to false?

4 * Last question, the intregrity of the cache is it verified by app? Maybe stupid question...

regards

Sam

**Comment by jedisct1** [comment]
Just use the defaults.
