### ISSUE TITLE
How to verify that relays are actually being used?

### ISSUE THREAD

**Issue by Bonilla** [DNSCrypt/dnscrypt-proxy#1200]
I have defined some routes via relays in `dnscrypt-proxy.toml` to turn on Anonymized DNS. How can I verify that dnscrypt-proxy is actually using those relays to make queries?

The query log file shows only the resolving server being queried but it does not give any indication of whether relays are being used to reach those DNS servers:

> [TIMESTAMP]   127.0.0.1       www.amazon.com  AAAA    PASS    20ms    quad9-dnscrypt-ip4-nofilter-alt
[TIMESTAMP]   127.0.0.1       www.amazon.com  A       PASS    22ms    quad9-dnscrypt-ip6-nofilter-alt
...

The only clue that I could find is in the application's general log file: 

> [TIMESTAMP] [NOTICE] Source [relays] loaded
[TIMESTAMP] [NOTICE] Anonymized DNS: routing [quad9-dnscrypt-ip4-nofilter-alt] via [anon-scaleway-ams anon-v.dnscrypt.uk-ipv4]
[TIMESTAMP] [NOTICE] Anonymized DNS: routing [quad9-dnscrypt-ip6-nofilter-alt] via [anon-scaleway-ams-ipv6 anon-v.dnscrypt.uk-ipv6]
...

Many thanks for your help!

**Comment by ghost** [comment]
Hi,

_You use anonymised DNS for all servers you set in TOML with routes and relays._

_______________________________________________________

**LOG APP:**

**How to verify that relays are actually being used?**

> **FOR RELAY:**

> This line in log shows you, the relay and informs you the server you have chosen behind the relay.

[TIMESTAMP] [NOTICE] Anonymized DNS: routing [quad9-dnscrypt-ip4-nofilter-alt] via [anon-scaleway-ams anon-v.dnscrypt.uk-ipv4]

The server quad9-dnscrypt-ip4-nofilter-alt is selected and will be relayed by anon-scaleway-ams anon-v.dnscrypt.uk-ipv4 and the relay connection is OK.




> **FOR SERVER BEHIND RELAY:** 

Look in the log some lines after those relating anonymised DNS informations.


This is an example of this Logs lines:
....
[2020-02-18 21:51:36] [NOTICE] [quad9-dnscrypt-ip4-nofilter-pri] OK (DNSCrypt) - rtt: 25ms
[2020-02-18 21:51:36] [NOTICE] [quad9-doh-ip4-nofilter-pri] OK (DoH) - rtt: 20ms
...

**** You can see  server name, "OK" if the server can be connected, if dnscrypt or doh protocol is used, and ping (in ms).

Ping is used for sort connections.

!!!!! Anonymised DNS is only available with dnscrypt v1 or last, v2 protocol. And latest dnscrypt-proxy release.

****ping in ms is time for connection between the user's computer and the server the user is connected.



If the server is not connected, you will see information like TIMEOUT (the server has waiting more than a defined standard maximum timing), or cert error, ... etc.

Example of informations where the server isn't connected:

[2020-02-18 21:51:41] [NOTICE] [cs-pl] TIMEOUT
[2020-02-18 21:51:41] [WARNING] [cs-nl] Incorrect signature for provider name: [2.dnscrypt-cert.cryptostorm.is.]


_______________________________________________________

**CONNECTION TEST:**

For test connection, disable first (for Windows) the dnscrypt-proxy service, in Windows settings.

and lauch the dnscrypt-proxy.exe (for Windows) as admin and look "something beautifull"

!!! If nothing happened, two things:

-the service is running,
-your toml conf file is not good.

Restart service when all is good for you.

_______________________________________________________

Edit: sorry i just realize.. i've determined you're a Windows user, because if not, you would have precised it... if needed i can give you the way for linux.
It's same approach but with linux cmd from the app folder.

**Comment by Bonilla** [comment]
Thanks for the clarifications! I guess it would be helpful if the query log was more verbose regarding the use of relays. Maybe this would be a good feature request?

Btw, my dnscrypt-proxy is running on Raspbian. :)

**Comment by jedisct1** [comment]
You can also use a network logging tool such as `tcpdump` to verify that packets are only sent to relays.

Logs are already quite verbose. I'm not sure that it is worth repeating the same data in every single line.

**Comment by ghost** [comment]
@Bonilla 
I don't know Raspbian.. i will learn...

For linux and from dnscrypt-proxy directory (command emulator):
*  From Jedisct1 TUTO:
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-linux

Test connexion:
./dnscrypt-proxy

Start service:
./dnscrypt-proxy -service start

Stop service:
./dnscrypt-proxy -service stop
