### ISSUE TITLE
Can't set [::]:53 to listen address

### ISSUE THREAD

**Issue by toorich** [DNSCrypt/dnscrypt-proxy#1217]
## *Who* is the bug affecting?

dnscrypt-proxy.exe

## *What* is affected by this bug?

The service can't start with error 1067.

## *When* does this occur?

When I set [::]:53 as listen address, the service can't start.

## *Where* does it happen?

Windows 10 1803 x64, used with Simple DnsCrypt GUI.

## *How* do we replicate the issue?

Set the value of```listen_addresses``` in dnscrypt-proxy.toml to [::0]:53

## Other Comments

I want use dnscrypt-proxy by global resolver (both IPv4 and IPv6), it need setting [::]:53 as the listening address. But I can't set it.

**Comment by welwood08** [comment]
Since it's unclear from your description, please can you confirm exactly what you set in `dnscrypt-proxy.toml`? For example, only 1 of the following is valid configuration syntax even if they appear similar:
- `listen_addresses = ['[::]:53']`
- `listen_addresses = '[::]:53'`
- `listen_addresses = [::]:53`

According to the comment in the example config, to listen on both IPv4 and IPv6 you should use `listen_addresses = ['127.0.0.1:53', '[::1]:53']`. If you really mean to use the unspecified address and listen on all interfaces, then the equivalent would be `listen_addresses = ['0.0.0.0:53', '[::]:53']` but I don't know if this is even supposed to work without digging into the code so maybe that's the problem you're encountering?

I also don't know what error 1067 means or where it comes from (I guess Simple DnsCrypt GUI, in which case you might have better luck reporting the issue to them), it would be more useful if you could provide the actual error message that is logged when the service fails to start.

**Comment by toorich** [comment]
> Since it's unclear from your description, please can you confirm exactly what you set in `dnscrypt-proxy.toml`? For example, only 1 of the following is valid configuration syntax even if they appear similar:
> 
> * `listen_addresses = ['[::]:53']`
> * `listen_addresses = '[::]:53'`
> * `listen_addresses = [::]:53`
> 
> According to the comment in the example config, to listen on both IPv4 and IPv6 you should use `listen_addresses = ['127.0.0.1:53', '[::1]:53']`. If you really mean to use the unspecified address and listen on all interfaces, then the equivalent would be `listen_addresses = ['0.0.0.0:53', '[::]:53']` but I don't know if this is even supposed to work without digging into the code so maybe that's the problem you're encountering?
> 
> I also don't know what error 1067 means or where it comes from (I guess Simple DnsCrypt GUI, in which case you might have better luck reporting the issue to them), it would be more useful if you could provide the actual error message that is logged when the service fails to start.

I have tried starting dnscrypt-proxy manually, but it also reports an error, the output is as follows:
```
[2020-03-07 01:15:32] [NOTICE] dnscrypt-proxy 2.0.39
[2020-03-07 01:15:32] [NOTICE] Network connectivity detected
[2020-03-07 01:15:32] [NOTICE] Source [public-resolvers] loaded
[2020-03-07 01:15:32] [NOTICE] Source [relays] loaded
[2020-03-07 01:15:32] [NOTICE] Firefox workaround initialized
[2020-03-07 01:15:32] [FATAL] listen udp 0.0.0.0:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
I set ```listen_addresses = ['0.0.0.0:53', '[::]:53']```.

**Comment by jedisct1** [comment]
I think it means that it was already running, so you tried to run it twice.

**Comment by toorich** [comment]
> I think it means that it was already running, so you tried to run it twice.

I tried to run it several times, but it didn't work properly, the output is as follows:
```
[2020-03-07 16:18:47] [NOTICE] dnscrypt-proxy 2.0.39
[2020-03-07 16:18:47] [NOTICE] Network connectivity detected
[2020-03-07 16:18:47] [NOTICE] Source [relays] loaded
[2020-03-07 16:18:47] [NOTICE] Source [public-resolvers] loaded
[2020-03-07 16:18:47] [NOTICE] Firefox workaround initialized
[2020-03-07 16:18:47] [NOTICE] Now listening to 0.0.0.0:53 [UDP]
[2020-03-07 16:18:47] [NOTICE] Now listening to 0.0.0.0:53 [TCP]
[2020-03-07 16:18:47] [FATAL] listen udp [::]:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

**Comment by welwood08** [comment]
As @jedisct1 said, the message `[FATAL] listen udp [::]:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.` means something else is already listening on `[::]:53`. If you're certain the first attempt to start dnscrypt-proxy was unsuccessful then you should be able to use Resource Monitor's Network tab to identify which existing process is listening on that port.

**Comment by toorich** [comment]
> As @jedisct1 said, the message `[FATAL] listen udp [::]:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.` means something else is already listening on `[::]:53`. If you're certain the first attempt to start dnscrypt-proxy was unsuccessful then you should be able to use Resource Monitor's Network tab to identify which existing process is listening on that port.

But there is no problem using only one of them.

**Comment by welwood08** [comment]
Since I couldn't work out what problem you're trying to describe, I decided to actually try it. It looks like when using the unspecified address, the socket is automatically dual-stack. Consequently, it doesn't matter if you use `listen_addresses = ['0.0.0.0:53']` or `listen_addresses = ['[::]:53']` or even just `listen_addresses = [':53']` - you'll always be listening on both IPv4 and IPv6 (I confirmed on both Windows and FreeBSD, I'm assuming Linux behaves the same).

Being unaware of this special behaviour for unspecified addresses, I was wrong to advise `listen_addresses = ['0.0.0.0:53', '[::]:53']`. The 2nd listen address was unable to bind because the 1st listen address was already listening on both IPv4 and IPv6.

I'm not sure if there's any resolution to this issue other than to learn of the existence of this automatic dual-stack behaviour for unspecified addresses, but feel free to disagree.

**Comment by toorich** [comment]
> Since I couldn't work out what problem you're trying to describe, I decided to actually try it. It looks like when using the unspecified address, the socket is automatically dual-stack. Consequently, it doesn't matter if you use `listen_addresses = ['0.0.0.0:53']` or `listen_addresses = ['[::]:53']` or even just `listen_addresses = [':53']` - you'll always be listening on both IPv4 and IPv6 (I confirmed on both Windows and FreeBSD, I'm assuming Linux behaves the same).
> 
> Being unaware of this special behaviour for unspecified addresses, I was wrong to advise `listen_addresses = ['0.0.0.0:53', '[::]:53']`. The 2nd listen address was unable to bind because the 1st listen address was already listening on both IPv4 and IPv6.
> 
> I'm not sure if there's any resolution to this issue other than to learn of the existence of this automatic dual-stack behaviour for unspecified addresses, but feel free to disagree.

It works, thanks!
