### ISSUE TITLE
Question about Anonymized DNS

### ISSUE THREAD

**Issue by Bnwqo** [DNSCrypt/dnscrypt-proxy#1235]
## Subject
* [ ] Other

## Description

I fairly understand ADNS. I just have a question about the use of ADNS with a resolver. I don't use "server_names," instead I default to using any server with the require_* filters.

I stumped on what to add in the "server_name=" field under **[anonymized_dns]**

My "routes" section looks like:

>   routes = [
     { server_name='example-server-1', via=['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4'] },
  ]

**Comment by tigernero79** [comment]
```
route = [
{server_name = 'YOUR DNS Server', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
]

```

where for "your dns server" you have to put the name among those you have chosen in the initial where for "your dns server" you have to put the name among the name servers you have chosen in the initial name server section

you have to use only those that are dnscrypt servers of course.

example= `server_names = ["nextdns", 'scaleway-fr', 'cloudflare']`

if you chose example 
1) cloudflare 
2) nextdns
3) scaleway-fr

the only one that can take advantage of Adns is scaleway-fr as the other two are not dnscrypt servers.

ce scaleway-fr so you will do this:

```
route = [
{server_name = 'scaleway-fr', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
]

```
the list of servers that have the dnscrypt protocol can be found here:

https://dnscrypt.info/public-servers/

**Comment by Bnwqo** [comment]
I'm not using `server_names =` as mentioned above. Only the require_* filters.

**Comment by tigernero79** [comment]
then write like that:

```
route = [
{server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
]

```

**Comment by inputuserhere** [comment]
> then write like that:
> 
> ```
> route = [
> {server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
> ]
> ```

You can't do that either. According to the documentation you need to have something defined in under server_names in order for it work.

I don't believe there is a way to properly do this without using "server_names". I could be wrong though, maybe someone else can chime in.

**Comment by tigernero79** [comment]
no need to specify server names.

> > then write like that:
> > ```
> > route = [
> > {server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
> > ]
> > ```
> 
> You can't do that either. According to the documentation you need to have something defined in under server_names in order for it work.
> 
> I don't believe there is a way to properly do this without using "server_names". I could be wrong though, maybe someone else can chime in.

no need to specify server names.

**Comment by gspannu** [comment]
What is the easiest way to test whether anonymised forwarding is working? I looked at the Query.log, but it does not show any detail of which relay was used (or used).

Any commands/ logs to check that DNS queries are indeed going through the relays? 

I’m sure there must be some way to do this via tcpdump but I am not conversant with the command - so any help or instructions would be appreciated.

**Comment by inputuserhere** [comment]
> no need to specify server names.
> 
> > > then write like that:
> > > ```
> > > route = [
> > > {server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
> > > ]
> > > ```
> > 
> > 
> > You can't do that either. According to the documentation you need to have something defined in under server_names in order for it work.
> > I don't believe there is a way to properly do this without using "server_names". I could be wrong though, maybe someone else can chime in.
> 
> no need to specify server names.

Sorry, I was referring to server_names from the toml file: 

```
List of servers to use

Servers from the "public-resolvers" source (see down below) can
be viewed here: https://dnscrypt.info/public-servers

If this line is commented, all registered servers matching the require_* filters
will be used.

The proxy will automatically pick the fastest, working servers from the list.
Remove the leading # first to enable this; lines starting with # are ignored.

server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']
```

You would define it there and list them below in the Anonymized DNS section. If nothing is defined up there then you can't use a *wildcard below, the way I understand it.

```
route = [
{server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
]
```

**Comment by gspannu** [comment]
> 
> You would define it there and list them below in the Anonymized DNS section. If nothing is defined up there then you **can't use** a *wildcard below, the way I understand it.
> 
----------------------------------------------------------
I believe you can use this 
`route = [
{server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']},
]`

along with this setting
`# server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']`
_Commenting the line contains will cause name servers to be chosen automatically._

This should have the following effect:
1) the script will automatically pick up the server_names as nothing is specified as name_server (as commented above)
2) the routes entry will enforce that the specified relays are used for **any** name_server from the auto-built list (since we have not defined any specific name_servers)

I guess it is not recommended because you cannot control which relays are used for which servers and you may end up using name_servers from same businesses as relays. 
For e.g., the _name_server_ picked up could be '_v.dnscrypt.uk_' and the _relay_ used could be '_anon-v.dnscrypt.uk_' - thereby defeating the purpose of having a relay - as both entities are owned by vultr.

Technically, though the settings should work.

.... someone else can chime in if inaccurate.

**Comment by inputuserhere** [comment]
> What is the easiest way to test whether anonymised forwarding is working? I looked at the Query.log, but it does not show any detail of which relay was used (or used).
> 
> Any commands/ logs to check that DNS queries are indeed going through the relays?
> 
> I’m sure there must be some way to do this via tcpdump but I am not conversant with the command - so any help or instructions would be appreciated.

When you start up DNSCrypt, it should say [relays] loaded and "[NOTICE] Anonymized DNS: routing everything via [relay1 relay2, etc..]

But yeah I'd like hard proof of it actually working.

> > You would define it there and list them below in the Anonymized DNS section. If nothing is defined up there then you **can't use** a *wildcard below, the way I understand it.
> 
> I believe you can use this
> `route = [ {server_name = '*', via = ['anon-skyfighter', 'anon-v.dnscrypt.uk-ipv4']}, ]`
> 
> along with this setting
> `# server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']`
> _Commenting the line contains will cause name servers to be chosen automatically._
> 
> This should have the following effect:
> 
> 1. the script will automatically pick up the server_names as nothing is specified as name_server (as commented above)
> 2. the routes entry will enforce that the specified relays are used for **any** name_server from the auto-built list (since we have not defined any specific name_servers)
> 
> I guess it is not recommended because you cannot control which relays are used for which servers and you may end up using name_servers from same businesses as relays.
> For e.g., the _name_server_ picked up could be '_v.dnscrypt.uk_' and the _relay_ used could be '_anon-v.dnscrypt.uk_' - thereby defeating the purpose of having a relay - as both entities are owned by vultr.
> 
> Technically, though the settings should work.
> 
> .... someone else can chime in if inaccurate.

Initially, I had thought the same, it would just pick whatever server is available since you didn't list any. What bothered me with: `# server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']` is that in the wiki it states you **need** to define it with servers, hence you uncommenting it.

But you can control the relays used because you define them under **routes**.
