### ISSUE TITLE
dnscrypt-proxy stops itself after logging out from SSH (EdgeOS)

### ISSUE THREAD

**Issue by awooooool** [DNSCrypt/dnscrypt-proxy#1239]
Hello

I've followed this wiki's guide to install dnscrypt-proxy on EdgeOS. It works fine, however, it stops itself when I logged out from SSH. Am I doing something wrong? I'm running the latest version. Had to use tmux so that it won't stop for now. Is there anything that I can do so that I don't have to use tmux in order to use it? And how do I configure it to start at boot? (EdgeRouter X)

Thanks

**Comment by jedisct1** [comment]
What happened when you typed `dnscrypt-proxy -service install`?

**Comment by awooooool** [comment]
No, nevermind. After reboot, it's working perfectly now.

Thank you

**Comment by awooooool** [comment]
Somehow it stopped working again after updating to 1.10.11. Currently running it via tmux.

**Comment by welwood08** [comment]
I have an EdgeOS device running dnscrypt-proxy without issue. Could you elaborate how you're starting the service and maybe I can attempt to reproduce your problem? Also note that when you upgrade the EdgeOS firmware, any changes to the filesystem outside of `/config` will have been reverted so you should be aware that you will need to reinstall dnscrypt-proxy yourself.

**Comment by awooooool** [comment]
but when I `-service restart` it, it restarts just fine, like, doesn't it warn you that `You haven't installed the service yet`?

**Comment by ttfjustin** [comment]
I have the same issue, but on a USG rather than an EdgeRouter. I was under the impression my cloud controller was resetting it at regular intervals, but it makes sense that it's when it times out from SSH. I've tried committing then saving the configuration and followed everything in the guide on here - https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-on-EdgeOS

my start script looks like:

`echo '#!/bin/sh' > /config/scripts/post-config.d/dnscrypt.sh
echo '/config/dnscrypt-proxy/dnscrypt-proxy -service install' >> /config/scripts/post-config.d/dnscrypt.sh
echo '/config/dnscrypt-proxy/dnscrypt-proxy -service start' >> /config/scripts/post-config.d/dnscrypt.sh
`

This sits in /config/scripts/post-config.d/dnscrypt.sh as per the guide

When the service is running, I can see the port 53535 (which is the one I selected) in 

`netstat -lptn
`

After 10 minutes or so (my SSH still appears to be connected, I can still type in there and issue commands), netstat shows the port is no longer open. Start is again by running 

/config/dnscrypt-proxy/dnscrypt-proxy -service start

I get no complaints that the port is already bound, and netstat shows the port is available again. I've asked on the unifiy forumns but haven't had any luck.

Any guidance apreciated.
