### ISSUE TITLE
Anonamized Quad9 broken by dnscrypt update

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#1246]
Quad9 worked perfectly fine before the recent update by dnscrypt proxy; it was anonymous and everything was relayed without any issues. Please fix this bug and don't sabotage your software for special interests.

Now I am getting timeout errors using quad9, logs state "is incompatible with anonymization". It wasn't incompatible before the recent dnscrypt updates.

**Comment by jedisct1** [comment]
Quad9 was added to the list of broken resolvers because another user suggested more politely that we do: https://github.com/DNSCrypt/dnscrypt-proxy/issues/1169

If you think you know better than him, you can adjust the `broken_query_padding` list accordingly.

I don’t have Internet connectivity since the country lockdown, which makes testing these things a bit complicated.

**Comment by rugabunda** [comment]
Thank u! Eat lots of beets because [nitric oxide reduces replication of sars](https://www.evolutamente.it/covid-19-mutations-vaccines-nitric-oxide-the-vitamin-c-connection/) by 82%; [coconut kills covid](https://www.ateneo.edu/ls/sose/sose/news/research/potential-coconut-oil-and-its-derivatives-effective-and-safe-antiviral), and [vitamin c](https://www.greenmedinfo.com/blog/chinese-medical-team-report-successful-treatment-coronavirus-patients-high-dose-v0) will prevent mortality entirely. 

Enjoy the peace and quiet!

**Comment by rugabunda** [comment]
Oddly Quad9 was working just fine recently so unless they are intentionally blocking anonymous relays, I don't know how it would suddenly stop out of the blue, please explain this to me.

**Comment by rugabunda** [comment]
Thank you for fixing this up jedi

**Comment by jedisct1** [comment]
Now that I have Internet access again at home, I had a chance to look at this.

The original report was correct. Over UDP, Quad9 doesn't return anything at all when the response is larger than the question.

This is probably a bug in the server implementation they use (`dnsdist`), and I'll try to take a closer look at it. But as a result, large responses are never received.

So, no, it was not "working just fine". Some queries could never get a response.

A workaround has been implemented in version 2.0.42, but there is no way to make relaying reliable until the bug is fixed on their end.

**Comment by rugabunda** [comment]
> 
> 
> Now that I have Internet access again at home, I had a chance to look at this.
> 
> The original report was correct. Over UDP, Quad9 doesn't return anything at all when the response is larger than the question.
> 
> This is probably a bug in the server implementation they use (`dnsdist`), and I'll try to take a closer look at it. But as a result, large responses are never received.
> 
> So, no, it was not "working just fine". Some queries could never get a response.
> 
> A workaround has been implemented in version 2.0.42, but there is no way to make relaying reliable until the bug is fixed on their end.

I have not had a single issue since the initial implementation of anonymized DNS; DNS worked flawlessly on quad9 and others affected, however rare the time out error it definitely does not merit shutting down every-bodies lowest latency dns over a millisecond in a month occurrence; the burden with this lack of control I have over my DNS configuration far outweighs the unnoticeable. I must revert to 2.0.39.

**Comment by rugabunda** [comment]
So with this feature you have included in your software, any dns server could implement a DoS mechanism to de-anonymize, or shut down any anonamous relay by changing how they deal with fragmented packets. Bang now you cannot use quad9, cisco, you name it. Was working before, not anymo. technically they could do it anyway to anyone but just sayin'

**Comment by rugabunda** [comment]
> So, no, it was not "working just fine". Some queries could never get a response.
> 

well instead of some, now none ever get a response. It worked so well before that I never had an issue but under a blue moon. maybe once a week or so I would get 10 seconds of no response, now its permanent.
