### ISSUE TITLE
DNSCrypt ignoring "Disabled Servers"

### ISSUE THREAD

**Issue by inputuserhere** [DNSCrypt/dnscrypt-proxy#1292]
I am using disabled servers and DNSCrypt seems to constantly ignore my list of servers I want to disable.

disabled_server_names = ['google', 'yandex']

**Comment by jedisct1** [comment]
Let's do it together.

1) Download `dnscrypt-proxy`.

2) Copy the example configuration file:

```sh
cp example-dnscrypt-proxy.toml dnscrypt-proxy.toml
```

3) Print the list of enabled servers, and check if Google is in here:

```sh
sudo ./dnscrypt-proxy -list 2>/dev/null | grep google
```

4) Of course it is not, because `require_nolog` is set to `true`. Change it to `false` and try again.

5) Try again. Now, Google is being used.

```sh
 sudo ./dnscrypt-proxy -list 2>/dev/null | grep google
```

```text
google
```

6) Change `disabled_server_names = []` to `disabled_server_names = ['google', 'yandex']`.

7) Try again.

```sh
sudo ./dnscrypt-proxy -list 2>/dev/null | grep google
```

Oh, Google is gone!

```sh
sha256sum dnscrypt-proxy.toml
```

```text
117e2fceb936139370f9d7aa47db56a...
```
