### ISSUE TITLE
random panic at blacklist load

### ISSUE THREAD

**Issue by vbauerster** [DNSCrypt/dnscrypt-proxy#1295]
I use `master` 7d0e144 version self compiled for `Linux arm64`. Sometimes boot process exits with panic as it reaches `Loading the set of blocking rules`. At first I though that my blacklist file is corrupted due to bad sd card, but it is not. This happens sometimes when I reboot my raspberry pi 3.
[![Screenshot-2020-04-25-at-15-33-22.png](https://i.postimg.cc/sDk8Lzyf/Screenshot-2020-04-25-at-15-33-22.png)](https://postimg.cc/rK9QdvK7)

Stack trace is pointing to [here](https://github.com/DNSCrypt/dnscrypt-proxy/blob/7d0e1440e1170dc1c878101e72697f3fb84a20cf/dnscrypt-proxy/plugins.go#L265), and it turns out that pointer to slice is nil. [Gist](https://play.golang.org/p/UGYdgAqxZCY) of the problem.

**Comment by welwood08** [comment]
I think this is a race condition but I'm not sure the best way to fix it.

https://github.com/DNSCrypt/dnscrypt-proxy/blob/7d0e1440e1170dc1c878101e72697f3fb84a20cf/dnscrypt-proxy/main.go#L125-L130

In the main startup routine above, the configuration is loaded and then the plugins globals are initialised. The problem is that while loading the configuration, the proxy starts listening for incoming queries. There is currently no guarantee that the plugins globals have been initialised before a query arrives. It's not as simple as initialising before loading the config because the config is used during initialisation.

We should probably have some kind of lock to hold processing of incoming queries until somewhere in `proxy.StartProxy()`.

**Comment by jedisct1** [comment]
`proxy.addDNSListener` should probably just open the sockets instead of also spawning the goroutines accepting datagrams and connections.

So we can start accepting traffic only after everything has been properly initialized.
