### ISSUE TITLE
How to get to wifi hotspot web login page if no resolver is accessable (since I didn't login yet)

### ISSUE THREAD

**Issue by Utini2000** [DNSCrypt/dnscrypt-proxy#1312]
## Subject
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

## Description
I am on Archlinux and can't figure out how to connect/open a web login page of a wifi hotspot (like in the train or on the airport) with dnscrypt running. 

The problem is that dnscrypt.service exits due to not being able to access any resolver including the backup resolver. When trying to open the "log in page" to get access to the wifi, I get the timeout error as if the webpage didn't exist.

Any advice?

Thanks!

**Comment by jedisct1** [comment]
Hotspot web login pages hijack DNS queries in order to be displayed instead of the website you are trying to reach.

And the whole purpose of DNSCrypt is to prevent DNS hijack :)

So, you need to temporarily use insecure DNS, go through the login page, and then you can switch to secure DNS again.

A better option is to use [captive-browser](https://github.com/FiloSottile/captive-browser).
