### ISSUE TITLE
ignored_qtypes.. more than just query_log?

### ISSUE THREAD

**Issue by bcookatpcsd** [DNSCrypt/dnscrypt-proxy#1328]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [X] Other

## Description

I was wondering if there was a way to block query types? People at home are using their own anti virus, and some of the apps have 'website checking', so when they are connected to the VPN these apps do TXT lookups (apparently to verify websites) 

Thank you in advance..

**Comment by jedisct1** [comment]
Indeed, some antivirus are constantly phoning home. Sophos is a notorious example of that, sending queries to them for every single domain you visit (the name is encoded in ROT13).

But instead of blocking a query type, which is likely to break other applications, you can block the domain they use, such as `sophosxl.net`.
