### ISSUE TITLE
update fail on DNS restrict network [windows only]

### ISSUE THREAD

**Issue by lessload** [DNSCrypt/dnscrypt-proxy#1345]
## *Who* is the bug affecting?
Windows user, who don't use their device everyday. 
( `*.md` was outdated )
( but 127.0.0.1 is still the DNS of wif or etc. )
network that restrict DNS

## *What* is affected by this bug?
`dnscrypt-proxy` fail to update `*.md` and stop itself.
( this problem not affected when static `sdns://` )

## *When* does this occur?
When `dnscrypt-proxy` update `*.md` but DNS got restrict. (and `*.md` is too old)

## Expected behavior (i.e. solution)
- `dnscrypt-proxy` should update themself through existing DNSCrypt(server) and start themself again. 
(It should automatic try to connect to a server that is available for updates itself.)
(this not solve the problem when user have only one server and `sdns:\\` got changed)
- `dnscrypt-proxy` should allow user to always set DNS to 127.0.0.1 without problem.

## Other Comments
- If we can't always set DNS to 127.0.0.1 some of DNS traffic will leak. solve this problem will prevent DNS leakage.
- I test it by use old `*.md` select multiple server ( some server `sdns://` got changed but not all ) and fail to update.
- this not big problem but affects some of privacy data.

**Comment by lessload** [comment]
@jedisct1 you can test it by use old `*.md` and start service with 127.0.0.1 as dns of interface (wifi or etc). ( i use 2/5/2020 `*.md` for test ) 

Which point you need me to clarify, just tell me ? this is a real probem in some case.

**Comment by jedisct1** [comment]
This is not specific to this project, but without clear instrtuctions to reproduce an issue, having it fixed by someone who's not familiar with the context and your environment is going to be complicated.

At best, I can try chatbot-like shots in the dark based on keywords.

- Check that you are running the latest version (2.0.42)
- If the network is not immediately available after your system boots, increase `netprobe_timeout`.
- Check that valid addresses are present in `netprobe_address` and `fallback_resolvers`. `netprobe_address` has to be a non-local IP address in order to properly check for connectivity, and `fallback_resolvers` are required to be valid DNS servers. The default values in the example configuration are fine.
- Log files provide useful information about DNS traffic processed by the proxy, but also about what the proxy does, and why something didn't produce an expect result. Check `log_level` and `log_file` in the configuration file, but importantly, look at the output. Without `log_file` being set, log information can be seen in the Windows Event Viewer.
- Try the code present in the current GIt repository.

**Comment by lessload** [comment]
- i'm current on latest version (2.0.42)
- i set `netprobe_timeout = -1`
- all address/fallback valid ping pass
- log when start it
`dnscrypt-proxy 2.0.42`<br/>
`Network connectivity detected`<br/>
`System DNS configuration not usable yet, exceptionally resolving [raw.githubusercontent.com] using fallback resolvers over tcp`<br/>
`Fallback resolvers didn't respond - Trying with the system resolver as a last resort`<br/>
`Unable to resolve [raw.githubusercontent.com] - Make sure that the system resolver works, or that 'fallback_resolver' has been set to a resolver that can be reached`<br/>
`System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolvers over tcp`<br/>
`Fallback resolvers didn't respond - Trying with the system resolver as a last resort`<br/>
`Unable to resolve [download.dnscrypt.info] - Make sure that the system resolver works, or that 'fallback_resolver' has been set to a resolver that can be reached`<br/>
`Unable to retrieve source [relays]: [lookup download.dnscrypt.info: no such host]`<br/>
`lookup download.dnscrypt.info: no such host`

I will check log file and tel you later.

**Comment by lessload** [comment]
Ok now i found more specific case. as test, in my case seem like the company network route all dns to their dns that why resolver was fail but can ping. one way to solve it, update `*.md` through DNSCrypt. it look like feature request now.

- too specific case to found this problem
- need update `*.md` through DNSCrypt to make it work.

I hope `dnscrypt-proxy` may have this feature in a future.

**Comment by jedisct1** [comment]
Some DNS resolvers are accessible on different ports than 53.

For example, Quad9 is accessible on port 9953: `9.9.9.9:9953`.

**Comment by lessload** [comment]
Not work it seem like company allow only HTTP port. 
If we can update through DNSCrypt it will improve user privacy right?
Should have something like dnscrypt fallback/netprobe ?

Finally this is still problem but really specific case. You can skip this. It's up to you.

Thank you.
