### ISSUE TITLE
Allow an option to respond on the interface the request came in on.

### ISSUE THREAD

**Issue by kroy-the-rabbit** [DNSCrypt/dnscrypt-proxy#1362]
## Is your feature request related to a problem?

Right now, it seems to be impossible to use dnscrypt-proxy in an "anycast" situation.  This is where I have an address on a loopback advertised via BGP I want it to respond from, but I also want it to respond from its routed address

;; reply from unexpected source: 10.3.1.253#53, expected 10.53.53.53#53

The main issue is I can only have it respond on a single interface right now without this error.

## Describe the solution you'd like

Something akin to the `interface-automatic` option in Unbound.  It detects what interface the request comes from, and responds on the same interface.

## Alternatives you've considered

Staying with Unbound

## Who will that feature be useful to?

For a DNS server, especially with multiple interfaces, this is almost something that should be default.  

## What are you going to contribute?

I can test however.  I would also be willing to write up documentation regarding the fairly complex DNS setups I've been running for a while with dnscrypt-proxy.

**Comment by welwood08** [comment]
Sounds like golang/go#36421. A potential workaround method is proposed in that issue and we already use the dependency for it, so I guess it's relatively straightforward. I haven't looked closely yet, but I do have a concern about whether IPv6 works the same.

**Comment by jedisct1** [comment]
I made a quick a dirty attempt at this in the `xnet` branch.

**Comment by jedisct1** [comment]
Responses come from the correct interface on macOS, but I've no idea whether that works on Windows and other systems.

**Comment by FiloSottile** [comment]
I think that won't work for IPv6 packets to 0.0.0.0 wildcards. I also have a patch I wrote and never got around to testing. I'll try it on Linux and send it over.

**Comment by aidanharris** [comment]
@FiloSottile It doesn't seem to work for IPv4 packets to 0.0.0.0 either. I just built the xnet branch because I have this problem too and configured `listen_addresses = ["0.0.0.0:53"]` and see the following:

```sh
$ dig google.com @192.168.0.11
;; reply from unexpected source: 192.168.0.12#53, expected 192.168.0.11#53

;; reply from unexpected source: 192.168.0.12#53, expected 192.168.0.11#53

;; reply from unexpected source: 192.168.0.12#53, expected 192.168.0.11#53

```

```sh
$ dig google.com @192.168.0.12

; <<>> DiG 9.16.5 <<>> google.com @192.168.0.12
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13600
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		2359	IN	A	172.217.175.238

;; Query time: 1 msec
;; SERVER: 192.168.0.12#53(192.168.0.12)
;; WHEN: Thu Aug 06 12:39:19 -00 2020
;; MSG SIZE  rcvd: 55
```

I can add both addresses to the listen_addresses like this: `listen_addresses = ["192.168.0.11:53", "192.168.0.12:53"]` but I don't want to do that because if one of the interfaces is down dnscrypt-proxy refuses to start.

**Comment by jedisct1** [comment]
>  if one of the interfaces is down dnscrypt-proxy refuses to start.

Enabling `IP_FREEBIND` should be easy enough.

**Comment by petercooperjr** [comment]
I've managed to work around this for now by just specifying each interface separately instead of just something generic like `'[::]:53'`, but I'm similarly worried about having troubles if on reboot the IP address haven't been bound yet when dnscrypt-proxy tries to start. Really I just want to be able to specify the interfaces themselves rather than the IPs on them like dnsmasq's `interface=` command, since I can't guarantee that my ISP won't try to change my IPv6 prefix on me (though they haven't actually done so yet). I'm experimenting with replacing dnsmasq entirely with dnscrypt-proxy on my Ubiquiti EdgeRouter ER-X if I can, but maybe best practice is still to have something like dnsmasq sit in front of dnscrypt-proxy to handle the actual requests?
