### ISSUE TITLE
DNSCrypt: 'd0wn-*-ns[1-2]' Servers. Question.

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1416]
Hello.

I have just one, short question about Servers provided by Mr Martin 'd0wn' Albus. Does anyone have any informations about privacy policy (logging, non-logging etc.), DNSSEC support (however, it can be easily checked) and so on?

I searched network for those informations, but probably not so hard. So, what is the status of a mentioned Servers? 

It would be ideally, if Mr Albus could provide such informations itself (then, for example, `public-resolvers.md` file could be also updated).

Thanks, best regards.

**Comment by jedisct1** [comment]
This information is printed for all resolvers here: https://dnscrypt.info/public-servers and you can also simply click the name of a resolver to get details.

**Comment by ghost** [comment]
Hello **jedisct1**.

Yes, I know `dnscrypt.info` website. However, there are exactly the same informations about Mr Martin 'd0wn' Albus servers as in `public-resolvers.md` file - no logging policy, no `DNSSEC` support etc.

Thanks, best regards.

**Comment by welwood08** [comment]
It's not clear what response will be satisfactory when the information you ask for _is_ already present in both the website and `public-resolvers.md`.

On the website, the lack of any icon in the "Logging" column means "No logging" and a blue padlock icon in the "DNSSEC" column means "DNSSEC supported". If you clicked on a server name as previously advised, you would also see "**DNSSEC** 	true" and "**No logs** 	true".

In `public-resolvers.md` it may not be in a human-readable form, but that shouldn't matter if you already know about the website since there's also a tool to decode DNS stamps there. Alternatively, `dnscrypt-proxy -list -json` will output similar information relevant to your local configuration.

If your objection is that the descriptive text doesn't mention the machine-readable flags, please feel free to change it with a pull request in [the proper place](https://github.com/DNSCrypt/dnscrypt-resolvers) (although I'm sure there are plenty of other servers in the list whose descriptions are similarly lacking).

**Comment by ghost** [comment]
Hello  **welwood08**.

Thank You for an answer. I didn't know that: "_On the website, the lack of any icon in the "Logging" column means "No logging" and a blue padlock icon in the "DNSSEC" column means "DNSSEC supported"._" (However, I don't see a blue padlock, but it's an issue on my side, probably).

"_If your objection is_" - no, I haven't any objections.

Best regards.
