### ISSUE TITLE
How can I count how many people have used my server?

### ISSUE THREAD

**Issue by mukberty** [DNSCrypt/dnscrypt-proxy#1418]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] ***Other***

## Description
I shared my server with a few friends. Is it possible for me to count how many people have used it(even if they aren't active at the moment)?

Thanks.

**Comment by jedisct1** [comment]
You can run tcpdump and count the number of unique IP addresses having sent queries.

It won't be very accurate, since people's IP addresses change, and people can also use relays.

Unfortunately, there are no ways to accurately measure how many users a DNS server has. The way to do it on the web is to use cookies and other intrusive methods, but fortunately, this is not possible with DNS.
