### ISSUE TITLE
How to cleanly override specific settings in the config file?

### ISSUE THREAD

**Issue by infokiller** [DNSCrypt/dnscrypt-proxy#1419]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [x] Other

## Description

Thanks for this great project!
I have a small number of settings that I override in my dnscrypt-proxy.toml config file. I used to do this directly in the file shipped by my Linux package manager, but this requires me to merge changes whenever this file is updated by the package manager.
Ideally, I'd be able to use the file shipped by the package manager and only override a few settings. However, AFAIK, TOML doesn't support overriding values of keys that were already defined, so I can't just append the overrides.
Is there an existing way to do what I want, without dealing with merges on every package upgrade (that also updates the config file)?
If there isn't, does it make sense to have dnscrypt-proxy support multiple config files, where the latter ones override the earlier ones if they set the same keys?
For example: `dnscrypt-proxy -config distro_shipped_config.toml -config my_config.toml`

Thanks!

**Comment by alisonatwork** [comment]
It would be possible to parse multiple config files with the second one overriding the first one, but it could make the error reporting a bit more confusing, because it will no longer be clear which "layer" of the config caused an error on startup.

Is there one config in particular that you want to override? If it is a generally useful one to override, it might be worth adding a command line argument or environment variable specifically for that one.

**Comment by infokiller** [comment]
No particular config, it's a few keys spread across multiple places.

**Comment by jedisct1** [comment]
Error reporting would be confusing, but "merging" different configuration files would also require inventing a new version of TOML.

To understand why, what should the merging process do if there are two `[sources]` section?

Should the final set be the union of both sets? Or should every parsed file clear the set and reduce it to its own definition? 
If the former, how would one overwrite (instead of add to) a property?

TOML, and more generally structured configuration formats, don't really play well with merging.

Having defaults that differ from the standard defaults would also make troubleshooting cumbersome. When a user has a issue and posts their configuration file, there won't be any way to tell what the actual configuration is. Two identical configurations would behave differently on different systems (or even the same system, but different distributions or versions).

However, since the very first version of the project, we've been trying really hard to avoid breaking backward compatibility. So that you can keep your existing configuration file, even after an update.
