### ISSUE TITLE
dnscrypt-proxy & Tor Browser: How To Configure?

### ISSUE THREAD

**Issue by FrigidReward** [DNSCrypt/dnscrypt-proxy#1420]
How do I use Tor when I also have dnscrypt-proxy installed? Is there some way I can configure dnscrypt-proxy to not use encrypted DNS when using Tor?
Reason:
>However you shouldn't use encrypted DNS with Tor. This would direct all of your DNS requests through a single circuit, and >would allow the encrypted DNS provider to deanonymize you.

Link: https://www.privacytools.io/providers/vpn/#info

**Comment by syphyr** [comment]
As long as you force dnscrypt-proxy to also use Tor when requesting DNS, it should be ok to still have encrypted DNS requests:
force_tcp = true
proxy = 'socks5://127.0.0.1:9050'

Then, in your web browser, set a socks4 proxy with Tor so it uses external DNS on your local host pointing to dnscrypt-proxy.   This way, DNS and web browser are both going through tor.

**Comment by welwood08** [comment]
Going by your issue title, it seems you are confusing the Tor Browser package with the Tor service. If you really are just trying to use the Tor Browser, it should safely route its own DNS queries through its own instance of Tor out of the box.

The advice you've quoted from PrivacyTools, and that given by @syphyr, applies when you have set up your own instance of Tor and are manually configuring other software to proxy through it. If this is what you are doing then you probably want a local firewall to alert you when an application you thought was safely proxying to Tor made a non-Tor request, DNS or otherwise, so you can fix it yourself.
