### ISSUE TITLE
Question: Verify Anonymized DNS is working / Clear cache

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1427]
I have questions about the DNSCrypt or Anonymized DNSCrypt protocols

1) How can i verify Anonymized DNS is working on my Ubuntu server and all queries are going only via Anonymized DNS? What are the commands?
I am using it with Pihole+Softether VPN combination vla 127.0.0.1:5300

If anyone can share with me their sample configurations, that would be great.

2) How can i purge/remove dnscrypt cache on my Ubuntu server?

Thanks
Onder

**Comment by jedisct1** [comment]
1) It's printed when the server starts:

    [2020-07-28 14:39:38] [NOTICE] Anonymized DNS: routing everything via [anon-kama]

2) Restart the server.

**Comment by ghost** [comment]
Which command can i use to see that?

2. How can i purge/remove dnscrypt cache on my Ubuntu server?

**Comment by welwood08** [comment]
The cache is only kept in memory, it will be empty every time you start `dnscrypt-proxy`.

**Comment by ghost** [comment]
Hello.

Sorry for interrupting, but I also would like to ask a question about cache. So, can ` systemd-resolve --statistics` command be used to check cache value used by - for example - DNSCrypt? I'm asking, because mentioned command shows e.g. current cache size (and also cache hits, misses) etc.

Is `systemd-resolve(1)` command sufficient to gather an information about cache status? In addition, the `--statistics` option show resolver statistics, including information about the `DNSSEC` validations (succesful and failed etc.) 

What do you think?

_EDIT_: **ndr48291** `systemd-resolve(1)` command offers `--flush-caches` option to flush the DNS cache (available - if I remember correctly - in Ubuntu 18.04 LTS). By the way; restarting `systemd-resolve` can also flush DNS caches. Maybe, it will help You somehow.

Thanks, best regards.

**Comment by welwood08** [comment]
In terms of DNS basics, there can be a cache at every hop in the DNS request chain. If you use `systemd-resolve` and it tells you about a cache, it is safe to assume it's telling you about its own cache and no others.

**Comment by ghost** [comment]
Hello **welwood08**.

Thank You. Okay, and what about DNSCrypt restart (vide - for example - `systemctl restart` command)? Can it flush the cache? I'm asking, because You've written "_The cache is only kept in memory, it will be empty every time you **start dnscrypt-proxy**._"

Sorry for off-topic. That's my last question.

Thanks.

**Comment by welwood08** [comment]
Yes, as usual for any service manager, when you ask to restart any service they will at some point stop the old instance of the service if it's running and start a new instance (depending on the servcice, not necessarily in that order). This is the expected meaning of the word "restart" in this context, and is probably documented as such in the SystemD manual. You can always check for yourself if this actually happens by using a process manager to observe the service's process ID changing.

In case it wasn't obvious, because the cache is only in memory it will cease to exist as soon as `dnscrypt-proxy` is stopped (no matter how you achieve this state) and the effect of that is for it to be empty when you start it. There is no other way to clear this cache because there hasn't been an urgent need to implement such a feature (startup is usually fast enough).
