### ISSUE TITLE
ipset DNS queries

### ISSUE THREAD

**Issue by dim-geo** [DNSCrypt/dnscrypt-proxy#1430]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
Allow dns query results to become part of an ipset.
## Alternatives you've considered
Parsing query logs and add them manually to ipset
## Who will that feature be useful to?
Firewalls/QoS based on FQDN not on ips
## What have you done already?
Separate parser/script of dns query logs that add manually to ipset the resolving IPs
## What are you going to contribute?
I can test and document if needed.
## Additional context
dnsmasq offers this feature. dnscrypt-proxy is a proxy, but when local DoH is used you cannot ipset queries via ipset-dns.
[QoS via ipset ](https://github.com/hisham2630/Ultimate-SQM-settings-Layer_cake-DSCP-marks-New-Script/blob/master/dnsmasq.conf-ipv4../dnsmasq.conf)

**Comment by jedisct1** [comment]
Looks like `ipset` is a ([legacy?](https://wiki.nftables.org/wiki-nftables/index.php/Moving_from_ipset_to_nftables)) command that only exists on Linux.

`dnscrypt-proxy` tries to stay system-agnostic, so that it works the same way on all platforms.

Since what you are trying to achieve can already be done (and you already did it), it doesn't seem to be necessary to reimplement this in the proxy itself. `ipset` being an external command, it also seems safer to run it in its own security context. An external script parsing the logs (possibly just reading them from a named pipe) sounds like the way to go.
