### ISSUE TITLE
"Too many incoming connections (max=250)" when internet down

### ISSUE THREAD

**Issue by stephen-d-hill** [DNSCrypt/dnscrypt-proxy#1439]
## *Who* is the bug affecting?
Affects all DNS clients
## *What* is affected by this bug?
DNS requests stop working and never recovers
## *When* does this occur?
The problem occurs when the street has a powercut, but I have a UPS which keeps my server and modem working....BUT the link to the internet goes down.
## *Where* does it happen?
It happens on my Ubuntu 18.04 server, which is my LANs DNS server
## *How* do we replicate the issue?
To replicate....I assume what's happening is that all the clients on my LAN start sending DNS requests that don't get serviced, or something like that
## Expected behavior (i.e. solution)
For dnscrypt-proxy service to recover once the internet link comes back, i.e. when the power comes back on. To fix it I have to restart dnscrypt-proxy.

## 
Log attached
[dnscrypt_proxy_systemd_log.txt](https://github.com/DNSCrypt/dnscrypt-proxy/files/5030580/dnscrypt_proxy_systemd_log.txt)

**Comment by jedisct1** [comment]
Don't use systemd sockets. Use normal sockets.

**Comment by stephen-d-hill** [comment]
Easier said than done. 
I tried the following:
* sudo systemctl stop dnscrypt-proxy
* sudo systemctl stop dnsmasq.service
* Checked socket 3353 was free using netstat
* Edit /etc/dnscrypt-proxy/dnscrypt-proxy.toml to add listen_addresses = [127.0.2.1:3353]
* Edit /etc/dnsmasq.d/dnscrypt-proxy to change port to 3353
* sudo systemctl start dnscrypt-proxy.service
`                                                                                                        
Aug 06 09:04:18 xxx.xxx.xxx systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a 
Aug 06 09:04:18 xxx.xxx.xxx systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
`
                                                                        
I've no idea what the problem is....is there any log I can look at?

**Comment by stephen-d-hill** [comment]
Oops, I forgot the quotes.
Should have been listen_addresses = ['127.0.2.1:3353']

**Comment by jedisct1** [comment]
Start the server interactively (just with `dnscrypt-proxy`) before installing it as a service. If there is anything wrong with the configuration file, it will tell you immediately.

Once the maximum number of connection is reached, new connections are refused, and old connections eventually time out. `dnscrypt-proxy` will not stop accepting connections (or whatever "DNS stops working" means). 

But maybe something is sending old queries that have been piling up, even if there are no chances that clients are still waiting for them.

I suspect that it may happen if the sockets are handled by systemd.

Otherwise, it may also be a configuration issue, where there are loops in your network configuration. Looking at the query logs may help a lot to understand this.
