### ISSUE TITLE
Use system line ending & Windows CRLF for examples

### ISSUE THREAD

**Issue by u1735067** [DNSCrypt/dnscrypt-proxy#146]
Under Windows, unix line ending is not usable with `notepad` for example, could you use the default system line ending ?
This applies to the output files (logs), but also to the example files provided in the release file.
(Btw, don't you want to provide the utils/ in the release file ?)

**Comment by jedisct1** [comment]
I'm not sure that it currently works with Windows-style end of lines, but I'm pretty sure that this will never be tested :)

Do people really still use Notepad? Not even Wordpad? I must confess that this is the very first time I read such a request.

**Comment by u1735067** [comment]
> I'm not sure that it currently works with Windows-style end of lines, but I'm pretty sure that this will never be tested :)

I don't have issues with toml & blacklist with CRLF ending so far (it seems at least).

> Do people really still use Notepad? Not even Wordpad? I must confess that this is the very first time I read such a request.

I don't think you want to use Wordpad. Notepad is certainly not the best editor, but it's light & the default program for txt files (& maybe log unless I changed that).

**Comment by Tallefer** [comment]
Yep, my bad — I completely forgot about this issue (probably because I am still on v1, waiting for some issues being resolved, before I could freely use it to install everywhere), should've made a report before release. 
I don't use default windows notepad anymore personally, but let's not forget — for any fresh installed (or just some average Joe's) system working with configs could become a real problem. And in most cases installing security-related software (such as DNScrypt) should be a first priority, before anything fancy (like any modern text editor) could be downloaded and used.
