### ISSUE TITLE
Help: details about implementation of XChacha20-Poly1305 in PHP

### ISSUE THREAD

**Issue by noglitchyo** [DNSCrypt/dnscrypt-proxy#1461]
## Subject

* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

## Description

Hello,

I am working on an implementation of the DNSCrypt protocol in PHP. 
I succeed to make a first implementation with the ES version 1 (using XSalsa20) but I have a bit of a struggle to implement the ES version 2 using XChacha20-Poly1305.

From what I understood, the implementation of XChacha20 looks pretty similar and differs only on:
- the creation of a shared key with `crypto_scalarmult` from the resolver PK and the client secret key
- the creation of the cipher with `crypto_secretbox_xchacha20poly1305`

And other requirements like the nonce or the padding of the client query should be left intact (i.e: same as in XSalsa20).

Is that first statement correct or am I already missing something? I have only really basic knowledge in cryptography, so there is great chances that I am missing something there.

In my current not working implementation of XChacha20 which can be found [here](https://github.com/noglitchyo/dealdoh/blob/33d0135d421bc9f13eb8e5397789bb3bc83948e4/src/Service/DnsCrypt/XChacha20AuthenticatedEncryption.php#L64), the client successfuly sent the DNSCrypt query with the encrypted message but failed to receive a response from the upstream resolver.
There I assume that it is due to a faulty encryption, since it works well when I use ES1 with that same resolver.

Other information which should be of interest, I use the [paragonie/sodium_compat](https://github.com/paragonie/sodium_compat ) library, do you see any incompatibilities or misuses of the library?

Any help would be greatly appreciated. 

Thank you very much.

**Comment by jedisct1** [comment]
Hi!

Key pair creation is done exactly the same way. In fact, the same key pair can be used by both algorithms.

As for encryption, the only difference is that you have to call `crypto_secretbox_xchacha20poly1305()` instead of `crypto_secretbox()`. That's it :) Parameters have the same sizes and format.

But if a resolver supports both, you will get two certificates, with a different server magic (which is how the server will know if the client is using Salsa or ChaCha). So, make sure that you are sending queries with the right magic for the protocol version.

**Comment by jedisct1** [comment]
Ah, I see what's wrong with your code.

`sodium_compat` implements `crypto_box` but not `crypto_box_xchachapoly1305` so you had to reimplement it.

```php
$this->sharedKey = ParagonIE_Sodium_Compat::crypto_scalarmult(
    $this->clientSecretKey,
    $this->resolverPublicKey
);
```

This has to be changed to:

```php
use ParagonIE_Sodium_Core_HChaCha20;
```
...
```php
$shared_point = ParagonIE_Sodium_Compat::crypto_scalarmult(
    $this->clientSecretKey,
    $this->resolverPublicKey
);
$this->sharedKey = ParagonIE_Sodium_Core_HChaCha20::hChaCha20(str_repeat("\0", 16), $shared_point);
```

`crypto_scalarmult()` doesn't return a key. It's the coordinate of a point, that has to be hashed in order to get a key.
With Salsa20, the hash function is `ParagonIE_Sodium_Core_HSalsa20::hsalsa20()` and with ChaCha20 the hash function is `ParagonIE_Sodium_Core_HChaCha20::hChaCha20()`.

**Comment by noglitchyo** [comment]
Thanks @jedisct1, it works! 

I really need to step up my cryptography basics ;)
