### ISSUE TITLE
Unable to connect to Github using Anonymized Dnscrypt-Proxy "Connection not secure"

### ISSUE THREAD

**Issue by Bushwickz** [DNSCrypt/dnscrypt-proxy#1472]
![Untitled](https://user-images.githubusercontent.com/65140377/92721537-cc163a80-f355-11ea-95d2-cb0819f2b013.jpg)

![Untitled2](https://user-images.githubusercontent.com/65140377/92721545-cfa9c180-f355-11ea-922e-57fe5230ee64.jpg)

![Untitled3](https://user-images.githubusercontent.com/65140377/92721881-4b0b7300-f356-11ea-8bec-8a2904781e56.jpg)

dnscrypt-proxy catalina

**Comment by welwood08** [comment]
This doesn't look like an error that would be caused by `dnscrypt-proxy`. When Firefox encounters a problem during DNS resolution, I would expect the error to say "Hmm. We’re having trouble finding that site.". This looks like Firefox has finished DNS resolution successfully and is trying to connect to the website, which does not involve `dnscrypt-proxy` and could be caused by any number of other factors on the network path between you and GitHub.

Since the limited information you've given doesn't appear to point to `dnscrypt-proxy` I'll close the issue and suggest you try a traceroute and check any firewall you might have. If you disagree with my conclusion, please feel free to provide some more information like a query log or something that shows the DNS result is at fault and we can investigate further.

**Comment by Bushwickz** [comment]
Thanks.

**Comment by jedisct1** [comment]
`blahdns` is a filtering server. They block ads and trackers, but like any blocking service, it can have false positives.

So, another explanation may be that they are (were?) blocking GitHub.

What does `dnscrypt-proxy -resolve github.com` print?

**Comment by Bushwickz** [comment]
> `blahdns` is a filtering server. They block ads and trackers, but like any blocking service, it can have false positives.
> 
> So, another explanation may be that they are (were?) blocking GitHub.
> 
> What does `dnscrypt-proxy -resolve github.com` print?


root@MaxPro dnscrypt-proxy-macos-2.0.44 # ./dnscrypt-proxy -resolve github.com 
Resolving [github.com]

Domain exists:  yes, 8 name servers found
Canonical name: github.com.
IP addresses:   fe80::21b:aabb:8c52:7903
TXT records:    MS=ms44452932 MS=ms58704441 MS=6BF03E6AF5CB689E315FB6199603BABF2C88D805 docusign=087098e3-3d46-47b7-9b4e-8a23028154cd v=spf1 ip4:192.30.252.0/22 ip4:208.74.204.0/22 ip4:46.19.168.0/23 include:_spf.google.com include:esp.github.com include:_spf.createsend.com include:servers.mcsv.net ~all
Resolver IP:    159.69.198.101

root@MaxPro dnscrypt-proxy-macos-2.0.44 #

**Comment by jedisct1** [comment]
> `IP addresses: fe80::21b:aabb:8c52:7903`

That doesn't make any sense.

This is a link-local address. It cannot be reached over the internet. 

I tried with `doh-de-blahdns` which I assume is the DNS you are using (why is it called `blahdns-de-doh` in your screenshot?) and got the proper GitHub address.

Do you get the same IPv6 address when using a different resolver?

**Comment by jedisct1** [comment]
Noticed that your screenshot says both `blahdns-de-doh` and DNSCrypt. 

Alright. So what you called `blahdns-de-doh` may be what's called `dnscrypt-de-blahdns-ipv4` everywhere else after all.

Trying that one, I noticed that it indeed returns `fe80::21b:aabb:<ip>` as an IPv6 address for anything that has an IPv4 address and not an IPv6 one.

Looks like that resolver enabled DNS64, a mechanism to access servers everything over IPv6. Some ISPs may enforce this, but for a public resolver, it is probably a configuration error.
