### ISSUE TITLE
Set DNS resolvers ping range option for load-balancing

### ISSUE THREAD

**Issue by alessandro893** [DNSCrypt/dnscrypt-proxy#1476]
Example: 
When ping range option is set to "100" - dnscrypt-proxy chooses resolvers with ping lower than "100" (in range 0-100).

Thanks.

**Comment by welwood08** [comment]
Ping is not a fixed value - every query's response time is measured and used to update an [exponentially weighted moving average](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average). A resolver's previous response time is already taken into account when choosing which resolver to use, but it could still exceed any user-specified ping range and by that time it's already too late to pick a different resolver unless you can travel back in time.

If a resolver took too long to respond 1 time and was then ignored forever, you would end up with no resolvers to choose from after a while. If there was a temporary problem with your internet that delayed your connections to every resolver, you would end up with no resolvers to choose from very quickly.

There are already several load-balancing strategies, the default (`lb_strategy = 'p2'`) picks randomly from the fastest 2 resolvers based on previous response times. Hopefully I've clarified why it's not as simple as setting a hard ping limit but if I've misinterpreted your suggestion, please elaborate.

**Comment by jedisct1** [comment]
Indeed, if you enable query logging, that includes the time taken to answer each query, you will notice a significant variance, even for a given server. This is due to the distributed nature of DNS.

A subset of the servers can be chosen according to a single query at startup time and some threshold. But then you would get a different set of servers every time the proxy is started according to your network conditions and what else you were doing at that exact time. In the worst case, you may end up with only 1 or, as pointed out by Will, even no usable servers at all.
