### ISSUE TITLE
Automatically use next server when get wrong replies like `127.0.0.1` or `0.0.0.0`

### ISSUE THREAD

**Issue by cindymao56** [DNSCrypt/dnscrypt-proxy#1493]
## Is your feature request related to a problem?

Sometimes a DOH server answers `127.0.0.1` or `0.0.0.0` to my query (I'm query an ordinary domain like `www.google.com`). That's obviously a wrong answer.

## Describe the solution you'd like

dnscrypt-proxy automatically send query to next DOH server when get such wrong answer

## Alternatives you've considered

Added `127.*` and `0.*` to ip blacklist ( why it doesn't support mask format like `172.16.0.0/12` ?)
But that doesn't really solve. Browser or other DNS forwarder (I'm chaining DNS softwares) have cache. I have to reset them every time.

**Comment by jedisct1** [comment]
`127.0.0.1` or `0.0.0.0` are not "wrong" answers. They are totally valid responses that can be assigned to a hostname.
These are also commonly used for spam filtering.

If you get such a response for `google.com` and are not intentionally using a lying resolver, the best thing to do would be report what resolver is doing this. So that the "no filter" attribute can be removed accordingly.
