### ISSUE TITLE
Need correct iptables of dnscrypt-proxy (Linux)

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1505]
Hi!

Can you please post the correct iptables rules of dnscrypt-proxy/dns here for standard use.

dnscrypt-proxy runs on 127.0.0.1:5300.

Please all, INPUT/OUTPUT rules - tcp/udp.

I don't know the correct rules for dns port 53 and dnscrypt-proxy port.

Must it be a INPUT rule/OUTPUT rule or must I forward dns port 53 to 5300?

So, please post it here.

Thanks!

**Comment by jedisct1** [comment]
Wouldn't it be easier to simply listen to port 53 as it does by default ?

That way no firewall rules would be needed.

**Comment by ghost** [comment]
I thought I still had to set ipbtables for dnscrypt-proxy and dns port 53.

Do I have to open port 5300 too?
Or only port 53 for dns?

If yes,
INPUT or OUTPUT rule for that to connect to dnscrypt-proxy servers?

You say I do not need it, but I would like to have it. :)

I set:

> # tcp
> /sbin/iptables -A INPUT -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport 53 -j ACCEPT
> /sbin/iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 53 -j ACCEPT
> 
> # udp
> /sbin/iptables -A INPUT -m state --state NEW,ESTABLISHED -m udp -p udp --dport 53 -j ACCEPT
> /sbin/iptables -A INPUT -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT

correct rule?

or must I set it to OUTPUT rule?

Also ACCEPT port 5300 or only 53?

**Comment by jedisct1** [comment]
`127.0.0.1` is your local host. Local connections from the host to itself, that don't go over the network, don't need firewall rules, unless you went really extreme. You probably have a rule allowing everything on the local interfaces anyway.

`dnscrypt-proxy` will send packets to the resolvers you chose, but outgoing connections are probably already allowed, or else that host could barely access the internet.

Unless you put a public IP address in `listen_addresses` instead of the default `127.0.0.1` or a local IP, you don't need firewall rules.

**Comment by ghost** [comment]
ok
