### ISSUE TITLE
SAD DNS vulnerability

### ISSUE THREAD

**Issue by Dr-Flay** [DNSCrypt/dnscrypt-proxy#1508]
I just tested a few resolvers with the SAD DNS check and all failed.
https://www.cs.ucr.edu/~zhiyunq/SADDNS.html
https://www.bleepingcomputer.com/news/security/dns-cache-poisoning-attacks-return-due-to-linux-weakness/

Is it possible to mitigate within DNSCrypt itself ?

**Comment by jedisct1** [comment]
None of my servers are vulnerable :) [edgedns](https://github.com/jedisct1/edgedns) has been protecting against this since the initial release as well.

DNSCrypt sits between recursive servers and clients. SADDNS doesn't apply here (nor any other DNS vulnerabilities, including fragmentation, amplification, etc).

SADDNS is about packets exchanged between recursive servers and authoritative servers, where DNSCrypt cannot be used.

The Linux kernel will be updated to deal with that issue, so resolvers will eventually be protected no matter what software they use. 

That being said, even if there's a web page for that bug and a logo, it's not the end of the world. Blind DNS cache poisoning attacks are very hard to conduct. Active attacks (from an ISP the packets are going through) are far more realistic, and don't need such a bug to work effortlessly.

**Comment by Dr-Flay** [comment]
Thanks for the clarification.
I did note the test points out it is not 100% reliable.
I assume because it only checks for certain factors which in the case of DNSCrypt are not an issue anyway.
