### ISSUE TITLE
[QUESTION] Can I apply time-based rules for DNS requests originating from predefined IPs?

### ISSUE THREAD

**Issue by atmosx** [DNSCrypt/dnscrypt-proxy#1526]
What I would like to do is block access to `twitter.com` for a group of devices, while allowing everyone else to access `twitter.com`.

Is it possible to apply time-based access restrictions to specific IP addresses? 

Thank you!

**Comment by scubasunny** [comment]
I would even vote for such a feature, deny access to certain websites for my son :-), all others can still use these.

**Comment by atmosx** [comment]
> I would even vote for such a feature, deny access to certain websites for my son :-), all others can still use these.

I'll take a look at the code over the weekend, see how could be accomplished. Pointers welcome!

**Comment by ianbashford** [comment]
I use a simple version of this at home for my kids -- I just run two dns servers - their's has time restrictions, and the adults one doesn't.  Its really simple to manage...

**Comment by jedisct1** [comment]
Hi!

Instead of complicating the syntax of time-based rules, I would recommend to solve this by running two instances, listening to different IP addresses.

By doing so, these instances:
- can have different (time-restricted and permanent) filtering rules
- can use different resolvers (filtering vs non-filtering)
- can have different cloaking rules (especially useful for enabling the "safe mode" on YouTube and Google)
- can have dedicated log files.

**Comment by ianbashford** [comment]
+1   That's exactly what I do, for all of those reasons :-)

**Comment by scubasunny** [comment]
Yes, fully ok, but as I run the package natively on my synology I would need somehow to clone this or adopt the start scripts in a way that two instances are started on different virtual IP.
And that's not straight forward on the syno!
But I can understand that you want to keep the code small and easy to maintain

**Comment by atmosx** [comment]
Using `dnsmasq` is possible to setup DNS servers per client, so I can live with that!
