### ISSUE TITLE
[FreeBSD] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tannx** [DNSCrypt/dnscrypt-proxy#154]
![screenshot_2018-02-19_18-17-25](https://user-images.githubusercontent.com/5285684/36400830-600e5168-15a1-11e8-88b4-415e00886f1d.png)

just install it on my freeBSD first time.

**Comment by jedisct1** [comment]
`-service install` only works on macOS, Linux and Windows.

Maybe there should be a more graceful way to error out, though :)

This is where you should report it: https://github.com/kardianos/service

(but no screenshot except for UI issues, please. They are impossible to read on mobile, impossible to copy/paste, impossible to look for so that people with the same issue could find it, and generally just annoying)

**Comment by jedisct1** [comment]
547e444afda34536a2520d7d770149efe266f2ee should now display a proper error message.

But feel free to contribute support for FreeBSD to `kardianos/service`!

**Comment by tannx** [comment]
I see, thanks.
