### ISSUE TITLE
Wildcard on anonymized DNS

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1553]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [x] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ ] Other

I have a question regarding anonymized DNS.

I don't use "server_names" because I'm using the automatic selection mode. As such, I'd think that using anonymized DNS with all servers would be a good thing.
However, in the example file says that using a wildcard on "routes -> server_name" is not recommended. Why is that?

**Comment by jedisct1** [comment]
Isn't this explained in the [documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS)?

**Comment by guillaumerenault** [comment]
" Only use this if you have server_names defined, with a small set of servers that don't overlap with relays." from the [documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS#configuring-anoymized-dns-in-dnscrypt-proxy).
I'm guessing this is due to servers acting both as a dnscryt-server and a relay? I'm also curious as to why this is not recommended, what's the problem (if not technical) with defining a route of relay(s) that is applied to all the available servers?

**Comment by ghost** [comment]
@jedisct1  @guillaumerenault 

So the warning is there just to make sure the servers don't overlap with the relays then.
I had already read the docs, I just thought the warning would be there for something less conspicuous. :)

And Frank, thanks for the great DNSCrypt!
