### ISSUE TITLE
How do we do auto-updates of DNSCrypt in FreeBSD? 

### ISSUE THREAD

**Issue by Jsalas424** [DNSCrypt/dnscrypt-proxy#1560]
## Subject

* [ ] I'd like to contribute to the project (code, documentation, website, advocacy, integration, ...)
* [ ] I want to run my own DNSCrypt and/or DoH server
* [ ] I'd like to have my existing server added to a public list of encrypted DNS servers
* [ ] I'd like to announce a new application/website/article related to the project
* [ ] I have questions about the DNSCrypt or Anonymized DNSCrypt protocols
* [ ] I am a MacOS developer and I'd like to contribute a GUI for dnscrypt-proxy
* [ ] I am an Android developer and I'd like to contribute an Android app
* [ ] I am a technical writer and I'd like to help write an IETF Internet Draft for the DNSCrypt protocol
* [ x] Other

## Description

Are there instructions anywhere for auto-updating a FreeBSD (pfsense) system similar to the Ubuntu ones? 

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates

**Comment by welwood08** [comment]
If you installed `dnscrypt-proxy` using [the instructions on the wiki for pfsense](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation-pfsense) then I don't think the Linux update script you linked will be compatible since it expects the service to be installed in a different way.

If you're not comfortable making the necessary changes to that update script and assuming pfsense is similar to vanilla FreeBSD then I'd recommend a simpler alternative: install with `pkg install dnscrypt-proxy2` (if you want to re-use your existing configuration, it should be in `/etc/dnscrypt-proxy/`) and then do updates with `pkg update` as a cronjob.
