### ISSUE TITLE
DoH clients not show in query.log

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-proxy#1589]
Why IP address of DoH client hidden? How change it?

`[2021-01-21 15:17:46]   -       l9bjkkhaycw6f8f4.soundcloud.com A       PASS    95ms    dnscrypt.eu-nl` <--- DoH client
`[2021-01-21 15:17:54]   192.168.0.67     github.com      A       PASS    62ms    meganerd` <---simple client

**Comment by jedisct1** [comment]
Logging the IP address has only been implemented for regular DNS queries, mainly because local DoH connections are assumed to always come from the local machine.

> How change it?

In all the places where the IP is logged, I think the client protocol is checked for being `udp` or else is assumed to be `tcp`.  The case of the `local_doh` protocol needs to be added.

**Comment by black-cerberon** [comment]
In older versions that was work.

**Comment by jedisct1** [comment]
The `local_doh` case doesn't seem to be handled anywhere, so if it worked in older versions, that was probably by accident.

**Comment by jedisct1** [comment]
The IP was actually present in all log files, except the query log.

This has been fixed, thanks!
