### ISSUE TITLE
❓ Question How this look for a toml?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#1639]
How this look for a toml?
trying to optimize for speed performance privacy and uptime, uptime is critical first priority.

`server_names = ["quad9-doh-ip4-filter-pri"]
listen_addresses = ['127.11.11.11:53', '[0:0:0:0:0:0:0:1]:53']
max_clients = 1000000
ipv4_servers = true
ipv6_servers = false
disabled_server_names = []
dnscrypt_servers = false
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
daemonize = false
force_tcp = false
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
tls_cipher_suite = [4866]
offline_mode = false
timeout = 999
keepalive = 30
lb_estimator = false
netprobe_timeout = 60
netprobe_address = "9.9.9.9:53"
log_level = 0
use_syslog = false
cert_refresh_delay = 1
fallback_resolvers = ['9.9.9.9:53', '149.112.112.112:53']
ignore_system_dns = true
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 600
cache = true
cache_size = 1000000
cache_min_ttl = 30
cache_max_ttl = 604800
cache_neg_min_ttl = 30
cache_neg_max_ttl = 604800

[query_log]
format = "ltsv"

[nx_log]
format = "ltsv"

[blacklist]

[ip_blacklist]

[anonymized_dns]
skip_incompatible = false

[broken_implementations]
fragments_blocked = []

[sources]

[sources.public-resolvers]
urls = ["https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md", "https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md"]
minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
cache_file = "public-resolvers.md"
refresh_delay = 72
prefix = ""

[sources.relays]
urls = ["https://github.com/DNSCrypt/dnscrypt-resolvers/raw/master/v2/relays.md", "https://download.dnscrypt.info/resolvers-list/v2/relays.md"]
minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
cache_file = "relays.md"
refresh_delay = 72
prefix = ""`

**Comment by jedisct1** [comment]
> How this look for a toml?

Difficult to read :)

```toml
max_clients = 1000000
```

If you ever get 1 million queries simultaneously waiting for a response, there's something really wrong. I doubt your system would be able to handle that anyway.

```toml
[broken_implementations]
fragments_blocked = []
```

Don't do that. Disabling workarounds for server bugs is not a good way to improve reliability.

```toml
cert_refresh_delay = 1
```

Yikes.

I'd recommend starting over from the default configuration and only changing the bare minimum (and not changing parameters if you don't understand what they do).

Just changing `server_names` and `listen_addresses` is going to give the best results in almost all cases.
If this is not the case, we should change the default settings instead :)

**Comment by ghost** [comment]
does quad 9 still need padding? i tried with padding but it lagged bad so i deleted it
cert refresh 1 minute vs 4 hours means i do not have to kill and restart the dnscrypt proxy service all the time
i also tried quad9-dnscrypt-ip4-filter-pri instead of quad9-doh-ip4-filter-pri and it lagged bad so i switched back to doh when i tried dnscrypt proxy i deleted tls_cipher_suite so that it would use default settings

i am not willing to give up performance and speed so that it lags and runs like the tor network where nothing ever loads in a respectable timely manor

**Comment by ghost** [comment]
what setting would i have to change so i do not have to stop and restart the dnscrypt proxy service every single time my ip changes?

**Comment by Icekiss69** [comment]
max_clients = i don't wanna be artificially limited to 250 by crapware or tyrants
tls_cipher_suite upgraded cyper suit
timeout 999 ms is link dead no idea why 5,000 is a thing you said high numbers here caused latency
cache_max_ttl = this setting should allow for good clean entries to last for up to one full week if not updated
cert_refresh_delay high numbers here causes internet to go permanently dead
cache_min_ttl high numbers here causes internet to go permanently dead
cache_neg_min_ttl high numbers here causes internet to go permanently dead
allot of the default settings for refresh rates are completely worthless for a machine box server that is never turned off because they never update in a timely manor so you either have to reboot the dnscrypt service or reboot the server
certificates are updated by the minute and tls every 30 seconds really good setting to keep the internet from crapping out
default toml runs like garbage unless the end user plans to reboot there pc by the hour
