### ISSUE TITLE
[Android] Please, please provide compiled binaries

### ISSUE THREAD

**Issue by HI54U** [DNSCrypt/dnscrypt-proxy#164]
It would be really good if someone can compile also for Android (Amd64) updated versions.
Hope someone can provide this. Thank you for your efforts!!!

**Comment by jedisct1** [comment]
Or add whatever has to be added to the Travis script so that they are built automatically.

**Comment by Sporif** [comment]
I tried adding the build guide to .travis.yml and it works. Tested the arm64 binary on my phone. no issues. 

https://github.com/Sporif/dnscrypt-proxy/releases

https://travis-ci.org/Sporif/dnscrypt-proxy/builds/344817293

I also tried using a docker container of the standalone android ndk ([rhardih/stand](https://github.com/rhardih/stand)) but it turned out much slower:

https://travis-ci.org/Sporif/dnscrypt-proxy/builds/344786625

**Comment by HI54U** [comment]
Thank you very much for actual version!

**Comment by jedisct1** [comment]
Are android/x86_64 and android/i386 actually needed?

I thought that Android-x86 had been abandoned. Chromebooks maybe?

**Comment by jedisct1** [comment]
Android builds have been added, thanks a lot @Sporif !

Do you think we should upx them?

**Comment by Sporif** [comment]
Just tried a upx version on my phone, says illegal instruction when I launch it :/

**Comment by jedisct1** [comment]
Ah, not a good start :(

**Comment by u1735067** [comment]
> I thought that Android-x86 had been abandoned. Chromebooks maybe?

http://www.android-x86.org/releases/releasenote-7-1-r1 :)
