### ISSUE TITLE
Errors are not written to syslog when in syslog mode

### ISSUE THREAD

**Issue by thuantran** [DNSCrypt/dnscrypt-proxy#169]
As the title suggested, can you consider changing this behavior, as well as making sure stdout/stderr messages are all written to syslog?
It would be easier for me to get log from my users, just in case.

Best regards,
Thuan

**Comment by jedisct1** [comment]
Check the configuration of your syslog daemon. Maybe the file you are looking at filters out messages whose severity is lower than the error messages you are looking for.

**Comment by thuantran** [comment]
I don't think that is the case as I specifically see the messages printed out to my terminal. The error I mention is for config file error, but I don't know if you have it at other places. I think if syslog is enabled, everything should go there, easier to look for error as sometimes it might be run unattended.

**Comment by jedisct1** [comment]
Your terminal prints everything, your syslog daemon only logs messages matching specific facilities and severities.

In order to log messages due to errors in the configuration file, you have to use the command-line option that specifies that logs have to go to syslog (I don't remember what it is, sorry. `-syslog` probably). Because the property in the configuration file cannot be used if the configuration file is invalid.

**Comment by thuantran** [comment]
Ah I missed that. I'll test this out and change my installation procedure to reflect this. Thanks a bunch.

**Comment by jedisct1** [comment]
No problem :)
