### ISSUE TITLE
[Feature] Allow to blacklist servers

### ISSUE THREAD

**Issue by u1735067** [DNSCrypt/dnscrypt-proxy#170]
If I'm right, the current version allow to filter servers, or whitelist them, but not to blacklist them.

I'm using the public server list with filters [nofilters, dnssec, nolog], and relying on the load balancing for the service to work correctly. Most of the settings are the default ones. Trusting the LB, I'm also using only one instance with v2 while I used 2 instances on two different fixed servers on v1.
But since I migrated to v2, I'm getting a lot of resolving failure, I even have to restart the service to get it working again (almost).

I can't see anything interesting in the logs (except for an app desperately trying to resolve the blocked `dev.appboy.com` spamming the logs), but I found https://github.com/bitbeans/SimpleDnsCrypt/issues/233 and https://github.com/bitbeans/SimpleDnsCrypt/issues/237 seems to indicate the same issue.

While I could use the whitelist, I would miss new servers in from the auto-updated list, so could it be possible to blacklist servers?

**Comment by jedisct1** [comment]
Looks like the failures you and others recently witnessed were due to a set of servers (`d0wn-*`) responding promptly and correctly (from a protocol perspective), but with responses containing errors.

The load balancer only paid attention to the latency, so kept sending traffic to them.

These resolvers have been removed from my list and changes have been made to the code to gradually avoid sending data to servers returning responses with errors.

A blacklist can be great, but solving the root causes is even more important. In particular, writing a tool that constantly monitors the health of all servers by sending real queries would be very useful.

With the Paris Fashion Week starting in a couple days, I won't have any more time to work on this, though. But I'd be glad to merge whatever you want to contribute.

**Comment by sergeevabc** [comment]
Let’s blacklist ```content.ad``` via DNSCrypt, then ```ping content.ad```, then do the same using Windows hosts by means of inserting ```0.0.0.0 content.ad```. The former option expects something for a while, while the latter option does the job outright and finishes with the message ```Ping request could not find host content.ad```. Is it possible to tune DNSCrypt to block that fast?
