### ISSUE TITLE
Enhancement : a whitelist to counter one's blacklist

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#198]
I know this has been discussed here already and as I understood it it's feasible: adding a setting to enable a domain whitelist conceived as an exception list in regard to one's blacklist (blacklist.txt).

When a user includes one or more filters in the blocklist some filters may include an entry which is either inappropriate objectively or undesirable by the user for personal considerations.

The idea is not new,

- [The more blocklists you add, the more likely you'll come across a false positive](https://wally3k.github.io/ )
- [Commonly Whitelisted Domains over at the Pi-hole forum](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212)

For instance I have a list I just don't add anymore given the fact it has one entry which is obviously a mistake. I won't check the blacklist to remove exceptions each time the list has been updated. If I could add that entry to a whitelist then I could take advantage of the whole list... 

I must point out that of course the argument concerns more particularly users handling several blocking lists (merged into DNSCrypt-proxy's blacklist). I have nine lists, merged with removed redundancies. Having a whitelist then would be a welcomed feature.

**Comment by ghost** [comment]
Topic already exists on #117, OK, thanks Frank.

**Comment by jedisct1** [comment]
Let's keep yours open instead, as the description is more concise.

**Comment by ghost** [comment]
I never know when to close or not doors I've opened myself in this place (I mean GitHub). :=)

**Comment by sergeevabc** [comment]
So what’s the recommended way to whitelist some (sub-)domain at present?
Or should I just a) manually delete it from ```mybase.txt```, then b) notify @jedisct1 and wait for an update?

**Comment by sergeevabc** [comment]
Issues are commonly closed if they are resolved as fixed, rejected, or invalid. I see whitelist feature was requested here and [there][1] and even [there][2], but see no reason to believe it is resolved. So why is it closed with a weird ```timeout``` tag then? It’s a kind of disregard for users. Have you lost passion, @jedisct1?

[1]: https://github.com/jedisct1/dnscrypt-proxy/issues/117
[2]: https://github.com/jedisct1/dnscrypt-proxy/issues/144#issuecomment-376687607

**Comment by jedisct1** [comment]
There hasn't been any progress after 30 days. I haven't had the time to do this, nobody offered to help either, so keeping this open is useless and won't make it magically happen in a near future.

**Comment by ghost** [comment]
Looks like the idea which I deployed after others had, meets little enthusiasm.

> There hasn't been any progress after 30 days

 is factual. I'm surprised but as always with little success the best concepts often vanish :=)

**Comment by sergeevabc** [comment]
Should we consider the project abandoned?
Or bug reports are the only things to be processed from now?
Is there a roadmap to see what is going to happen in the future?

**Comment by jedisct1** [comment]
You wrote a lot of comments, but never ever contributed anything to the project. Instead of random comments on old tickets, you could have documented the problem discussed in each ticket and its solution. That would have improved the project. But you didn't.

Does it mean that the project is abandoned?

No, just that people do whatever they feel like doing. If they have spare time (which is not really a thing. It's more about trade-offs with other things), if they feel like doing something in particular, if they think that they can learn by doing it, if this can be useful to themselves, they will do it.

If not, they might do it whenever they feel like doing it. Later. For any definition of later. Or never. There are no obligations.

Now, by writing "should we consider the project abandoned" because I didn't abandon my actual job to work for free on something you suggested within 3 weeks, you can be sure that my motivation to spend time on this immediately went down to zero.

**Comment by sergeevabc** [comment]
@jedisct1, aren’t you confusing mere users with developers? User is not skilled to contribute in terms of changing code. User applies tool to tasks in a way you may not even think of, within the environment you do not have, then reports back to developer about ambiguous, broken and missing pieces. It explains why I asked a lot of questions lately, i.e. to make things clear, because you made things obscure in the first place. Public issue tracker implies developer’s intention to gather feedback — why else keep it open. Then it means doing, even with vague roadmap and loose schedules, not silently canceling issues or [passive-aggressively][1] confronting users. Otherwise, have guts to inform you’re (busy, [burned out][2], done…), mute the tracker and mark the project as unmaintained to strangle public expectations for improvements.

![](https://pli.io/7GnBl.png)

[1]: https://en.wikipedia.org/wiki/Passive-aggressive_behavior
[2]: https://en.wikipedia.org/wiki/Occupational_burnout

**Comment by jedisct1** [comment]
Here is a better picture.

![perro-y-gato-durmiendo-petsonic](https://user-images.githubusercontent.com/124872/38113356-ff32fd54-33a4-11e8-9aef-5672a5d349ad.jpg)

**Comment by sergeevabc** [comment]
Hooray, it’s implemented in 65e6b8569ee65e168095d9cfb562681491df22f0! Thank you, Frank.
