### ISSUE TITLE
can i forced to return IPv6 address in forwarding-rules?

### ISSUE THREAD

**Issue by ztjal** [DNSCrypt/dnscrypt-proxy#217]
i under ipv4, and enable teredo ipv6, some domain have ipv6 address like 'imap.gmail.com'.
so, i want to interpret those domain force to return ipv6 address, don't return ipv4.
how can I do it?
or add a new feature in forwarding-rules? ( forwarding-rules-v6 ?)

**Comment by jedisct1** [comment]
Hi,

This is a bit complicated.

If the server returns an IPv6 address, but the client originally asked for an IPv4 address, the client will not use the IPv6 address.

The client must explicitly ask for an IPv6 address (`AAAA` query) before IPv4 for this to work. This is something you may be able to configure in your operating system or browser.

**Comment by ztjal** [comment]
ok, change ideas.

without modifying the hosts or cloaking-rules.

i hope force use ipv6 to connect some domain, like 'imap.gmail.com'.

first, i need force use ipv6 to explain domain name.

some domain name like 'imap.gmail.com', 'smtp.gmail.com', will be manually written in a txt like 'ipv6-rules.txt'.

**Comment by jedisct1** [comment]
So, that would be blocking queries based on names but also query types (to block `A` but not `AAAA` of the same name).
That looks a bit complicated, especially for the syntax.

**Comment by ztjal** [comment]
may be don't think too complicated.
like windows system ping.exe, 'ping -4' force use ipv4, 'ping -6' force use ipv6.

**Comment by jedisct1** [comment]
But here, `ping` is the application. It can do whatever it wants. But a proxy cannot choose what the client wants.

**Comment by vilyair** [comment]
If you are using Windows, this behavior may be modified in the registry:
`reg add HKLM\System\CurrentControlSet\Services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0`

This issue is inherently the precedence of IPv4 and IPv6. It could be displayed by the following command: `netsh interface ipv6 show prefixpolicies`.

If you want to adjust certain IPv6 address precedence, you might also use prefixpolicy to achieve it.
Take Teredo as an example:
`netsh interface ipv6 set prefixpolicy 2001::/32 40 1`

In my opinion, the precedence of IPv4 and IPv6 is determined by OS, and applications had better not touch it.
