### ISSUE TITLE
If ipconfig /flushdns can't run in service-restart.bat the service doesn't restart.

### ISSUE THREAD

**Issue by Atlntssplayer** [DNSCrypt/dnscrypt-proxy#2347]
After upgrading from an earlier version to the current (2.1.4) I noticed that a line was added into `service-restart.bat`.

I left it there.

But then I noticed that the service doesn't restart if I use this `.bat` file if it can't flush the dnscache (op. system built-in dnscache and services are disabled).

Maybe a condition to check if the op.system dnscache is even online before trying to flush it would solve it, but I have no idea, I don't know much about computers, I just thought I would report this.

I'm using Windows.

Thank you!

## *What* is affected by this bug?
My computer

## *When* does this occur?
When I try to use `service-restart.bat` to restart the service.

## *Where* does it happen?
On my computer.

## *How* do we replicate the issue?
If you use windows and disable the built in dns service I think you can replicate this error.

## Expected behavior (i.e. solution)
Expected would be to still restart `dnscrypt-proxy` even if it can't flush the dnscache.

## Other Comments
Thank you!

**Comment by lifenjoiner** [comment]
My tests:
| OS | Tests |
|-------|---------|
| Win 7 | Works, although `ipconfig /flushdns` triggers an error, if `dnscache` (DNS Client) service is stopped and disabled. |
| Win 10 | `dnscache` service can NOT be stopped nor be disabled. |

**Comment by jedisct1** [comment]
Is there a way to ignore the error, so that it would be okay for `ipconfig` to fail?

**Comment by lifenjoiner** [comment]
1. `ipconfig /flushdns` error is just a console message. It doesn't hang up.
2. Whether the following command is executed doesn't depend on the result of `ipconfig /flushdns`.


@Atlntssplayer 
Could you:
1. Make a copy of `service-restart.bat`, named as `p.bat` for example. Remove the line 23 `ipconfig /flushdns` of the `p.bat`. It should be the same as the previous version. Run them and compare, to make sure the restart failure is caused by the new command, or not.
2. If it is confirmed, provide the environment details of your OS: version, special config, tweaks etc.
