### ISSUE TITLE
Debian 9.4

### ISSUE THREAD

**Issue by ysz223** [DNSCrypt/dnscrypt-proxy#254]
How to configure in Debian 9.4, according to the method of the document, but failed.

**Comment by jedisct1** [comment]
Can you describe exactly what you did and what happened?

**Comment by ysz223** [comment]
I'm currently using 64-bit Debian 9.4, and the documentation you're writing seems to be inapplicable, especially the 127.0.0.1 configuration to the system.

**Comment by r4sas** [comment]
@ysz223 check that in your system not installed bind9 witch by default listening on 127.0.0.1:53.

**Comment by ysz223** [comment]
Have already installed bind9, also reinstall dnscrypt-proxy, still can not use, do you need to configure bind9 to open the service?

>  This file describes the network interfaces available on your system
>  and how to activate them. For more information, see interfaces(5).
> 
> source /etc/network/interfaces.d/*
> 
>  The loopback network interface
> auto lo
> iface lo inet loopback
> dns-nameservers 127.0.0.1

**Comment by r4sas** [comment]
set-up dnscrypt-proxy to use 127.0.0.2, for example, and set `dns-nameservers` to it also

**Comment by ghost** [comment]
Since this is semi-debian related, when will you push this wonderful v2.x.x to the debian packages?
https://packages.debian.org/sid/dnscrypt-proxy

Also another question: I see 12 threads in htop, care to explain how to limit these to 4? I cannot see the point in having so many.

**Comment by jedisct1** [comment]
@mkirisame I don't use Linux, but someone (maybe you ?) may eventually build a Debian package for it.

It may take some time before this actually gets into their repository, though.

I think the number of threads depends on the number of CPU core. Go maps one threads to one CPU core and then balances the load across all threads. This can be changed with the `GOMAXPROCS` environment variable.

**Comment by ghost** [comment]
@jedisct1 it is not that easy, since (edit: some) Linux distro packages are signed with a key or already owned by other maintainers and I'm way to unimportant to have such power.

But I wrote to [eric](https://github.com/zedinosaur) @ debian(.)org and explained the situation to him about your rewrite and the version differences, didn't know what OS you use or if you know him. Right now your binaries are used on a raspi 2 and 3 which is armhf, they both offer 4 physical cores, why 3 threads per core is still confusing.

**Comment by ran-sama** [comment]
Normally I would refrain from doubleposting, but this deserves its own post:

Eric contacted me today, the release was delayed because v2 
>has a fair number of dependencies that aren't currently packaged in Debian
He asked me to file a wishlist bug which I did here: [Debian Bug report logs - #894280 dnscrypt-proxy: Migration from 1.9.5-1 to version 2.0.7 or higher is required](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894280)

Debian and Ubuntu users may bookmark this page to check back on the progress of Eric. My thanks to everyone involved.

**Comment by ghost** [comment]
Normally I would refrain from doubleposting, but this deserves its own post:

Eric contacted me today, the release was delayed because v2 
>has a fair number of dependencies that aren't currently packaged in Debian

He asked me to file a wishlist bug which I did here: [Debian Bug report logs - #894280 dnscrypt-proxy: Migration from 1.9.5-1 to version 2.0.7 or higher is required](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894280)

Debian and Ubuntu users may bookmark this page to check back on the progress of Eric. My thanks to everyone involved.
