### ISSUE TITLE
panic: runtime error: slice bounds out of range (MIPS/MIPS64 2.0.7)

### ISSUE THREAD

**Issue by bkero** [DNSCrypt/dnscrypt-proxy#258]
I am receiving errors after a few minutes/hours attempting to run dnscrypt-proxy on my Ubiquiti Edgerouter Lite.

The error is as follows:

>goroutine 2067 [running]:
main.ReadPrefixed(0x8d9fe48, 0xbea5bf3b, 0x375d0a36, 0xf0, 0xb0a06843, 0x6eccc0)
>	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/common.go:67 +0x354
main.(*Proxy).tcpListener.func1(0x5153c0, 0x8d9fe48, 0x89908d4)
>	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:175 +0x1ac
>created by main.(*Proxy).tcpListener
>	/home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:167 +0xa8
>panic: runtime error: slice bounds out of range

**Comment by jedisct1** [comment]
Unfortunately, I don’t understand why it happens. Can you help?

**Comment by ghost** [comment]
Looks like the DNS packet size is out of bounds, are you using UDP, TCP?

What about your IPv6 settings?

From: https://www.potaroo.net/ispcol/2017-08/xtn-hdrs.pdf

>The  basic  approach  is  that  any  IPv4 router that is unable to forward an IPv4 packet into the next network because the  packet  is  too  large  for  the next  hop network  may  split  the  packet 
into a set of smaller “fragments,” copying the original IP header fields into each of these fragments, then forwarding each of these fragments instead. 

You said you're using Ubiquiti Edgerouter Lite. Have you setup IPv6?
Because it looks like it needs to be setup manually: http://www.forshee.me/2016/03/08/ubiquiti-edgerouter-lite-setup-part-4-ipv6-setup.html

Maybe it's receiving IPv6 packages but you haven't setup IPv6?

Try disabling IPv6 in the .toml file as an experiment.

**Comment by jedisct1** [comment]
According to the stack trace, this is using TCP, it happens exactly here: https://github.com/jedisct1/dnscrypt-proxy/blob/fa2c95084ef9b575bfbe62543e0765623c9b8a0e/dnscrypt-proxy/common.go#L66-L68

If this is actually version 2.0.7, I don't see how this can possibly happen.

**Comment by bkero** [comment]
This certainly is running 2.0.7.
> root@ubnt:/opt/dnscrypt-proxy# ./dnscrypt-proxy -version
> 2.0.7

I can try running with IPv6 explicitly disabled once my network connection is available.

**Comment by jedisct1** [comment]
Please reopen if you still get this with version 2.0.8 :)
