### ISSUE TITLE
Support multiple URLs for a given source

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-proxy#265]
So we can have mirrors, and improve resiliency.

**Comment by JayBrown** [comment]
Maybe just add a copy to a GitHub repo? Nation state actors can block dnscrypt.info, but it would surprise me if they blocked the whole of GitHub because of only one public-resolvers.md file.

You could also—but this would be a major code change—decentralize the distribution of the latest source file. One node (the originating node) would publish the new source file, all client nodes running DNSCrypt would then download and reseed the .md, similar to DHT/torrent.

**[go-ipfs](https://github.com/search?utf8=✓&q=go-ipfs)** with IPNS refresh via pubsub comes to mind. :)

**Comment by JayBrown** [comment]
Example using IPFS—just a few simple hacks on the command line using the default **[ipfs CLI](https://github.com/ipfs/go-ipfs)**:

The current source & signature files have the following hashes, which you can download using `ipfs get <hash> -o /LocalPath/to/file`:

```
public-resolvers.md	QmdLe9RBZW2nmwNcvX4n31K7TAi992AuyRaRHvLYmFTCHy	17805
public-resolvers.md.minisig	QmZUhGZKgE7Q8f7yoFNBzGgyLnbanqb9LbNvt7jpDxnW5t	307
```

The parent directory hash is `QmZwMP3tSQNontTQKePqaDpvDnSvNFjbshM8XThYAQs6ua` and is accessible via localhost and gateway nodes:

http://localhost:8080/ipfs/QmZwMP3tSQNontTQKePqaDpvDnSvNFjbshM8XThYAQs6ua
https://ipfs.io/ipfs/QmZwMP3tSQNontTQKePqaDpvDnSvNFjbshM8XThYAQs6ua

These files are decentralized, distributed, and with immutable hashes, so the hashes always change, when the files are updated. That's why there's the naming system IPNS, which has an immutable parent (or master) hash (and therefore an immutable path/URL), while the contents are mutable, e.g. when the source file is updated by the originating node that has the secret IPNS key. An example IPNS hash originating from my own node is `Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP` … also available as above:

http://localhost:8080/ipns/Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP
https://ipfs.io/ipns/Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP

The publish command for IPNS would be: `ipfs name publish --key=dnscrypt-source <CurrentParentIPFSHash>`, whereas "dnscrypt-source" is just the name I gave my secret IPNS key, and whereas "CurrentParentIPFSHash" would (as of today) be `QmZwMP3tSQNontTQKePqaDpvDnSvNFjbshM8XThYAQs6ua` (_see above_). If you start the IPFS daemon with the new `--enable-namesys-pubsub` option, then IPNS records are not distributed via DHT (only as a fallback), but by using the built-in pubsub system.

This stuff, i.e. adding content to the IPFS & publishing to IPNS, can be automated on the originating IPFS node, and then the DNSCrypt proxy servers "just" need a small built-in IPFS node to listen via ipfs pubsub for IPNS updates, and then download the contents (the new source file) into the node and extract the actual files to ./etc … however, they would also need to **pin** the files to the local node for reseeding. The relevant CLI command would be `ipfs pin add <hash>`. (Older files pinned to the node can then be removed in order to keep the filestore small.)

One additional advantage is that you don't need minisign anymore to check the source file, because it would all be auto-verified through the IPNS & IPFS hashes.

**Comment by JayBrown** [comment]
A demonstration LaunchAgent + shell script is here:

https://github.com/JayBrown/DNSCrypt-Menu/tree/01a7360577b27cd5720b296c6cab80cb85bf11b3/IPFS
(only a quick hack; still buggy if ipfs daemon fails to launch)

The agent uses `fswatch` on the .md file. (I've never used `fswatch` before, so I hope it works.) If the .md is updated & if the md5 hashes are actually different, the agent runs the script which will remove the old files (resolvers + signature) from the IPFS node, add the new ones, cache them on a couple of public gateways, and then publish it all to the IPNS under `Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP`, i.e.:

http://localhost:8080/ipns/Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP
https://ipfs.io/ipns/Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP
and on other gateways.

Needless to say, many computers (like mine) are not always online, so a similar procedure could be run by an IPFS node on the computer, where the .md file originates.

To get the current IPFS hashes of the actual files, run:

```
❯ ipfs ls /ipns/Qmcy2uSAkLDLaGsPagjbwHJJMwkXJQu5XvxGiUpN1jzsSP
QmdLe9RBZW2nmwNcvX4n31K7TAi992AuyRaRHvLYmFTCHy 17819 public-resolvers.md
QmZUhGZKgE7Q8f7yoFNBzGgyLnbanqb9LbNvt7jpDxnW5t 318   public-resolvers.md.minisig
```

**Comment by iWARR** [comment]
But first, an authors of the **go-ipfs** have to be sure that protocol is well protected. Then it can be advisable for wide audience.

**Comment by JayBrown** [comment]
The bold future of the internet is decentralized. You could add support for multiple URLs of the same file, old-school & quickly implemented, or you could have DNSCrypt nodes P2P-sharing that file (the resolver list, all of them) amongst themselves, no point of failure. At any rate, the question is not so much about security, but privacy & self-determination. You can block URLs & domains. You can't block a distributed file shared by all DNSCrypt users. As for bugs & exploits: they are everywhere. We shouldn't let that get in the way.
