### ISSUE TITLE
kill -HUP behaviour

### ISSUE THREAD

**Issue by wulungnet** [DNSCrypt/dnscrypt-proxy#278]
Sorry for long time not checking in, jump to v2 is very good.
Now I use 2.0.6 linux x64 binary from release, run manually.
This is Enhancement request :)

In linux usually `kill -HUP` command put the program to reload the config then restart/resume the operation with the same pid.
I did that and dnscrypt-proxy just quit and no log write that it did quit.

Would be nice to have this feature. Thanks.

**Comment by jedisct1** [comment]
If something has changed in the configuration file, we will need to parse everything again, refetch certificates, and essentially do the same thing as stop/start. Even the cache needs to be flushed in cache cloaking rules are changed.

So, handling SIGHUP to reload the configuration wouldn't be very different than stop/start.

It could reload the modules, though. So that blacklists could be reloaded that way.

Except that... SIGHUP (and generally, Unix signals) has no equivalent on Windows.

So, this has to be done differently. Maybe by watching blacklist/cloaking/forwarding files for time changes.

Do you think this is something you can implement?

**Comment by wulungnet** [comment]
Haha I'm not a coder in terms of Go. Sorry.
No pressure though. Could use some list to do for this feature, if all above behaviors will be included. Put long milestone to this if that needed.
What bother me first are, nothing in log and very quick on quitting [kill will do that of  course :) ].
