### ISSUE TITLE
No connectivity after changing DNS Server to 127.0.0.1

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#285]
First post on Github, so sorry if my question is absurdly dumb. I've spent a fair amount of time Googling and wasn't able to find the solution on my own.

I am on macOS High Sierra. I've successfully installed and started dnscrypt-proxy via brew.

```
myname$ brew services start dnscrypt-proxy
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 14 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Tapped 0 formulae (43 files, 55.2KB)
==> Successfully started `dnscrypt-proxy` (label: homebrew.mxcl.dnscrypt-proxy)
```

...but then when I go to change my DNS server to 127.0.0.1 in System Preferences --> Network --> Advanced, I lose all connectivity. Anyone have any advice for how to troubleshoot this? Again, I am a complete novice here, so it's very possible I'm doing something obvious wrong.

**Comment by JayBrown** [comment]
You need to start the service using the `sudo` command, otherwise `homebrew.mxcl.dnscrypt-proxy` will just wind up in `~/Library/LaunchAgents` (user)  instead of `/Library/LaunchDaemons` (global).

But first stop the service with: `brew services stop dnscrypt-proxy`
Check if it's really stopped with: `pgrep dnscrypt-proxy`
Then you can launch the service as root with: `sudo brew services start dnscrypt-proxy`
Check if it's running as root with: `pgrep -U 0 dnscrypt-proxy`

**Comment by JayBrown** [comment]
Updated wiki: https://github.com/jedisct1/dnscrypt-proxy/wiki/installation#installing-dnscrypt-proxy-on-macos-as-a-system-service
