### ISSUE TITLE
Respect server filters even when server_names= is specified

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#286]
Good day.

Been testing dnsCrypt-Proxy for 2 weeks. Started with SimpleDNSCrypt but that has too many bugs and limitations and toml is easy to edit (plus we have a nice python script for blacklist building). It is with that UI however that I noticed something: If we specify a list of servers using server_names= then restrictions on which servers to use are ignored (require_dnssec, require_nolog, require_nofilter.) Possibly the other two rules are also ignored but I'm not sure (dnscrypt_servers, doh_servers).

Suggest the proxy should filter the list of supplied servers and only use those which satisfy specified requirements. I **have** to specify servers manually, because if I let the proxy pick them for me, it will pick servers all over the world and I end-up downloading e.g. Dropbox updates from the UK etc. So what I like to do is pick the list of the 10 fastest continental America servers, stuff them in server_names= and then restrict which to use with the require_xxx settings. I cannot do that right now. And since I cannot read the sdns:// string, I end-up having to use SimpleDNSProxy to select servers (which messes-up my toml file.)

Thank you.

**Comment by evilvibes** [comment]
Not sure if this will help you or not but you can view all the servers here https://dnscrypt.info/public-servers

And you can manual add the servers you want to use only to server_names. You can also look at the stamps here https://dnscrypt.info/stamps

Edit also you can have a look here https://mastad0n.github.io all server by country note the list here are missing some servers.

**Comment by Utini2000** [comment]
I would also wish for a way to enable "server_names" while still using the "requires" filters.

**Comment by jedisct1** [comment]
Hi,

If you explicitly name a server, this is because you want to use it :)

That was what felt more intuitive to me and thus the current behavior. 

As pointed out by Evilvibes, and even if they are not always up to date, Mastad0n made feeds of resolvers organized by country.

Anyone can make such lists with the criteria they want. It's very easy: just copy/paste the parts you want from the `public-resolvers.md` file and sign the resulting file.

This has a lot of advantages over using the main list and manually defining the `server_names` set.

The list can be public. So that everyone can use it instead of having to do the same thing.
The list can be refined using filters.
Updates to the list will be immediately downloaded by everybody using it. Unlike a `server_names` set the will not always have the newest resolvers in your country, or that will list resolvers that don't exist any more.

Sure, a `always_use_filters_even_for_explicitly_named_serves` option can be added (but we have to find a better name for it!).

But I would really encourage making and publishing new lists instead, or helping the current ones being always up to date!

**Comment by B00ze64** [comment]
Good day.

@evilvibes Hey Andrew, didn't know there was an online SDNS decoder (much easier than having to code one, or to save the Base64 into a file, decode it and try to read it). The Public-Servers list is good too (better than relying on the comments in public-resolvers.md). About Mastad0n's lists - This looks perfect, I can specify multiple countries and have the proxy decide for itself but Question: What's the public miniKey for those lists?

@jedisct1 Hi there. I wouldn't know where to begin making a list. I don't really follow DNSCrypt mailing lists etc where servers are discussed, posted etc. The only thing I could do is use the public list you guys publish, decode all the addresses, figure out which country each server is from using its IP, and compile into a new list. Quite doable with a script (altho it would be quite an undertaking for me,) but way too labor intensive to do manually. It's too bad SDNS doesn't include a country code. Well, it's up to you - I will be changing my toml file to point to Mastad0n's lists (as soon as Andrew explains where the public key is) and this will be enough for me. If Mastad0n builds those lists manually we can forget about this being a long term solution, but if he has scripted it, then maybe he can publish the script so we can run it locally against your master list? I already see a deprecated server in Mastad0n's Canada list, the best would be if we could run this ourselves...

EDIT: Never mind Mastad0n's public key, it's listed in the Wiki, my bad!

Thank you.
Best Regards,

**Comment by B00ze64** [comment]
@mastad0n How about it Sir; care to share the script you use to build all those nice servers-by-country lists that you have posted on GitHub?

**Comment by jedisct1** [comment]
@B00ze64 The JSON file used to display the map on the website includes the country name:
https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json

It's updated every time the main list is updated.

But the country name is automatically found from the resolver IP address, using GeoIP, so it may not always be the correct one.

**Comment by B00ze64** [comment]
Good enough for me, thanks! Checked quickly and PowerShell 3 can read JSON. So now I have to write my second PowerShell script ever; this will take some time...

EDIT: You beat me to it - was gonna update the Wiki with new ARS Technica article about DNSCrypt...
