### ISSUE TITLE
TCP_NODELAY required?

### ISSUE THREAD

**Issue by geekmiki** [DNSCrypt/dnscrypt-proxy#288]
I am running dnscrypt on Archlinux and dnscrypt-proxy.socket reports the following:
Mar 30 01:50:34 RPi-SSHGateway systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available

Is there anything to do outside of dnscrypt-proxy to enable tcp_nodelay system wide?

Thank you in advance.

**Comment by Utini2000** [comment]
The dnscrypt-proxy.service (or was it the .socket?) has a "no-delay" parameter inside. Maybe this is it?

**Comment by geekmiki** [comment]
it is enabled in  dnscrypt-proxy.socket:
NoDelay=true

**Comment by jedisct1** [comment]
It's very weird that the option cannot be set. `TCP_NODELAY` has been implemented on all Unix systems for 20 years. Are the UDP and TCP sockets in the correct order? Maybe they have been swapped?

If you don't absolutely need to use systemd sockets, don't use them. Delete the `.socket` file and just configure the IP addresses you want to use in the `dnscrypt-proxy.toml` file.

**Comment by geekmiki** [comment]
TCP and UDP socket were not swapped.

I am trying without .socket now.

What is the format of the IP address in dnscrypt-proxy.toml? 127.0.2.1:5754 gives me an error:
Near line 31 (last key parsed 'listen_addresses'): Invalid float value: "127.0.2.1"

**Comment by geekmiki** [comment]
Running without socket works fine. Thanks for your help.

**Comment by Utini2000** [comment]
@jedisct1 but enabling the service will automatically also enable the socket?

> sudo systemctl enable dnscrypt-proxy.service
Created symlink /etc/systemd/system/multi-user.target.wants/dnscrypt-proxy.service -> /usr/lib/systemd/system/dnscrypt-proxy.service.
Created symlink /etc/systemd/system/sockets.target.wants/dnscrypt-proxy.socket -> /usr/lib/systemd/system/dnscrypt-proxy.socket.

**Comment by geekmiki** [comment]
@Utini2000 You have to edit the dnscrypt-proxy.service unit and remove the .socket dependency (at least that worked for me)

**Comment by dvzrv** [comment]
First of all:
`NoDelay=True` is a [non-default setting](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#NoDelay=) for a socket unit.

The warning message about it not being available ~~(because Arch probably somehow has it disabled)~~, won't make the socket unit fail to listen on any port you specify. Therefore this can be ignored.
More info on `TCP_NODELAY` ~~and why it might be disabled~~ can be read up in the [tcp man page](https://linux.die.net/man/7/tcp) or in [this article](https://eklitzke.org/the-caveats-of-tcp-nodelay).

The solution to removing the warning is either to remove the corresponding setting in this repository and then ship it with the next version (as it is an absolute non-default and probably not needed), or to override it in a local version on your machine (`systemctl edit dnscrypt-proxy.socket`).
@jedisct1 deleting it is rather bad advice, as this is a system file! However, if one wants to use the service unit without the socket file, it can be achieved by first masking the socket (`systemctl mask dnscrypt-proxy.socket`) and then overriding the systems default service unit (`systemctl edit dnscrypt-proxy.service`) and removing the socket settings.

**Comment by dvzrv** [comment]
I have to revert parts of my above statement:
`TCP_NODELAY` fails in this specific case, because it is applied to a UDP socket. So, this has nothing to do with Arch, but is a completely valid statement: "For the (`UDP`) socket, I can't apply this setting and I'm not going to!"

So, for the `TCP` socket it's a valid setting, but not for the `UDP` socket! In any case, it doesn't lead to the socket unit to fail!
