### ISSUE TITLE
Improvement for service-restart.bat

### ISSUE THREAD

**Issue by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [DNSCrypt/dnscrypt-proxy#290]
Hello Frank,
I ran into a malfunction during the service update process under Windows. The reason was, that the service was not even started yet. Therefore the restart option failed during the internal work flow, because there was nothing to close the start task was not executed. The solution is to substitute the restart command with 2 commands; the stop command and the start command. The stop line gives an error too, but the start option will be executed anyway and the service will be started --> success.
Regards
Andreas

**Comment by jedisct1** [comment]
Hi Andreas,

So this would be replacing

```
.\dnscrypt-proxy.exe -service restart
```

with

```
.\dnscrypt-proxy.exe -service stop
.\dnscrypt-proxy.exe -service start
```

?

Does it work as is or is a delay required between both commands?

**Comment by iWARR** [comment]
This is not an exactly "issue" of "dnscrypt-proxy" and may happen on Windows:

1. Service may change if you update it. Windows don't like it and may stuck.
 That's why you succeed within (manual) relauching a commands.

2. This is usual if you have Antivirus in your system. Some of them reconize changes in the critical for Windows section - System Services. That's why updated apps need to be added to the "Trusted" zone, then restarting/reinstalling again.

My experiance says, that present *.bat files working 100% and working fast in the context of the same version. Moving to the updated version requires a few relaunches due to stuck by described reasons.

@jedisct1 
> Does it work as is or is a delay required between both commands?

I think, this is not.

Windows Agreement changes are required to one sentence:

> Installing Windows you're agree to feel like Alice in Wonderland.

**Comment by jedisct1** [comment]
So, should we make the above change or not?

**Comment by sergeevabc** [comment]
```service-restart.bat``` works fine on my end (Windows 7 x64).
I launch it after updating ```blacklist.txt``` and ```dnscrypt-proxy.toml```.

**Comment by jedisct1** [comment]
The feedback isn't really clear, but it looks like changing the script is not necessary.

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Hello Frank,
First of all: a delay is not necessary, the second command is only run after the first one is finished.
I am a server administrator now for decades and "we" always split commands into the smallest possible parts to have the best failure tolerance. In case a service is corrupt and You commit a restart command to have everything neat before the next working day begins after the nightly backup, there won't be a calm morning, because the service is not started. The restart is so stupid, that it only executes the start of a service if it realizes that the service is running perfectly and it was able to stop it. So two possible reasons for failure. In case of a split command there is a good chance that the service just starts --> no problem.
