### ISSUE TITLE
Can't set log level to debug

### ISSUE THREAD

**Issue by gordyf** [DNSCrypt/dnscrypt-proxy#297]
I've set "log_level = 0" in my dnscrypt-proxy.toml, and also ran with "-loglevel 0" but I'm still only seeing "NOTICE"-level logs in my dnscrypt-proxy.log. I expect to see debug-level logs with such a log level. Is there something more I need to do to see debug logging?

**Comment by jedisct1** [comment]
Yep, that's intentional.

Debug logs are really only for debugging, and users enabling this would result in a slew of Github issues "I see this! It says warning! It says error! How do I fix this?" without understanding the context the messages fit in.

But if you are working on the code, and need this, you will quickly figure out how to enable these messages :)
