### ISSUE TITLE
Add support for systemd sockets

### ISSUE THREAD

**Issue by Zirkelite** [DNSCrypt/dnscrypt-proxy#3]
The previous version of `dnscrypt-proxy` supported using systemd sockets instead of directly listening to the port. This allows for more versatility and, for example, makes it possible to run the program without root privileges (since it does not have to listen directly to a privileged port).

**Comment by jedisct1** [comment]
This is something I am not planning to work on in a near future (I don't use Linux), but I'd be glad to merge any contributed code.

That being said, many, if not most of the issues raised with the previous versions on Linux were due to systemd sockets. They don't seem to work reliably on dynamic IP changes, in addition to being complicated to configure.

**Comment by jedisct1** [comment]
Support for systemd was added in beta9.

But don't expect me to provide any useful help if this doesn't work properly...
