### ISSUE TITLE
dnscrypt-proxy.plist invalid on macOS

### ISSUE THREAD

**Issue by jymoulin** [DNSCrypt/dnscrypt-proxy#304]
Hi,

When adding dnscrypt-proxy as a system service (dnscrypt-proxy -service install), the generated dnscrypt-proxy.plist is missing some information (config file path and running user).

dnscrypt-proxy version 2.0.8 installed with brew.

I add to patch with:

--- dnscrypt-proxy.plist.orig	2018-04-03 11:54:09.000000000 +0200
+++ dnscrypt-proxy.plist	2018-04-03 11:23:11.000000000 +0200
@@ -7,8 +7,16 @@
 <key>ProgramArguments</key>
 <array>
         <string>/usr/local/sbin/dnscrypt-proxy</string>
+		<string>-config</string>
+        <string>/usr/local/etc/dnscrypt-proxy.toml</string>
 </array>

+<key>GroupName</key>
+<string>wheel</string>
+<key>UserName</key>
+<string>root</string>
+
+
 <key>SessionCreate</key><false/>
 <key>KeepAlive</key><true/>
 <key>RunAtLoad</key><false/>

**Comment by jedisct1** [comment]
If the config file is not in the same directory as the executable file, the `-config` command-line option should be provided along with `-service install`.

Something that needs to be mentioned in the documentation. Would you mind adding this?

On macOS, I expect most users to install it through Homebrew which directly installs its `.plist` file. But this should definitely be documented, if only because Linux and Windows users may have the same issue.

**Comment by jedisct1** [comment]
The `.plist` file is generated by https://github.com/kardianos/service/blob/master/service_darwin.go so I don't think we have much control over it. It keeps the initial command-line arguments, though.

**Comment by jymoulin** [comment]
Ok, thanks. In fact my complete command, for service install, was:
> dnscrypt-proxy -config /usr/local/etc/dnscrypt-proxy.toml -service install

(dnscrypt-proxy doesn't run otherwise)

But the config file path wasn't added in .plist.

**Comment by jedisct1** [comment]
This is a mess. Or, actually, way too complicated for my Go skills.

So, either leave everything in the same directory, or modify the `.plist` file. Unless you know how to fix this.
