### ISSUE TITLE
[QUESTION] dnscrypt-proxy v2 & dnsmasq: drduh information still up-to-date?

### ISSUE THREAD

**Issue by JayBrown** [DNSCrypt/dnscrypt-proxy#305]
I have created a pull request to update the _general_ information on DNSCrypt version 2. See here: https://github.com/drduh/macOS-Security-and-Privacy-Guide/pull/291/commits/32a989c3bb4f3f6a7f7865c1cc037481a7375d73

However, I'm not sure if the specific info on using dnscrypt-proxy with dnsmasq is still up-to-date: https://github.com/drduh/macOS-Security-and-Privacy-Guide#dnscrypt

Anyone who knows more?

**Comment by jedisct1** [comment]
As long as the port number (5355) matches, the dnsmasq information should still be valid.

I'd recommend using dnscrypt-proxy directly instead of dnsmasq for filtering, though, as it supports more patterns and can drastically reduce the number of required rules.

If this is only for filtering and caching, dnsmasq is not even useful and will only add complexity and latency.

**Comment by JayBrown** [comment]
So it's true that the user needs to edit the plist, not the TOML, if he wants to use dnsmasq. That was the main thing I was unsure about.

Anyway, thanks for the heads-up about dnsmasq. I had thought about installing it for running a local DNS resolver to be accessed by dnscrypt, but if it's not useful… good… less work for me. ;)

**Comment by jedisct1** [comment]
Oh, I had overlooked that. You're right, the IP address just needs to be changed in the TOML file, not in the plist. In fact, it was already the case with dnscrypt-proxy 1.x, except with very old versions that didn't had a configuration file.
