### ISSUE TITLE
Dnscrypt-proxy is completely unusable on linux desktop

### ISSUE THREAD

**Issue by mxfm** [DNSCrypt/dnscrypt-proxy#319]
Hi! I was happy user of dnscrypt v1. untill recently when after Arch update this software landed on my desktop. The most strange point is that this program designates itself as replacement of v1 (at least by Arch developers).

My network configuration is follows (was working for 3 years without an issue). I manually start wpa_supplicant service, than dhcpcd, than dnscrypt service.

Today running 'systemctl start dnscrypt-proxy' failed because dependency 'dnscrypt-proxy.socket' failed because of some socket opening error. I believe this is an issue by itself because dnscrypt can work with default settings. Unfortunatelly, there is no way to inspect what exactly causes this failure.

I tried to launch daemon manually from command line, but the syntax of v.2 differes significantly from v1. OK. However, after running daemon as 'dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml -service start' DNS stil does not work and nobody listens 53 port.

I tried to configure 'listen_adress' config to ['127.0.0.1:53'] but this not helped (ignoring some time I spent guessing that I should surround localhost with '' because of new brilliant TOML syntax). Judging from nmapping 127.0.0.1 I do not have service listening 53 port. 

Finally, I carefully studied documentation (at /usr/share and at github). Unfortunatelly, it covers only the topic of dns servers. The page covering differences with v.1 could have been very usefull if it was devoted to differences in config file names, config syntax, default settings. Unfortunatelly, currently it only pleases ego of it developers by claiming how nice is Go language, etc.

So, here are three issues:
1) Not working with default settings ('systemdctl start dnscrypt-proxy' should work out of the box).
2) Not working after manual daemon starting, editing 'listen_addresses = ['127.0.0.1:53']' in dnscrypt-proxy.toml
3) Absense of documention how to configure 'listen_adress' in particular, or in general how to launch dnscrypt (I mean how to make it to listen to 53 port).

**Comment by jedisct1** [comment]
Thanks for your help improving the documentation!

**Comment by mxfm** [comment]
> Thanks for your help improving the documentation!

Is this a joke? There are no improvements in documentation.

Dnscrypt does not work either via systemd, or with manual daemon starting. It does not listens 53 port. This is a bug. The issue should be reopened.

**Comment by jedisct1** [comment]
I'm not a Linux person, but following the generic [installation instructions for Linux](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-linux) worked out of the box on a Arch Linux system.

Since you are referring to things that are present nowhere in these instructions (`systemctl`? things in `/usr/share`? configuration in `/etc/dnscrypt-proxy/dnscrypt-proxy.toml`? `listen_addresses` to change? `.socket` file?), I reckon you didn't follow them.

So, start from scratch and follow them.

And if they don't work for you, figure out why and improve the documentation, especially the ones for Arch Linux (that I never tried, because installing Yaourt, etc. was too complicated for no benefits and the generic instructions worked).

**Comment by eli-schwartz** [comment]
I guess you're free to go to the Arch Linux package details page for dnscrypt-proxy and follow the "View Changes" link, to get the v1 PKGBUILD. You're more than welcome to use that, or even upload a dnscrypt-proxy-legacy package to the AUR if you really feel it has advantages.

For obvious reasons, we will not package outdated versions of things in the official repos. Given that this is the upstream developer of dnscrypt-proxy, developing a program called dnscrypt-proxy in the canonical location, I'm going to go out on a limb here and say there is no need to "replace v1". We've merely updated to the latest version....

I won't comment on the rest, except to say lots of people apparently did not have your issues; the repo package (which simply builds the same binaries as the ones uploaded here, but using *our* Go compiler, plus updating config filepaths to use consistent system logging directories) seems to work out of the box for them.

...

Alternatively explain what your actual issue is, rather than what **didn't** work to fix it? Maybe then the developer could actually try to help you.

Also keep in mind the default systemd service uses socket activation, so you're supposed to specify the listen_address in the .socket file, not in the toml config file (maybe this would aid in your quest to see how to configure things?)

**Comment by mxfm** [comment]
1. I have written request here in an attempt to fix the current version, rather than to use old.
2. I have read that several people using the package out of the box in Arch bugzilla. After some tricks dnscrypt-proxy started to work (this tricks cannot be qualified as fixes).
3. My issue is explained in the post in three points (you said that you would not comment on the 'rest' which describes problem): not working out of the box (I wrongly assumed that Arch completely follows upstream, so this could be package issue rather than the program itself), not working after manual launch after configuration fixes in TOML file, sparse documentation (which spends more time on praising the new version rather than explaining how to migrate to new version).
4. I will look at the .socket file. By the way, I have found nothing about in the documentation.

**Comment by eli-schwartz** [comment]
> explain what your actual issue is, rather than what didn't work to fix it

I'm depressed that an Arch Linux user wouldn't know this already. You failed to do this, instead spending the bulk of your time complaining about the choice of configuration file formats, then obliquely referencing "some error".

(re: the wiki "differences from v1", I don't see any point in documenting specific differences when the whole idea is "literally everything is different, please start from scratch". Complaining that the relevant wiki page is instead devoted to listing reasons why the new version is "better", is a really weird complaint and indicates you're once again missing the point.)

> After some tricks dnscrypt-proxy started to work (this tricks cannot be qualified as fixes).

Well, this is useless. You're still positive it doesn't work out of the box, but you won't tell the author what your actual problem is. You will tell him that you got it to work, but you're being evasive about what fixed it, so he cannot consider if it is possible to make those "tricks" unnecessary, and also ensuring if anyone else stumbles across this issue via google, they won't either know how you fixed it.

> I will look at the .socket file. By the way, I have found nothing about in the documentation.

https://github.com/jedisct1/dnscrypt-proxy/blob/0cca203bb0cb6cab326c0ee9037a154ad6b50452/dnscrypt-proxy/example-dnscrypt-proxy.toml#L34

I don't think people usually re-document systemd when systemd has perfectly good documentation on systemd socket activation already. So I guess this comment in the dnscrypt-proxy config file is all the documentation needed for "look at the socket file and consult your systemd documentation if you need more help". (Maybe that line could be added to the comment, would that make you happy?) At a certain point jedisct1 does need to assume that users actually think about the problem.

...

My point here is very simple: you're being extremely unhelpful for someone who opened an issue for presumably the desire to get help.

**Comment by mxfm** [comment]
@eli-schwartz , I have written what my issue is in the first post here (if you are really interesting, I provided also information in Arch bugzilla, the issue was closed as 'configuration error'). 

My issue/problem is that dns stopped working after switching to the second version of dnscrypt-proxy. In particular, starting service dnscrypt-proxy failed because dependency dnscrypt-proxy.socket failed. The dependency failed because it was unable to open socket with error 'Input/Output error'. This is what I called 'does not work out of the box'. 

Then I tried to launch dnscrypt-proxy via command line. I changed config 'listen_adress' option to [127.0.0.1:53] (following the comment in documentation you mentioned) and added dns servers in 'server_names' option. Judging by program output (and htop) dnscrypt-proxy runs without any error but dns is not working ("Temporarily failure in domain resolution" error or something like that). This is presumably because (judging by nmap 127.0.0.1) nobody is listening to 53 port. I have only 127.0.0.1 as nameserver in resolv.conf.

By the way, you pointed to 'listen_address' config ((of course, I noticed it)) but it seems to be irrelevant to my issue. The option was set to default value [] in the arch package (for using with systemd socket activation) when I tried to start .service. When I was trying to launch dnscrypt-proxy manually, I have changed this option to ['127.0.0.1:53'] as documentation suggests. Thus, according to my understanding of documentation, this setting was as it should be when dnscrypt-proxy was starting via systemd and when starting manually.  

Your comment about 'keep in mind the default systemd service uses socket activation' I initially interpreted as 'dnscrypt-proxy.socket' file requires adjustments. Now I see you meant 'listen_addresses ', but I believe I had correct settings.

I am silent about what fixed the error because I don't remember and don't want to report inaccurate information. After having zero success with documentation I worked on the issue on my own and changed several settings. I need some time to investigate which particular setting fixed my problem. Since the program finally started to work, I believe that it was indeed 'configuration error'. 

Another reason I don't explain what fixed is because both this issue and arch bugzilla issue were closed, so it seems my further reponses are not expected.
