### ISSUE TITLE
[QUESTION] Difference 'cloudflare' and 'doh-crypto-sx'

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#322]
Hi,

I'm learning, step by step.
I stumble on the difference between `'cloudflare'` and` 'doh-crypto-sx'` servers.

`'cloudflare'` : _Cloudflare DNS (anycast) - aka 1.1.1.1 / 1.0.0.1_
`'doh-crypto-sx'` : _DNS-over-HTTPS server. Backend hosted by Scaleway, globally cached via Cloudflare._

Both are DoH, what makes them apart? Any additional security with `'doh-crypto-sx'`?

Thanks.

**Comment by jedisct1** [comment]
`doh-crypto-sx` was probably the first global DNS-over-HTTPS server.

This is something I had set up using Cloudflare, because using a CDN for DNS-over-HTTPS made total sense, and this is something I could configure on Cloudflare for free.

It has nothing to do with Cloudflare's own `1.1.1.1` project that was announced later.

Does it make sense to keep `doh-crypto-sx` around now?

I don't know... It's using different server software, so it can still be useful for interoperability testing. And if something doesn't resolve properly using Cloudflare's own servers, maybe it will resolve properly using `doh-crypto-sx` or the other way round.

But Cloudflare's own servers will always be faster for non-cached queries; I can't compete.

So, maybe it's time to retire `doh-crypto-sx`, especially if it looks confusing.

**Comment by ghost** [comment]
OK, I start to better conceptualize the difference, thanks Frank.

> [...]Cloudflare's own servers will always be faster for non-cached queries; I can't compete.

I've tested both, always one server at a time of course (in fact I always choose only one server) and if the difference in speed isn't flagrant I've encountered nevertheless times when `doh-crypto-sx` seemed to suddenly slow down, and immediate change to `cloudflare` restored the slow-down, but this is of course not worth the qualification of experimental.

Anyway, I get it better now and indeed  `doh-crypto-sx`,that is in fact  dnscrypt-proxy's DoH pioneer , may come in handy should `cloudflare` fail temporarily.

EDIT: I forgot to mention that when testing servers, I uninstall dnscrypt-proxy before installing it again with the new server rather than restarting the service because I believe uninstalling cleans the cache when restarting doesn't. I hope this is correct.
