### ISSUE TITLE
Negative caching TTL (RFC 2308)

### ISSUE THREAD

**Issue by twisteroidambassador** [DNSCrypt/dnscrypt-proxy#352]
Looks like the current behavior of caching negative results is to always use a fixed TTL, as configured in `cache_neg_ttl`.

It would be nice if the TTL can be determined according to [RFC 2308 - Negative Caching of DNS Queries (DNS NCACHE)](https://tools.ietf.org/html/rfc2308), using the MINIMUM field in SOA records. Many domains have an actual negative TTL set to much longer than 60 seconds, so implementing this should reduce the number of queries that have to be sent upstream.

**Comment by jedisct1** [comment]
RFC 2308 is broken by design due to the SOA TTLs not being decreased by caching resolvers unlike RR TTLs.

When multiple caches are chained, which is always the case with `dnscrypt-proxy`, a negative response will always be cached way longer than expected.

`dnscrypt-proxy` can also use multiple servers simultaneously. If only due to qname minimization, we had many reports of names returning `NXDOMAIN` with a resolver, and returning a proper RRSET with another. 

Having a fixed, reasonable value for the negative TTL may lead to sending additional queries, but reduces the number of "it doesn't work" complains.

This can be tuneable, though. Maybe we should respect RFC 2308, but provide `min` and `max` properties to force it to be within a range. Is it something you can implement?

**Comment by twisteroidambassador** [comment]
Interesting, I did not know that peculiarity about SOA TTLs, and it does make sense to use a short TTL in that case.

> Is it something you can implement?

Probably not, unfortunately. My lack of knowledge in golang is only the first obstacle. :-/
