### ISSUE TITLE
[CYCLE ERROR] v2.0.9 - Service installation (Windows)

### ISSUE THREAD

**Issue by iWARR** [DNSCrypt/dnscrypt-proxy#353]
Great Changelist. But, unfortunately, I can't try it.

During Service installation `service-install.bat` - cmd window goes to unstoppable cycle error, splashing on the screen and loosing system control. Only Ctrl+Alt+Del & ShutDown helps. Don't know, if you familiar, how virus activity looked on Windows 3.11 or Windows 95, but it's alike. "Hello from 90-s" :)

I have run the *.bat from the "FAR manager", so I can report about error code. I've write it on the paper regardless splashing screen, so some symbols may being lost/wrong.
```

ECHO Elevated priviledges are temporary required, just to register or remove the dnscrypt-proxy service

MHTA "java script: var shell = new ActiveXObject ('shell.application'); shell.ShellExecute ('%~nx0', '', '', 'runas', 1); close ();"

EXIT

@ECHO OF & SETLOCAL ENABLEEXTENTIONS
CD /d %~dp0
SFC 2>&1 | FIND /i "/SCANNOW" >NULL : IF ERRORLEVEL 1 GOTO : ELEVATE
GOTO : ADMINTASKS
: ELEVATE
```
Next info is about usual "succssesful" installation of the dnscrypt-proxy :)

**Comment by jedisct1** [comment]
Any idea @B00ze64 @mazesy?

Maybe reintroduce e20c980b1540bc1220f65e192b7074693d4453bc that was removed with db837204dadf1d3ddb210ca049df708c0b5a594b ?

**Comment by iWARR** [comment]
@jedisct1 Unfortunately, I didn't tried last betas. Updated from stable v2.0.8
But if you tell me, the beta version, I can replace only *.bat files and make a test.

**Comment by ghost** [comment]
On Windows, OK
I have no idea if what I had experienced with the default _service-install.bat_ was similar in cause but I know it was similar in effects: cmd window going into an unstoppable cycle error, I presumed then it was related to the _MSHTA_ command in the context of my Windows 7 settings considering I had modified several registry entries.

What I know is that dnscrypt-proxy -- all 2.x versions -- run fine, excellently, with modified -install, -restart and -uninstall .bat files as follows, that I have as well installed an application called _DNSJumper_ which can be called from a command-line and therefor which I include when installing/uninstalling dnscrypt-proxy:

**service-install.bat**
```
@echo off
cmd.exe /c "dnscrypt-proxy.exe -service install"
cmd.exe /c "dnscrypt-proxy.exe -service start"
cmd.exe /c "c:\Program Files (x86)\DnsJumper\DnsJumper.exe" 127.0.0.1
```
As soon as dnscrypt-proxy is started dnsjumper switches Windows DNS to 127.0.0.1

**service-restart.bat**
```
@echo off
cmd.exe /c "dnscrypt-proxy.exe -service restart"
```

**service-uninstall.bat**
```
@echo off
cmd.exe /c "c:\Program Files (x86)\DnsJumper\DnsJumper.exe" 9.9.9.9,149.112.112.112
cmd.exe /c "dnscrypt-proxy.exe -service stop"
cmd.exe /c "dnscrypt-proxy.exe -service uninstall"
```

dnsjumper switches Windows DNS to my choice (here Quad9) before uninstalling dnscrypt-proxy

All this works fine. I have _UAC_ disabled here on Win7 so elevated privilege is not concerned.
I also have disabled _Windows Script Host_, if this may be of any concern in the issue.

From there on, this is home-made medicine and doesn't explain why the default -install.bat produced the same issue here as @iWARR described.

**Comment by iWARR** [comment]
@jedisct1 

May be this Doc will help you organize Windows Service installing in the correct way.
It's not about GO! , it's for `.NET`, but you may have a look at the overall principle.

**Walkthrough: Creating a Windows Service Application in the Component Designer**
https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer

P.S. No mention, if it can be helpful for GO! ...

**Comment by iWARR** [comment]
Also, you may discover an alternative way: will `PowerShell` commands become a workaround instead of `cmd` commands...

**Comment by ghost** [comment]
Using `PowerShell` to process a simple install/uninstall application seems to me similar as wearing a dinner jacket when going to a party: too much. Not to mention that `PowerShell` is limited/disabled by many users for security purpose. Plain .bat files with cmd seem to be just the right thing.

My credo, for what it's worth is : avoid scripting when you can perform the task without it.
For instance, the number of scripts available at GreasyFork which perform tasks which could be easily accomplished with a simple css is amazing. No point in taking Valium when a herb tea can do it as well, without side-effects. Sorry for the analogies.

**Comment by iWARR** [comment]
@mazesy 

> seems to me similar as wearing a dinner jacket when going to a party

What weighs, it is sitting well :) After Valium, nobody will care :))))

**Comment by ghost** [comment]
@iWARR 

> What weighs, it is sitting well :) 

That's not negotiable, indeed!
Better to wear a dinner jacket and sit well than wear a cool outfit and be exaggeratedly cool in our behavior! But why choose when no incompatibilities in view? Maybe to set priorities and, I agree, the first priority is respect.

> After Valium, nobody will care :))))

Bodies care :=) 

The idea is that overdoing it is part of the radical approach of things, when less is always preferable when less is enough. That's what I had in mind!

**Comment by iWARR** [comment]
@mazesy If you read carefully, I said "**alternative**". I don't argufy. Take it easy.
At least, a few last stable releases have some issues during the Windows Service installation.
Our Author create a lot of magic, so I beleive, this task will also be resolved anyway and in the most correct way. What I can remember from previous experience - manual **cmd** `SC` command (from Admin), for example, for deletion of the stucked service (in very old versions) worked like a charm.

**Comment by ghost** [comment]
@iWARR ,

> If you read carefully, I said "alternative". I don't argufy. Take it easy.

No rush, I would have replied the same without you conditioning your proposal as an alternative, I was referring to the proposal itself, not to the idea you'd suggest it as the best or the worst!  1+1=2 independently of anyone saying it's true or not, right?!

**Comment by iWARR** [comment]
@mazesy

1+1=2 = ~100% of proof for this rare and specific issue on Windows. Thankfully 1+1, nice it was found and confirmed fast, because it's too critical for system well-being.

P.S. It's time for herbal tea :) "Common Barby, let's go party (C)" :)))

**Comment by ghost** [comment]
The example was intentionally aimed at consensus (even if some might argue that 1+1=11!).

We're far from code here. I meant to say that arguing of an hypothesis can and should be done independently of the person proposing it. Nowadays there seems to be a persecution feeling spreading all around, as if debating would concern persons saying things rather than the things themselves, maybe explained by the fact that an audience -- not to mention the masses on social Web -- are inclined to believe the truth is that of the strongest opponent and not that of the strongest argument.

I apologize for digressions, especially that once you start digressing the digression is likely to inflate : we may be and we are concerned by a site's, a thread's, a post's specific, it happens that, one idea leading to another we may slip.

If anything good, understanding each other is a common value to all topics. And that very point is becoming problematic nowadays. Language barriers but not only, misconceived arguments but not only, lack of explanation and of logic but not only : lack of words, lack of semantic logic, lack of effort required to consider the other's level to adapt our explanation. This is wider than any topic because relevant of all.

Back to code!

**Comment by B00ze64** [comment]
Good day.

@jedisct1 I ran the script several times and had no issues with looping. I did get an error about being unable to remove the _event log something_ (not surprising since I do not have event log logging enabled) but was unable to reproduce the error. I do have VBScript to elevate a command script, but it requires creating a small VBS file in %TEMP% so I much prefer using your inline HTA (EDIT: I also have a neat little tool called ELE from the WinAero guy, which elevates without prompting at all, but I'd be hesitant to rely on a 3rd party tool.)

@iWARR Can you add "PAUSE" here and there in the script, and remove the "@ECHO OFF &" at the beginning (leave the SETLOCAL). Pause at the beginning of ELEVATE (next line after :ELEVATE label,) and also at the beginning of ADMINTASKS, and then after Service Install and after Service Start. This might give us a clue as to where it starts looping. If you see for example that it NEVER reaches ADMINTASKS and always goes back to ELEVATE then we'll know that some windows installations have issues with the HTA. **EDIT:** You say the "Next info is about usual successful installation of the dnscrypt-proxy" but it should not say anything at all, installation doesn't say anything except "Press Return To End" - at least on my Windows 7. And if it loops, how can it ever "end" and say successful? Can you clarify?

@mazesy Until iWARR brings back some more information I'm not ready to say that the proxy itself makes the script loop and that it needs an extra command interpreter started with CMD /C. As the script is written, the proxy can fail all it wants, it should not spawn another execution of the script. I think you fixed your bug simply by removing the HTA, and that you should find your script runs just as good without using CMD /C. But there's nothing preventing @iWARR from replacing the 2 proxy calls with CMD /C and reporting back here.

Best Regards,

**Comment by iWARR** [comment]
@B00ze64 

>  if it loops, how can it ever "end"

You are absolutely right. In the "FAR" I was occasinally able just see "relative" error code in separate FAR window. It was a small "luck" to report, what about the error is and nothing more. This is not a proof of completed scenario, of course.

If you give me a new *.bat code here as it should be, on your opinion, I can copy-pase and test it. Just publish it right here. It's pretty short.

**Comment by iWARR** [comment]
I want to note, that *.bat file from v2.0.8 is able provide successfully installation for the v2.0.9 pack, as usual. Other *.bat files from v2.0.8 are fine also.

Whitelist works nice, I'm happy it was implemented at last. Thank you, **jedisct1**.

**Comment by ingber** [comment]
iWARR:

2.0.9 works fine on my x64 Ubuntu VPS, but fails as did yours on Windows x64.  Your solution on Windows works fine.

Thanks.

Lester

**Comment by jedisct1** [comment]
If any of you could send a pull requests with what has to be changed, that would be great!

**Comment by iWARR** [comment]
Same loop issue on v2.0.10. Solution of using `*.bat`-files from v2.0.8 still works.

@jedisct1 

I've created ISSUE #369 as Pull request, because I've experienced some troubles opening "Pull request".
Sorry for that. May be I don't know, how to do it in a correct way.
Or move it this "Issue" to "Pull request" section.

Please, excuse me for my English, if any... I've done it as I can...
Feel free fixing my sentences as you wish (I don't know, if you can change other user's posts on GitHub.
Or I can fix that request by myself, if you say me, how it should look.

**Comment by jedisct1** [comment]
Redundant with #369

**Comment by Tremerix** [comment]
So it looks like current elevation check using SFC didn't work for @iWARR for some reason, because the elevation itself is the same between v2.0.8 and v2.0.9.

The proper way of checking the elevation state would be using `whoami` system tool to find out the current Integrity Level (IL) and compare it to High IL (which is the default IL after UAC elevation and the actual thing we need here):
```cmd
whoami /groups | find "S-1-16-12288" >nul && goto :AdminTasks
```
`S-1-16-12288` is the [well-known constant SID for High IL](https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems).

---

Also, please never do scripting like the current one with infinite recursion. Always check first whether you already started a new instance and put a fallback. E.g. by checking a command-line argument before the elevation:
```cmd
:elevate
if "%~1"=="RunAsAdmin" goto :error
```
along with passing it in the elevated call:
```javascript
shell.ShellExecute('%~nx0', 'RunAsAdmin', '', 'runas', 1);
```

---

There are more problems.

Full path to our batch file may contain "bad" characters.

Windows till 10 still has a bug because of which by default you can't run as administrator a batch file containing special characters in its name _or in the path_ to it. This is because the "open" verb command resolves to `cmd.exe /c ""<path to batch file>" <arguments>"`, whereas the "runas" verb (used for running as admin) command is `cmd.exe /C "<path>" <arguments>` — so MS missed the second pair of enclosing quotes, which cmd needs. Btw one can fix it in his Windows in "runas" command registry key for "cmdfile".

To fix it without touching the user registry, we should manually run cmd the right way, so we should use the full path to our file. Which we can't just paste in HTA one-liner as a CMD reference, we should prepare it first to escape (double) all backslashes... But then one can have an apostrophe in his path and he'll encounter a JS error.

So I think the best way would be completely get away from popuping up HTA and use another technique of combining CMD batch code and JScript code in one file (using multiline comments and conditional compilation). Here is my version:

<details><summary><b>Click here to see an example</b></summary><p>

```cmd
@set @_cmd=1 /*
@echo off
setlocal EnableExtensions
title DNSCrypt-Proxy
pushd "%~dp0"

whoami /groups | find "S-1-16-12288" >nul && goto :admin
if "%~1"=="RunAsAdmin" goto :error

echo Requesting privileges elevation for managing the dnscrypt-proxy service . . .
cscript /nologo /e:javascript "%~f0" || goto :error
popd & exit /b

:error
echo.
echo Error: Administrator privileges elevation failed,
echo        please manually run this script as administrator.
echo.
goto :end

:admin
dnscrypt-proxy.exe -service install
dnscrypt-proxy.exe -service start

echo.
echo Thank you for using DNSCrypt-Proxy!

:end
set /p =Press [Enter] to exit . . .
popd & exit /b */

// JScript, restart batch script as administrator
var objShell = WScript.CreateObject('Shell.Application');
var ComSpec = WScript.CreateObject('WScript.Shell').ExpandEnvironmentStrings('%ComSpec%');
objShell.ShellExecute(ComSpec, '/c ""' + WScript.ScriptFullName + '" RunAsAdmin"', '', 'runas', 1);


```

</p></details>
<br/>
Besides the above-mentioned it is also using:

- `pushd` & `popd` to restore a user current dir;
- `exit /b` to prevent closing user console window if the user opened it himself e.g. to check for possible errors, and to prevent exiting from any parent batch script;
- `"%~dp0"` must be placed in quotes for "bad" characters in path.
