### ISSUE TITLE
make a couple of  [ server_names / listen_addresses] inside the same conf

### ISSUE THREAD

**Issue by Mannitou** [DNSCrypt/dnscrypt-proxy#368]
Hi,

Can we have a way to start only 1 dnscrypt-proxy for a multi couple of [ server_names / listen_addresses] ?

Thank you,

mannitou

**Comment by jedisct1** [comment]
Hi Mannitou,

Not really. You need to start multiple instances with different configuration files in order to achieve that.

Supporting this would be an edge case, and even then, would be incomplete. For a given local address, you may want to use a specific set of resolvers, but also different blocking rules, cloaking, log files, and so on.

That would introduce quite a lot of unneeded complexity both in the code and the configuration file.

OTOH, spawning multiple instances inherently supports all of this, and the overhead is not that big since most memory pages will be shared anyway.
