### ISSUE TITLE
Feature Request: Remove blacklisted entries from the query log

### ISSUE THREAD

**Issue by late-latte** [DNSCrypt/dnscrypt-proxy#413]
Hi,

Thanks for actively developing this. Well, it's really just to ease up administrating blacklisting and whitelisting. I want to check query.log once in a while to see what new trackers or analytics needed to be blocked. I suppose I can easily global blacklist all and work on whitelisting bit by bit if I'm the only user, but it's too much a hassle for other non-admin users and managing their needs. I had it in mind that those entries specifically blacklisted are to be included in blacklisted.log and whitelisted whitelisted.log, while the unspecified remnants in query.log (or other newly-defined logging, successful_query.log maybe?). Is it possible?

**Comment by jedisct1** [comment]
Hi,

Unfortunately, that sounds quite complicated to do due to IP blocking.

Queries are logged when they are received, so that they are logged even if a response is not received, which is usually what you want.

But when IP addresses are being blocked, the IP is not known when the query is received. Only when a response it received. So, entries would have to be "removed" from the log when this happens, which is not very practical. Or queries would have to be logged after a response is received when such an option would be enabled. That would introduce a lot of complexity.

So I think the best way to achieve that remains to post-process the logs to remove `blocked.log` entries from `query.log`.
