### ISSUE TITLE
Unified link for the 'latest' dnscrypt-proxy2 pre-built binary for specific architecture

### ISSUE THREAD

**Issue by drew1kun** [DNSCrypt/dnscrypt-proxy#419]
This is a question or maybe kind of a feature request.

Is there any link which can be used in automation scripts in order to always get latest dnscrypt-proxy2 pre-build binary for specified system arch?

As dnscrypt-proxy2 is an amazing project, which actively updates, this would help to automate tests and updates.

**Comment by jedisct1** [comment]
I don't think Github provides a stable link for this, but Algo VPN seems to use `https://api.github.com/repos/jedisct1/dnscrypt-proxy/releases/latest` in order to retrieve the file names of the latest version, and then downloads this: https://github.com/trailofbits/algo/blob/e01e82b1c30bfea2d28c7c85f1e05b67c75f58f8/roles/dns_encryption/tasks/freebsd.yml

**Comment by drew1kun** [comment]
That seems like exactly what I needed! Thank you!
