### ISSUE TITLE
 [Question] Documentation on stamps and multiple instances

### ISSUE THREAD

**Issue by Snapy** [DNSCrypt/dnscrypt-proxy#423]
I was reading the documentation and a few questions popped in my mind.
1. There is documentation about [Plain](https://github.com/jedisct1/dnscrypt-proxy/wiki/stamps#plain-dns-stamps) and [DNS-over-TLS](https://github.com/jedisct1/dnscrypt-proxy/wiki/stamps#dns-over-tls-stamps) stamps.
    - Does dnscrypt-proxy support DoT ? Plain DNS ? Or is it just for convenience (and the added value of all dnscrypt-proxy's features?
2. I wanted to setup multiple instances as suggested in other issues (#311, #368 or #415) but I can't find any instructions.
    - How to do that ?

**Comment by jedisct1** [comment]
Hi Snapy!

DNS Stamps can be used by other applications. They haven't been designed to be only used by dnscrypt-proxy. In fact, the code to read and write them is not part of dnscrypt-proxy any more, it's another project added as a dependency.
So, these other protocols have just been documented so that people who want to use them can do so and share a common format.

The `-config` command-line option let you chose the configuration file you want. So, if you want to run multiple instances, use different config files, and provide their respective path with the `-config` option.

**Comment by Snapy** [comment]
I've been trying but I don't know what I'm missing.
Do I need to install dsncrypt-proxy twice (under a different name) ?
What is the most straightforward way to have two instances running, one on 127.0.0.1 and the second on 127.0.0.2 ?

**Comment by jedisct1** [comment]
No, only once. But start it twice.

You didn't mention what your operating system was.

**Comment by Snapy** [comment]
I'm on macOS 10.11.6.
