### ISSUE TITLE
Arch 2.04.14-2 will not start on reboot

### ISSUE THREAD

**Issue by n3vae** [DNSCrypt/dnscrypt-proxy#463]
After getting update for 2.04.14-2 dnscrypt-proxy will not start on reboot.  Must manually start.  remove dnscrypt-proxy 2.04.14-2 and reinstall dnscrypt-proxy 2.04.14-1 and starts automatically on reboot.

**Comment by ghost** [comment]
What's the output of: `systemctl status dnscrypt-proxy.service` and `systemctl status dnscrypt-proxy.socket`? Also it's recommended to report distro packaging issues to distro packagers, see https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-ArchLinux

**Comment by n3vae** [comment]
dnscrypt-proxy.socket - DNSCrypt-proxy socket
 Loaded: loaded (usr/lib/systemd/system/dnscrypt-proxy.socket; enabled; vendor preset: disabled
 Active: failed (Result: service-start-limit-hit) since Tue 2018-05-22 07:45:32 EDT; 5min ago
     Docs: https://github.comjedisct1/dnscrypt-proxy/wiki
 Listen: 127.0.0.1:53 (Stream)
             127.0.0.1:53 (Datagram)

May 22 07:44:37 Linux-Laptop systemd[1]:  dnscrypt-proxy.socket:  TCP_DEFER_ACCEPT failed: Protocol not available
May 22 07:44:37 Linux-Laptop systems[1]:  dnscrypt-proxy.socket:  TCP_NODELAY failed:  Protocol not available
May 22 07:44:37 Linux-Laptop systems[1]  Listening on DNSCrypt-proxy socket.
May 22 07:45:32 Linux-Laptop systems[1]  dnscrypt-proxy.socket: Failed with result ‘service-start-limit-hit’.

Sorry I am copying this from my linux laptop to my Mac. There was a red dot in front of the very first line.

**Comment by n3vae** [comment]
I can send on my other laptop that I rolled back to dnscrypt-proxy 2.04.14-1 X-64.  To laptops one KDE that I sent you the fail and the one I rolled back is Gnome.

**Comment by ghost** [comment]
You may try:
```
systemctl disable dnscrypt-proxy.socket
systemctl enable dnscrypt-proxy.service
```
then reboot and see if it helped.

**Comment by s7bc** [comment]
After running the system, dnscrypt works.
But when connecting to the Internet by
dhcpcd enp0s20u10
dnscrypt is down and has to be restarted
systemctl restart dnscrypt-proxy.service

SOCKET
[Unit]
Description=DNSCrypt-proxy socket
Documentation=https://github.com/jedisct1/dnscrypt-proxy/wiki
Before=nss-lookup.target
Wants=nss-lookup.target network-online.target

[Socket]
ListenStream=127.0.0.1:53
ListenDatagram=127.0.0.1:53
NoDelay=true
DeferAcceptSec=1

[Install]
WantedBy=sockets.target

SERVICE
[Unit]
Description=DNSCrypt-proxy client
Documentation=https://github.com/jedisct1/dnscrypt-proxy/wiki
After=network.target
Wants=network-online.target nss-lookup.target
Before=nss-lookup.target

[Service]
NonBlocking=true
ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
DynamicUser=yes
CacheDirectory=dnscrypt-proxy
LogsDirectory=dnscrypt-proxy
RuntimeDirectory=dnscrypt-proxy
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

**Comment by s7bc** [comment]
systemctl enable --now dnscrypt-proxy.socket
Created symlink /etc/systemd/system/sockets.target.wants/dnscrypt-proxy.socket → /usr/lib/systemd/system/dnscrypt-proxy.socket.
Job for dnscrypt-proxy.socket failed.
See "systemctl status dnscrypt-proxy.socket" and "journalctl -xe" for details.

**Comment by tazer4** [comment]
The problem on archlinux is since the latest two releases the dnscrypt-proxy.service has been changed to not include the socket file, so those using socket activation which was default before will stop working after update. It can be fixed by modifying it or replacing it with the one from 2 releases ago.

/usr/lib/systemd/system/dnscrypt-proxy.service
**New bad dnscrypt-proxy.service:**

[Unit]
Description=DNSCrypt-proxy client
Documentation=https://github.com/jedisct1/dnscrypt-proxy/wiki
Wants=network-online.target nss-lookup.target
Before=nss-lookup.target

[Service]
NonBlocking=true
ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
DynamicUser=yes
CacheDirectory=dnscrypt-proxy
LogsDirectory=dnscrypt-proxy
RuntimeDirectory=dnscrypt-proxy
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target



**Old good service, replace with this:**
##########################################################
[Unit]
Description=DNSCrypt-proxy client
Documentation=https://github.com/jedisct1/dnscrypt-proxy/wiki
Requires=dnscrypt-proxy.socket
After=network-online.target
Wants=network-online.target
Before=nss-lookup.target
Wants=nss-lookup.target

[Service]
NonBlocking=true
ExecStart=/usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
DynamicUser=yes
CacheDirectory=dnscrypt-proxy
LogsDirectory=dnscrypt-proxy
RuntimeDirectory=dnscrypt-proxy

[Install]
Also=dnscrypt-proxy.socket
WantedBy=multi-user.target

##########################################################

Then do: # systemctl daemon-reload && systemctl stop dnscrypt-proxy.socket && systemctl stop dnscrypt-proxy.service && systemctl start dnscrypt-proxy

**Comment by ghost** [comment]
Does disabling socket and enabling service helped or not? Anyway you should report it to Archlinux as this isn't related to upstream code.

**Comment by frhgit** [comment]
Add the line below in /usr/lib/systemd/system/dnscrypt-proxy.service 
`Requires=dnscrypt-proxy.socket`

I have put it just below 
`[Unit]`
`Description=DNSCrypt-proxy client`
`Documentation=https://github.com/jedisct1/dnscrypt-proxy/wiki`

Restart systemd with `systemctl daemon-reload` and dnscrypt-proxy service with `systemctl restart dnscrypt-proxy`

**Comment by s7bc** [comment]
No.
this does not work.
service can not start

**Comment by frhgit** [comment]
I have done it succesfully 30 min ago.
Without any error message, I can not help you more.

**Comment by s7bc** [comment]
please show full text
your system - archlinux ?

**Comment by ghost** [comment]
@ljgdasfhk please show the output of:
```
systemctl status dnscrypt-proxy.service
systemctl status dnscrypt-proxy.socket
journalctl -r -u dnscrypt-proxy.service
journalctl -r -u dnscrypt-proxy.socket
```
Also please test if https://github.com/jedisct1/dnscrypt-proxy/issues/463#issuecomment-391065039 works for you.

**Comment by s7bc** [comment]
downgrade dnscrypt-proxy
to dnscrypt-proxy-2.0.14-1-x86_64.pkg.tar.xz
and now all work fine

**Comment by s7bc** [comment]
I'll check it in 2 hours on another same machine

**Comment by s7bc** [comment]
systemctl status dnscrypt-proxy.service
● dnscrypt-proxy.service - DNSCrypt-proxy client
   Loaded: loaded (/usr/lib/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-05-23 18:19:50 MSK; 49min ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
 Main PID: 6220 (dnscrypt-proxy)
    Tasks: 17 (limit: 4915)
   Memory: 15.1M
   CGroup: /system.slice/dnscrypt-proxy.service
           └─6220 /usr/bin/dnscrypt-proxy --config /etc/dnscrypt-proxy/dnscrypt-proxy.toml

мая 23 18:20:01 computer dnscrypt-proxy[6220]: [publicarray-au2] OK (crypto v2) - rtt: 329ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [publicarray-au-doh] OK (DoH) - rtt: 331ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [qualityology.com] OK (crypto v2) - rtt: 190ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [scaleway-fr] OK (crypto v2) - rtt: 66ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [securedns] OK (crypto v1) - rtt: 64ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [soltysiak] OK (crypto v1) - rtt: 71ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [trashvpn] OK (crypto v2) - rtt: 54ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [ventricle.us] OK (crypto v2) - rtt: 136ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: Server with the lowest initial latency: cpunks-ru (r>
мая 23 18:20:03 computer dnscrypt-proxy[6220]: dnscrypt-proxy is ready - live servers: 31

systemctl status dnscrypt-proxy.socket
● dnscrypt-proxy.socket - DNSCrypt-proxy socket
   Loaded: loaded (/usr/lib/systemd/system/dnscrypt-proxy.socket; enabled; vendor preset: disabled)
   Active: failed (Result: service-start-limit-hit) since Wed 2018-05-23 07:19:08 MSK; 11h ago
     Docs: https://github.com/jedisct1/dnscrypt-proxy/wiki
   Listen: 127.0.0.1:53 (Stream)
           127.0.0.1:53 (Datagram)

мая 23 07:18:37 computer systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available
мая 23 07:18:37 computer systemd[1]: Listening on DNSCrypt-proxy socket.
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.socket: Failed with result 'service-start-limit-hit'.

**Comment by s7bc** [comment]
journalctl -r -u dnscrypt-proxy.service
-- Logs begin at Sun 2017-12-03 05:32:46 MSK, end at Wed 2018-05-23 19:10:20 MSK. --
мая 23 18:20:03 computer dnscrypt-proxy[6220]: dnscrypt-proxy is ready - live servers: 31
мая 23 18:20:03 computer dnscrypt-proxy[6220]: Server with the lowest initial latency: cpunks-ru (rtt: 10ms)
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [ventricle.us] OK (crypto v2) - rtt: 136ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [trashvpn] OK (crypto v2) - rtt: 54ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [soltysiak] OK (crypto v1) - rtt: 71ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [securedns] OK (crypto v1) - rtt: 64ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [scaleway-fr] OK (crypto v2) - rtt: 66ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [qualityology.com] OK (crypto v2) - rtt: 190ms
мая 23 18:20:03 computer dnscrypt-proxy[6220]: [publicarray-au-doh] OK (DoH) - rtt: 331ms
мая 23 18:20:01 computer dnscrypt-proxy[6220]: [publicarray-au2] OK (crypto v2) - rtt: 329ms
мая 23 18:20:00 computer dnscrypt-proxy[6220]: [publicarray-au] OK (crypto v1) - rtt: 359ms
мая 23 18:20:00 computer dnscrypt-proxy[6220]: [opennic-tumabox] TIMEOUT
мая 23 18:19:58 computer dnscrypt-proxy[6220]: [opennic-onic] OK (crypto v1) - rtt: 127ms
мая 23 18:19:58 computer dnscrypt-proxy[6220]: [opennic-luggs] OK (crypto v1) - rtt: 146ms
мая 23 18:19:58 computer dnscrypt-proxy[6220]: [ipredator] OK (crypto v1) - rtt: 35ms
мая 23 18:19:58 computer dnscrypt-proxy[6220]: [flatty.co] TIMEOUT
мая 23 18:19:56 computer dnscrypt-proxy[6220]: [fvz-anytwo] OK (crypto v1) - rtt: 68ms
мая 23 18:19:56 computer dnscrypt-proxy[6220]: [fvz-anyone] OK (crypto v1) - rtt: 78ms
мая 23 18:19:55 computer dnscrypt-proxy[6220]: [freetsa.org] OK (crypto v1) - rtt: 222ms
мая 23 18:19:55 computer dnscrypt-proxy[6220]: [ev-us3] OK (crypto v2) - rtt: 168ms
мая 23 18:19:55 computer dnscrypt-proxy[6220]: [ev-us2] OK (crypto v2) - rtt: 126ms
мая 23 18:19:55 computer dnscrypt-proxy[6220]: [ev-us] OK (crypto v2) - rtt: 181ms
мая 23 18:19:55 computer dnscrypt-proxy[6220]: [doh-crypto-sx] OK (DoH) - rtt: 121ms
мая 23 18:19:54 computer dnscrypt-proxy[6220]: [dnscrypt.nl-ns0] OK (crypto v1) - rtt: 61ms
мая 23 18:19:54 computer dnscrypt-proxy[6220]: [dnscrypt.me] OK (crypto v2) - rtt: 53ms
мая 23 18:19:54 computer dnscrypt-proxy[6220]: [dnscrypt.eu-nl] OK (crypto v1) - rtt: 66ms
мая 23 18:19:54 computer dnscrypt-proxy[6220]: [dnscrypt.eu-dk] TIMEOUT
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [dnscrypt.ca-2] OK (crypto v1) - rtt: 141ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [dnscrypt.ca-1] OK (crypto v1) - rtt: 147ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [de.dnsmaschine.net] OK (crypto v2) - rtt: 50ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [d0wn-tz-ns1] OK (crypto v1) - rtt: 185ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [d0wn-nl-ns4] OK (crypto v1) - rtt: 62ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [d0wn-is-ns2] OK (crypto v1) - rtt: 99ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [cpunks-ru] OK (crypto v1) - rtt: 10ms
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [2.dnscrypt-cert.cypherpunks.ru.] certificate is about to expire -- if you do>
мая 23 18:19:52 computer dnscrypt-proxy[6220]: [cloudflare] OK (DoH) - rtt: 40ms
мая 23 18:19:51 computer dnscrypt-proxy[6220]: [arvind-io] OK (crypto v2) - rtt: 385ms
мая 23 18:19:51 computer dnscrypt-proxy[6220]: Now listening to [::1]:53 [TCP]
мая 23 18:19:51 computer dnscrypt-proxy[6220]: Now listening to [::1]:53 [UDP]
мая 23 18:19:51 computer dnscrypt-proxy[6220]: Now listening to 127.0.0.1:53 [TCP]
мая 23 18:19:51 computer dnscrypt-proxy[6220]: Now listening to 127.0.0.1:53 [UDP]
мая 23 18:19:51 computer dnscrypt-proxy[6220]: dnscrypt-proxy 2.0.14
мая 23 18:19:51 computer dnscrypt-proxy[6220]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 18:19:50 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:19:08 computer systemd[1]: Failed to start DNSCrypt-proxy client.
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.service: Start request repeated too quickly.
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:19:08 computer dnscrypt-proxy[2922]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:19:08 computer dnscrypt-proxy[2922]: dnscrypt-proxy 2.0.14
мая 23 07:19:08 computer dnscrypt-proxy[2922]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:19:07 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:19:07 computer dnscrypt-proxy[2909]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:19:07 computer dnscrypt-proxy[2909]: dnscrypt-proxy 2.0.14
мая 23 07:19:07 computer dnscrypt-proxy[2909]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:19:07 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:19:07 computer dnscrypt-proxy[2899]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:19:07 computer dnscrypt-proxy[2899]: dnscrypt-proxy 2.0.14
мая 23 07:19:07 computer dnscrypt-proxy[2899]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:19:07 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:19:07 computer dnscrypt-proxy[2885]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:19:07 computer dnscrypt-proxy[2885]: dnscrypt-proxy 2.0.14
мая 23 07:19:07 computer dnscrypt-proxy[2885]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:19:07 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:19:07 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:19:07 computer dnscrypt-proxy[2875]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:19:07 computer dnscrypt-proxy[2875]: dnscrypt-proxy 2.0.14
мая 23 07:19:07 computer dnscrypt-proxy[2875]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:19:07 computer systemd[1]: Started DNSCrypt-proxy client.
мая 23 07:18:47 computer systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
мая 23 07:18:47 computer systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
мая 23 07:18:47 computer dnscrypt-proxy[540]: listen udp 127.0.0.1:53: bind: address already in use
мая 23 07:18:47 computer dnscrypt-proxy[540]: dnscrypt-proxy 2.0.14
мая 23 07:18:47 computer dnscrypt-proxy[540]: Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
мая 23 07:18:47 computer dnscrypt-proxy[540]: Network connectivity detected
мая 23 07:18:41 computer dnscrypt-proxy[540]: Network not available yet -- waiting...
мая 23 07:18:37 computer systemd[1]: Started DNSCrypt-proxy client.
-- Reboot --

**Comment by s7bc** [comment]
journalctl -r -u dnscrypt-proxy.socket
-- Logs begin at Sun 2017-12-03 05:32:46 MSK, end at Wed 2018-05-23 19:10:20 MSK. --
мая 23 07:19:08 computer systemd[1]: dnscrypt-proxy.socket: Failed with result 'service-start-limit-hit'.
мая 23 07:18:37 computer systemd[1]: Listening on DNSCrypt-proxy socket.
мая 23 07:18:37 computer systemd[1]: dnscrypt-proxy.socket: TCP_NODELAY failed: Protocol not available
мая 23 07:18:37 computer systemd[1]: dnscrypt-proxy.socket: TCP_DEFER_ACCEPT failed: Protocol not available
-- Reboot --

**Comment by s7bc** [comment]
systemctl disable dnscrypt-proxy.socket
systemctl stop dnscrypt-proxy.socket
reboot
That helped

**Comment by dvzrv** [comment]
@n3vae: I've updated the [wiki](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-ArchLinux) on this topic. Please make sure to **either** use socket activation **or** the service file directly (with the implied modifications to your configuration file in each case), but not both at the same time.

Since the service/socket files have been downstreamed, for Arch Linux both unix socket activation *and* plain service usage are possible (separately).
[I explicitly decoupled the service and socket](https://bugs.archlinux.org/task/58661) to enable the user to choose to user either.
This cuts down on the necessary downstream modifications on the configuration file and enables for greater flexibility.
Sorry, if this was communicated insufficiently.

@tazer4 no, that's not correct. None of the service/socket files are *good* or *bad*. They just work in different ways. Also, your implied override would by in `/etc/systemd/system/` not `/usr/lib/systemd/system/`. Please don't give advice like that.

@jedisct1 You can close this, as this is also tracked [downstream](https://bugs.archlinux.org/task/58714) and more of a documentation issue imho.

**Comment by tazer4** [comment]
@dvzrv It is bad if it suddenly stops the program from working after updating it, you should have included this information after the package updated.  Also the service file is at /usr/lib/systemd/system/dnscrypt-proxy.service, the location you provide only contains a few symlinks unrelated to dnscrypt-proxy.  I gave the correct advice on how to return it to the previous functional configuration for less advanced users.
