### ISSUE TITLE
Cloudflare .onion resolver with dnscrypt-proxy

### ISSUE THREAD

**Issue by lukateras** [DNSCrypt/dnscrypt-proxy#505]
Hello! I'd like to use dnscrypt-proxy over Tor with Cloudflare's new onion resolver: https://blog.cloudflare.com/welcome-hidden-resolver/

I've specified `proxy = "socks5://127.0.0.1:9050"` in my config and stamp I'm using is `sdns://AgcAAAAAAAAAACDrdSX4jw2UWPgamVAZv9NMuJzNyVfnsO8xXxD4l2OBGD5kbnM0dG9ycG5sZnMyaWZ1ejJzMnlmM2ZjN3JkbXNiaG02cnc3NWV1ajM1cGFjNmFwMjV6Z3FhZC5vbmlvbgovZG5zLXF1ZXJ5`. I'm on 2.0.15. Unfortunately, that doesn't work.

Is that currently possible?

**Comment by CHEF-KOCH** [comment]
You do not provide as much information as needed in order to identify if it's on your end or DNSCrypt or Cloudflare.

Ensure that the following is setup correctly:

`dnscrypt-proxy.toml`
```bash
server_names = ['cloudflare', 'cloudflare-ipv6']
```

Make sure that nothing else is running on localhost:53, and check that everything works as expected

```bash
dnscrypt-proxy -resolve cloudflare-dns.com
Resolving [cloudflare-dns.com]

Domain exists:  yes, 3 name servers found
Canonical name: cloudflare-dns.com.
IP addresses:   2400:cb00:2048:1::6810:6f19, 2400:cb00:2048:1::6810:7019, 104.16.111.25, 104.16.112.25
TXT records:    -
Resolver IP:    172.xx.xxx.xxx
```

You can also register it as system service, as explained over [here](https://github.com/jedisct1/dnscrypt-proxy/wiki/installation#installing-as-a-system-service-windows-linux-macos).

----

On the cloudflare side:
* Download the [cloudflared daemon](https://developers.cloudflare.com/argo-tunnel/downloads/). You need to bind Port 53 because it's privileged port.

```bash
sudo cloudflared proxy-dns
INFO[0000] Adding DNS upstream                           url="https://cloudflare-dns.com/dns-query"
INFO[0000] Starting metrics server                       addr="127.0.0.1:49312"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://localhost:53"
````

From the [configuration reference](https://developers.cloudflare.com/argo-tunnel/reference/config/) you want to start it on user login:
```bash
mkdir -p /usr/local/etc/cloudflared
cat << EOF > /usr/local/etc/cloudflared/config.yaml
proxy-dns: true
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query
EOF
````


Verify it's running:
```bash
dig +short @127.0.0.1 cloudflare.com AAAA
2400:cb00:2048:1::c629:d6a2
2400:cb00:2048:1::c629:d7a2
```

Rest is explained [here](https://blog.cloudflare.com/welcome-hidden-resolver/). If there additional problems then provide the logs which points to the possible problems.

**Comment by lukateras** [comment]
It is not on my end or Cloudflare's. Please see OP.

**Comment by CHEF-KOCH** [comment]
It works for me. The socks port is 9150. So we can close this since you're not provide anything useful.

**Comment by lukateras** [comment]
This is not a `cloudflared`'s issue tracker. `cloudflare` and `cloudflare-ipv6` resolvers from `public-resolvers.md` use clearnet addresses which requires an exit node. I'm asking specifically about using dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion  as a resolver specifically with DNSCrypt-Proxy 2. Try entering stamp from OP in https://dnscrypt.info/stamps/ to see what it contains.

**Comment by dwimmer** [comment]
Do you have the ignore_system_dns option set? This may work if you leave that option unset. What do you see in the log if you set the log level to 0?

**Comment by dwimmer** [comment]
I just tested this and it looks like it does work with ignore_system_dns=false.

However, you'll need to change your dns stamp to include the correct certificate hash and possibly increase the timeout setting.

You can see the certificate chain in a browser at tor.cloudflare-dns.com or use this stamp:
sdns://AgcAAAAAAAAAACC0WWFtenR5met-s8i0oiShMtYstulWSybPBq-zBUEMNT5kbnM0dG9ycG5sZnMyaWZ1ejJzMnlmM2ZjN3JkbXNiaG02cnc3NWV1ajM1cGFjNmFwMjV6Z3FhZC5vbmlvbgovZG5zLXF1ZXJ5

**Comment by lukateras** [comment]
Great, thank you! Indeed, it works with that stamp, and I had `ignore_system_dns` set to `true` which likely was part of the issue.

**Comment by dwimmer** [comment]
Glad it worked for you!
I might see what I can do about decoupling general system dns usage from .onion lookups. Ideally the ignore_system_dns setting wouldn't matter for this.
