### ISSUE TITLE
More descriptive Server_Error?

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#529]
Salut.

I regularly see server-error's in the query log file. It's not bad, but it happens. Would it be possible to be more descriptive of what these errors are when they happen? If you want to keep the query log simple to parse (i.e. SimpleDnsProxy) maybe log those errors in another log file? (errors.log)

Thanks.
Best Regards,

**Comment by jedisct1** [comment]
This is the return code we got from the upstream server. There are no other information. An error such as `SERVFAIL` can be due to that upstream having connectivity issue, to expired DNSSEC keys, to a bad configuration, to an incorrect delegation... But there is no way to know without carefully investigating each step of the resolution from this upstream server's point of view. As a client, all we get is an empty response that says `FAIL`.

**Comment by B00ze64** [comment]
@jedisct1 Ok, understood. What happens when you get a `FAIL`? I would be interested in a retry-count setting; from the logs it does not look like you are retrying. Even better if you retry with the next best server in the list. Thank you,
