### ISSUE TITLE
Retry with next server on error?

### ISSUE THREAD

**Issue by B00ze64** [DNSCrypt/dnscrypt-proxy#540]
Good day.

I'm looking at my logs and I regularly see little "bursts" of Server_Errors, where whatever server is currently handling requests (I've tried 3 different ones) stops responding for 1 or 2 seconds. During that time, DNSCrypt might report 4 or 8 or 10 errors, before the server becomes responsive again. I'm actually surprised I haven't see any effects in client programs so far. It would be nice if DNSCryptProxy could retry using the next best server when this happens, and increase the RTT of the failing server a little.

Thank you,

**Comment by jedisct1** [comment]
The most frequent cause for `SERVER_ERROR` is a timeout. Clients automatically retry when this happens, which is why you rarely see implications in actual applications despite of what these errors being written to the proxy log file.

There might be two reasons for a timeout.

Authoritative servers for a given domain can be slow. The response will eventually come, but `dnscrypt-proxy`'s timeout is shorter. It doesn't help to make it longer, because clients have a timeout, too, and will ignore any response past it (actually, this is worse than just ignoring the response, as it will trigger a network error).
But after a retry, or a few retries *sent to the same server* the response will have been received by the upstream server, will have been cached, so you will get it.

*sent to the same server* is important. Suppose a domain has slow authoritative servers, that respond slower than the client timeout. If you send the same query to different servers, them will all fail the same way, since the timeout is not on their end, but on the authoritative servers they need to contact.

Another reason you may get a timeout is that a resolver is down, or has load or connectivity issues (including to some authoritative servers). In that case, it makes sense to try a different server.

A way to deal with both situations is to randomly send queries to the 2 "best" servers, and still slightly increase the RTT after a timeout. Which, incidentally, is exactly what the default strategy, p2, does.

**Comment by B00ze64** [comment]
Hi.

Ah yes, DNS servers ask upstream until they hit the respective domain's DNS server if no one has the result in cache, so it may take time to get a response from there, and asking repeatedly different DNS servers will not help, they will all timeout the same, you are right. Nice to see you are already increasing RTT when a timeout occurs, guess there is nothing else to do, DNSCryptProxy already deals with this correctly.

I'm not sure where the problem lies when I get `SERVER_ERROR`, but it seems to happen in little bursts. It does not happen very often now that I've added CloudFlare again - DNSCrypt-CA might be overloaded. I do see the client programs retrying, but most of the time they seem to stop trying before they get a correct response. Example:

```
[2018-07-06 21:22:47]	127.0.0.1	safebrowsing-cache.google.com	A	PASS
[2018-07-06 21:22:49]	127.0.0.1	safebrowsing.cache.l.google.com	A	SERVER_ERROR
[2018-07-06 21:22:50]	127.0.0.1	safebrowsing.cache.l.google.com	A	SERVER_ERROR
[2018-07-06 21:23:15]	127.0.0.1	www.youtube.com	A	SERVER_ERROR
[2018-07-06 21:23:16]	127.0.0.1	www.youtube.com	A	SERVER_ERROR
[2018-07-06 21:23:16]	127.0.0.1	youtube-ui.l.google.com	A	SERVER_ERROR
[2018-07-06 21:23:17]	127.0.0.1	youtube-ui.l.google.com	A	SERVER_ERROR
[2018-07-06 21:23:39]	127.0.0.1	outlook.office365.com	A	PASS
```

In this example, Google DNS seems to be having problems. The client retried twice, but no more, and each time, I do not see a valid response afterwards, it just stops with one last `SERVER_ERROR`. Strangely, I do not recall having issues reaching YouTube.

Maybe I should increase DNSCryptProxy's cache size, or TTL for cached entries? I had a look at the getMinTTL function; apparently the time to cache an entry is dictated by the server answering the query? Maybe I should increase CacheMinTTL? 10 minutes seems a bit low?

Thanks.

**Comment by jedisct1** [comment]
Increasing `CacheMinTTL` can definitely help.

Another thing that could be done is serve cached responses from the cache even if they are a little bit expired when the resolver temporarily returns an error.

It's trivial to do and shouldn't take more than 5 lines of code to implement. The only issue here is that like most trivial ideas, there are patents ([1](https://patents.google.com/patent/US8583801)) - ([2](https://patents.google.com/patent/US8676989B2)) describing this :(

**Comment by B00ze64** [comment]
Good day.

Wow, they basically patented "a dns cache." Software patents are a real problem.

Well, I've increased cache size to 2048, and minTTL to 12 hours (yeah, really high; it will bite me one day) but it has not really prevented little errors from popping-up now and again. I'm going to try a 4s timeout and a bigger TTL (yup, anyone changes their web server's address and I'll be in trouble.)

I do see something strange tho:

```
[2018-07-17 18:53:10]	127.0.0.1	crl.microsoft.com	A	PASS
[2018-07-17 18:53:12]	127.0.0.1	crl.microsoft.com	A	SERVER_ERROR
```
Shouldn't that have been cached? It error'ed out 2 seconds after getting a good response which should've been added to the cache...

Regards,

**Comment by B00ze64** [comment]
Good day.

Well a bigger timeout definitively helps; not sure if the bigger cache and MinTTL are also really helping. I'm going to close.

Thank you.
