### ISSUE TITLE
Questions for GUI: syntax and semantics of config files?

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#554]
About 1.5 months ago I started writing code for a GUI and told you guys I would update. I am adding finishing touches on the config file syntax analysing modules. I have a few question:

If a key-value pair has no semantic meaning in the config file does the system crash? Either if there is no defined key by that name or the value assigned to it is of an invalid type?

Will the data types or syntactic structure of a config file change in a major way in the future? I don't mean something as trivial as adding or removing keys, but something that implies a change of grammar of the language.

Once I finish the parser I will start working on the GUI.

**Comment by jedisct1** [comment]
Hi!

If the syntax is not correct, the proxy won't start rather than starting with an unpredicable configuration.

What you can do is use the `-check` command-line flag to check that the configuration file is correct without actually starting the service.

Backwards-compatibility is very important. Configuration parameters are unlikely to change in a breaking way. Even when a new feature that overlaps with an old one is introduced, the previous one is still supported, even if not documented any more.
