### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ci70** [DNSCrypt/dnscrypt-proxy#564]
Provide multiple DNS caching servers like Acrylic DNS Proxy does.

**Comment by jedisct1** [comment]
I'm not familiar with Acrylic DNS Proxy.

Can you clarify?

**Comment by ci70** [comment]
Here it is.
https://mayakron.altervista.org/wikibase/show.php?id=AcrylicFAQ

**Comment by jedisct1** [comment]
Thanks for spotting this website with completely obsolete information regarding DNSCrypt.

Since this is apparently a wiki, maybe you can directly update these information?

If not, since you are familiar with this project, can you tell the wiki maintainers what has to be updated (at least the website and instructions for dnscrypt-proxy 2.x)?

Thanks for your help!

**Comment by ci70** [comment]
Huh? Does dnscrypt support multiple dns servers for caching or not?

**Comment by jedisct1** [comment]
Yes, of course. Did you miss the [configuration](https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration) section in the documentation?

So, can you help with updating the DNSCrypt section on the link you posted? Thanks!

**Comment by jedisct1** [comment]
> So, can you help with updating the DNSCrypt section on the link you posted? Thanks!

Any progress on this?

**Comment by jedisct1** [comment]
@joeparkerz Ping. https://mayakron.altervista.org/wikibase/show.php?id=AcrylicFAQ still has outdated information. Can you try to have it updated?
