### ISSUE TITLE
Concurrent connection QPS is too low, which should not be the performance of go.

### ISSUE THREAD

**Issue by ceozero** [DNSCrypt/dnscrypt-proxy#581]
[meaningless picture deleted]

**Comment by jedisct1** [comment]
Can you please describe the issue, what you did, what happened, what was expected, and provide all the details on how to reliably reproduce it (including operating system, versions and configuration)?

Thanks in advance.

**Comment by ceozero** [comment]
I didn't do anything. I want to test the concurrent QPS capability of dnscrypt-proxy with queryperf. Has anyone ever done any tests?

**Comment by jedisct1** [comment]
In order to do performance testing on a proxy, you need to set up a dedicated server simulating the  protocol. Nothing like this exists for encrypted DNS as far as I know.

The local proxy, the transport layer, the remote proxy, its infrastructure, and upstream servers have their own limitations and restrictions. A test involving round trips through the whole chain can only estimate the performance of the whole chain. It cannot provide any indications on individual components. This requires simulation in a controlled environment.

As a practical example, my DNSCrypt proxy servers will immediately rate limit and eventually block your IP if a spike of traffic coming from the same source is detected, Google will ignore your queries after 100 queries per second, and Cloudflare enforces a low limit of in-flight queries per client. This doesn't let you measure anything about the proxy running on your end.
