### ISSUE TITLE
Usage of DNSCrypt in golang

### ISSUE THREAD

**Issue by inkeliz** [DNSCrypt/dnscrypt-proxy#588]
I don't know if already exist a library to address this question, or even if the dnscrypt-proxy can do that already. I'm asking here, since the dnscrypt-proxy is now written in golang.

My idea is create a easy replace of `net.LookupIP()`, that makes easy for developers use the dnscrypt in their own on project, even if the client itself didn't use dnscrypt-proxy. Also, the Golang has the [`Resolver`](https://golang.org/pkg/net/#Resolver), which allow set the `Dial`, I think is possible to create a custom `Conn`, but not seems too easy.

**Comment by jedisct1** [comment]
Hi!

That would be great, and I think it is totally doable based on the current code. Setting the `Resolver` `Dial` looks like the cleanest way to achieve this.

The difficult might be due to the fact that we need to keep some state, in order to avoid fetching certificates more often that required.

The `dnscrypt-proxy` code cannot do that right now, but turning it into a library can be done. Not sure that this is something I'll have time to spend on in a near future, though.

**Comment by jedisct1** [comment]
This would be really useful, but I haven't made any progress on this yet.

Adding the `timeout` tag to put it in the long-term todo list, unless you can help with it.
