### ISSUE TITLE
URLs generating HTTP 403 errors

### ISSUE THREAD

**Issue by Gitoffomalawn** [DNSCrypt/dnscrypt-proxy#590]
When trying to run the `generate-domains-blacklist.py` in the `utils` directory, many domains in the list I've added generate HTTP 403 errors. I'm assuming (I know this is dangerous) that this is related to user-agent string issues, since when I browse to those links using a browser I get to see the list as usual. Testing with a user-aget string switcher confirms that the `urllib` user-agent gets rejected by multiple websites.

Would it be possible to add something to the script to be able to change the user-agent if necessary? Or maybe just pass it a Firefox/Chrome user-agent by default?

**Comment by jedisct1** [comment]
If the maintainer of such a list explicitly wants to forbid non-browsers access, we should play by the rule instead of trying to violate the terms of use.

So, faking the user agent is not the kind of feature I'd like dnscrypt-proxy to support. If a user agent is refused, this is what the maintainer wanted.
