### ISSUE TITLE
DoH Authentication header support

### ISSUE THREAD

**Issue by Aaron-P** [DNSCrypt/dnscrypt-proxy#599]
Are there any current plans to support the sending of credentials via an authentication header for DNS-over-HTTPS queries, similar to what Firefox is doing with the network.trr.credentials setting?  It seems that it would be simple enough to add to the transport code but I'm not sure right now what a good way of passing in credentials on the config would be.  Are the server stamps an established spec or can those be added on to?  Before I explore it though I don't want to step on anyone if there's already work being done on it.

**Comment by jedisct1** [comment]
Hi!

I didn't plan to add support for user authentication, but hey, why not! And there are plenty features bit left in DNS stamps, so we can definitely use one to mention that authentication is required.

Adding user authentication opens a can of worms, though. People will immediately ask for static maps, sqlite, mysql, postgresql, oracle, ldap, and whatnot.

**Comment by Aaron-P** [comment]
The main issue I have right now is how to actually specify credentials.  It would probably need to be on a per-resolver basis, so there are only 3 methods that I can think of:

1. Insert the credentials into the stamp.  This doesn't seem like a good idea because it makes changing credentials a lot more opaque.  Though that could be a plus in the case of administrator granted stamp/credential sets.
2. Attach the credentials to the stamp via a query-string like extension.  Since the stamps are in a URI like format this doesn't seem completely out of place, but it would be the first thing this has ever been done for.
3. Have a server name to credential map someplace in the configuration.  This has the disadvantage of moving the credentials away from their associated stamps but is probably the most conservative solution.

Any thoughts?

**Comment by jedisct1** [comment]
A server to credential map sounds like the more intuitive solution.

Maybe just something like:

```toml
[ident.doh_resolver_name1]
psk = ...

[ident.doh_resolver_name2]
static_client_cert = ...

[ident.dnscrypt_resolver_name1]
seed = ...
```

**Comment by jedisct1** [comment]
I'm not a big fan of static keys, such as what you suggest for the `Authentication:` header, though.

Besides the "database has been leaked and passwords were not properly hashed" case, there is another common case that it doesn't protect against: employees. Suppose a company relies on this to provide a premium DNS service. Employees may access the customers' static keys, sell them, and/or use them even after they leave the company.

Certificate-based authentication solves this. Users can be identified using their public key, and having public keys leaked is harmless. This is easy to implement both for DNSCrypt and DoH.

The downside is that it makes it easy to map IP addresses to individual devices, even for passive observers.

Some PAKEs address this. Unfortunately, they are not widely used or implemented yet.

For DNSCrypt, this can be solved quite easily, with minor modifications to the current protocol.

The client can send `Ek(Cpk || dns_data)`, `k` being the secret derived from an exchange using an ephemeral key pair, and `Cpk` being the static client public key. Server responses are then encrypted using `Cpk` instead of the ephemeral client public key.

Attackers don't learn anything about the customer identify, and DNS operators cannot impersonate customers even by knowing `Cpk`.

For DoH, this is going to be more complicated, since client certificates are not encrypted.

**Comment by Aaron-P** [comment]
I wasn't really thinking about advanced cases like commercial use, and I also don't know much of anything about the DNSCrypt spec other than that it exists so I wasn't thinking about how that would handle authentication either.

Since DoH uses https you could theoretically use any authentication mechanism that http or tls supports, except for possibly sending some token in POST bodies since the way they send data for DoH post requests is a binary blob rather than a key-value set.  I'm not sure if the DNS wire data sent in those requests can have extra stuff tacked on.

The simplest mechanism in http is basic auth, and though it does have potential downsides in advanced cases as you pointed out, I'm not sure if not being a perfect solution for all possible use cases is a serious enough issue to not implement anything at all.  The whole 'perfect being the enemy of good enough'.

**Comment by jedisct1** [comment]
Closing, but keeping in the list of things to eventually implement.
