### ISSUE TITLE
Typo in dnscrypt-proxy.toml

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#61]
Typo in [dnscrypt-proxy.toml](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/dnscrypt-proxy.toml#L275): toserver --> to server

Regards and all the best with this awesome and very promising new project.

**Comment by phonphen** [comment]
i think, this is typo in dnscrypt-proxy.toml too
or maybe i am wrong

`fallback_resolver = "9.9.9.9:53"`

its should

`fallback_resolver = '9.9.9.9:53'`

**Comment by jedisct1** [comment]
@glitsj16 Good catch, thanks!

@phonphen Double quotes are fine and way more common. Single quotes are actually very annoying since you can't even easily include text with `'` characters in them.

The reason single quotes were chosen is to allow path names to use `\` instead of `/` as a separator on Windows.

Anyway, for consistency, the `fallback_resolver` example has been changed to single quotes as well.
