### ISSUE TITLE
[Request] Linux Repo or Inbuilt Automatic Updates For Stable and Nightly

### ISSUE THREAD

**Issue by rebekah65** [DNSCrypt/dnscrypt-proxy#611]
To my knowledge, right now you have to manually update to each new version.
Instead can you implement automatic updates for both stable and nightly, either by a repo or inbuilt automatic updates.
Thanks

**Comment by jedisct1** [comment]
The resolvers lists are automatically updated.

But for the software itself: it would be impossible for a single person to maintain packages for every single linux distribution (and why only Linux?), especially since I don't use Linux.

Packages are available for most operating systems/distros already (including Windows and all BSDs), so you should probably use them. dnscrypt-proxy will be updated like everything else on your system.
