### ISSUE TITLE
Feat: Improvement when -checking -config when the system is offline.

### ISSUE THREAD

**Issue by publicarray** [DNSCrypt/dnscrypt-proxy#619]
Can we improve the experience when the system is offline and the config is checked for syntax errors?

```sh
ash-4.3# time bin/dnscrypt-proxy -config var/dnscrypt-proxy.toml -check
[2018-10-19 02:20:35] [NOTICE] Network not available yet -- waiting...
[2018-10-19 02:21:05] [ERROR] Timeout while waiting for network connectivity
[2018-10-19 02:21:05] [NOTICE] Source [public-resolvers.md] loaded
[2018-10-19 02:21:05] [NOTICE] Configuration successfully checked

real	0m30.033s
user	0m0.004s
sys	0m0.008s
```

Usecase: I run the check command every-time the user saves a file in the GUI.

**Comment by jedisct1** [comment]
Checking the configuration may require loading sources (and, eventually, other things such as remote blacklists), so we really need the network to be available in order to do so.

Should we have a `-syntaxcheck` that just checks the syntax of the main `toml` file? Or add a command-line option to override `netprobe_timeout`?

**Comment by publicarray** [comment]
Thanks for explaining. While `-syntaxcheck` would fit this use-case, I think having the ability to configure the `netprobe_timeout` could benefit more people/ use-cases and would be less confusing. we don't need to explain what the difference between `-syntaxcheck` and `-check` is. Just my 2 cents 😃

**Comment by jedisct1** [comment]
> we don't need to explain what the difference between -syntaxcheck and -check is.

That is a very solid point :)
