### ISSUE TITLE
TLS 1.3 dnscrypt and dnscrypt docker

### ISSUE THREAD

**Issue by jicfol** [DNSCrypt/dnscrypt-proxy#648]
@jedisct1 As Dnscrypt does support TLS 1.3 now https://github.com/jedisct1/dnscrypt-proxy/blob/master/README.md
And i can't reply on https://github.com/jedisct1/dnscrypt-proxy/issues/298

Is Dnscrypt capable of using TLS 1.3 as Dnscrypt docker isn't updated yet?
If so, how to force TLS 1.3 only connection between both.

**Comment by jedisct1** [comment]
Not sure what you mean by "dnscrypt docker". Do you mean the dnscrypt-wrapper server image?

If you want TLS 1.3, you need to download the binary from https://github.com/jedisct1/dnscrypt-proxy/releases

**Comment by busmor** [comment]
@jedisct1 Same question here. Thanks for your reply to @jicfol
Highly recommended.

Setting is very simple: Linux client on dnscrypt-proxy, connects via dnscrypt-server-docker server elsewhere.

Do I understand it correctly that because dnscrypt-proxy 2.0.18 supports TLS 1.3.
It could connect to any server, based on dnscrypt-wrapper server via TLS 1.3?

I thought that both client and server had to be on TLS 1.3. 
But as I understand it does not matter?

P.s. If there are specific settings needed for dnscrypt-proxy.toml to use TLS 1.3. Kindly share them.

Thanks.

**Comment by jedisct1** [comment]
The DNSCrypt protocol doesn't use TLS. It's a protocol specifically designed for DNS.

dnscrypt-proxy compiled with TLS 1.3 support only improves connections to DNS-over-HTTP (DoH) servers, that used to require [10 times more packets](https://twitter.com/PowerDNS_Bert/status/1064440918139383809) than when using DNSCrypt. With TLS 1.3, it's only 6 times.
