### ISSUE TITLE
dnscrypt-proxy adds a EDNS0 RR even if the original request does not have it

### ISSUE THREAD

**Issue by ameshkov** [DNSCrypt/dnscrypt-proxy#667]
Yesterday I've been trying to figure how to use dnscrypt-proxy as a library and not as a binary executable, failed to do it, and used some copy-paste-fu to create a new one: https://github.com/ameshkov/dnscrypt

So, while reading the original code, I stumbled upon one thing that I don't fully understand.

I am talking about this plugin:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_get_set_payload_size.go

1. First of all, is it okay that it adds a new EDNS0 RR even if the original request didn't have it?
2. Second, I don't understand what's the point of modifying the existing EDNS0 record at all. I mean the DNSCrypt protocol is orthogonal to the plain DNS, isn't it?
3. This plugin is also applied when the upstream is a DoH server.

**Comment by jedisct1** [comment]
Hi!

And good job on the standalone library, this is amazing!

Stub resolvers can add an empty OPT section even if client queries didn't include one. This is what the Linux standard library do when the `edns` option is present in `/etc/resolv.conf`. Being restricted to 512 bytes UDP packets doesn't make sense any more.

This limits the number of times the client has to fallback to TCP. 

That could be done by the server-side proxy. And maybe it is implemented in dnscrypt-wrapper already. But old implementations will keep requiring the client to explicitly tell that payloads more than 512 bytes are okay in order to avoid TCP fallback.

Regarding DoH: queries sent to the DoH proxy are sent over TCP, but then, from that proxy to the actual resolver, this is almost always UDP. If the DoH proxy adds the supported EDNS payload size itself, this is fine. If the DoH proxy passes the client query unmodified, we will get more unnecessary fallbacks to TCP.

**Comment by ameshkov** [comment]
Thanks for the answers! It does make sense to add it indeed, I just think that I should make it configurable in the client library then.

Sorry for so many questions, I am just trying to understand it better.

1. The code that adjusts it uses `ResponseOverhead` value which consists of DNSCrypt-specific field lengths. Why?
2. [Here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_get_set_payload_size.go#L37) in some cases it makes the advertised payload size **less than** it was in the original `edns`. Is there a specific reason for that?

**Comment by jedisct1** [comment]
`MaxDNSUDPPacketSize` is the maximum packet size that is safe to use without fragmentation.

The resolver will send an unencrypted packet up to that size. The actual packet after encryption will have `ResponseOverhead` extra bytes, so the advertised max size as seen by the resolver should be `ResponseOverhead` less than the actual value.

Clients queries can already include EDNS0 information, but this assumes that there is no encryption. We need to adjust the size for `ResponseOverhead`.

**Comment by ameshkov** [comment]
Got it, thank you!
