### ISSUE TITLE
Support DNS-over-TLS with the Quad9 DNS Service

### ISSUE THREAD

**Issue by macmisu** [DNSCrypt/dnscrypt-proxy#68]
According to the link below, dns 9.9.9.9 also supports DNS-over-TLS (maybe HTTP/2?). Since dnscrypt-proxy already uses 9.9.9.9 as default fallback resolver, I think it makes sense to support it. Thank you.

https://medium.com/nlnetlabs/privacy-using-dns-over-tls-with-the-new-quad9-dns-service-1ff2d2b687c5

**Comment by jedisct1** [comment]
Implementing DNS-over-TLS is not planned since it provides no benefits over DNS-over-HTTP/2.

But Quad9 said they were working on implementing the DNSCrypt protocol..

**Comment by sergeevabc** [comment]
> Implementing DNS-over-TLS is not planned since it provides no benefits over DNS-over-HTTP/2
But DNS-over-TLS is a known and [widely implemented][1] technology already.

[1]: https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

**Comment by jedisct1** [comment]
Its initial proponents (because discussing this was an excuse for the handful privileged people allowed to attend IETF meetings to drink at expensive hotels in exotic locations, and eventually conclude that they wouldn't invent anything after all) are now all busy documenting and implementing DNS-over-HTTP/2 instead.

Move on. DNS-over-TLS doesn't make any sense any more (except to lucky people who got funding to work on it). DNS-over-HTTP/2 is what people use already, if only because of Firefox and Cloudflare.

Now, since you apparently have a lot of spare time, it would be great to write/improve the documentation instead of commenting old, closed tickets. Thanks!
