### ISSUE TITLE
sfw.scaleway-fr blocking facebook domains?

### ISSUE THREAD

**Issue by ajp2k13** [DNSCrypt/dnscrypt-proxy#713]
@jedisct1 I noticed sfw.scalewat-fr is blocking facebook.com and other facebook domains? Just curious if it's by design or a false positive/mistake?

Thanks!

**Comment by jedisct1** [comment]
Hi,

and thanks for reporting this.

This is probably due to the vast amount of pornographic websites having names resembling Facebook (fuckbook, etc), or the name facebook itself (see below for a snippet)

![screen shot 2019-02-01 at 14 27 22](https://user-images.githubusercontent.com/124872/52125715-a54a3b00-262d-11e9-83cd-e7ff325ac2b7.png)

I manually removed the legitimate Facebook domains. Thanks!

**Comment by ajp2k13** [comment]
Thanks for the quick fix! :)
