### ISSUE TITLE
[Info] eDNS (dnsflagday)

### ISSUE THREAD

**Issue by Ainatar** [DNSCrypt/dnscrypt-proxy#715]
Hi, I leave a link for those who want to catch up on dns news.

https://dnsflagday.net/

**Comment by Mikaela** [comment]
I am curious on does it affect dnscrypt-proxy users or people running the resolvers, but have been afraid to ask.

I have imagined that they are using so new versions that they are automatically part of dnsflagday, but I haven't thought about firewalls until typing this now.

The tester there warned on two domains I tested, but both seemed to be working in the morning and now it's already 00:08 here, so day after DNS flag day.

**Comment by jedisct1** [comment]
dnscrypt-proxy itself has support for edns since day one.

This flag day is about authoritative servers not supporting EDNS, not recursive ones.

And I don't expect much to happen on this day, if anything at all.

If a popular domain cannot be resolved, people will add workarounds so that it works, even if it's technically broken.

It's the way DNS operation has always worked, and it's not going to change.

Adding workaround for broken servers, because users/customers not complaining is more important than being pedant about how specifications are implemented.

Some "supporters" on the DNS flag day page [don't even support EDNS themselves](https://ednscomp.isc.org/ednscomp/94aa341fd6), so this flag day is more like "let's our company find an opportunity to get some press" than a real issue being addressed.

So, don't panic. Nothing's going to happen on that day.
