### ISSUE TITLE
daemon.warn dnsmasq[5877]: Maximum number of concurrent DNS queries reached (max: 150)

### ISSUE THREAD

**Issue by vanyaindigo** [DNSCrypt/dnscrypt-proxy#769]
Something spaming with this on OpenWRT:
`daemon.warn dnsmasq[5877]: Maximum number of concurrent DNS queries reached (max: 150)`
After i go to Status-Realtime Graphs-Connections. Number of open connections grow very fast (more then thousand) and all it is DNSCrypt-Proxy sending 1 packet.

**Comment by the-w1nd** [comment]
If you followed the configuration instructions on the [wiki](https://github.com/jedisct1/dnscrypt-proxy/wiki/Installation-on-OpenWRT), then you've introduced an infinite loop in your configuration, since `forwarding-rules.txt` will forward internal PTR requests (reverse dns lookups) to `dnsmasq`, which in turn will send it back to DNSCrypt.  There is however a chance that the infinite loop will be broken by `dnsmasq` sending the request to the ISP, since the `resolv.conf` file is still getting used.

I've changed my configuration to prohibit local requests from reaching DNSCrypt, while having DNSCrypt the only authority for external requests.  I'm proposing the same wiki changes here, but meanwhile, you can look at what I've done in [OpenWRT forum](https://forum.openwrt.org/t/how-to-properly-configure-dnsmasq-for-dnscrypt-v2-to-prevent-leaks-to-isp/33907).

Hope this helps.
