### ISSUE TITLE
base64 urlsafe_b64encode padding

### ISSUE THREAD

**Issue by dl9sau** [DNSCrypt/dnscrypt-proxy#775]
Since https://dnscrypt.info/stamps Online DNS Stamp calculator does not work on any browser and because I did not found any useful commandline tool, I wrote a small program in python for generating DNScrypt sdns URLs.

While testing, dnscrypt-proxy often complained
  [FATAL] illegal base64 data at input byte 159

Reason: python base64 urlsafe_b64encode returns the base64 urlsafe encoded string with padding:
  print "sdns://%s" % base64.urlsafe_b64encode(stamp)
I.e. ending with "...QuaXQ=". n * '=' is the padding character for base64.

I assume that the go implementation of
  base64.RawURLEncoding.DecodeString()
in dnscrypt-proxy is not safe for the padding char '='.

Solution: delete the padding chars in the sdns-URL.

Possible fix: I'd recommend dnscrypt-proxy to remove the padding char's in the sdns-URLs specified in the config file before passing them to base64.RawURLEncoding.DecodeString().

**Comment by jedisct1** [comment]
The online stamp calculator should work with any browser. I just accessed it and it seems to work fine. What issues are you having? Any message on the console?

its source code is here: https://github.com/jedisct1/vue-dnsstamp

There are different base64 variants, and the one used here is indeed the url-safe variant, without padding.

If Python always adds padding, you can simply remove the `=` characters.

Padding is a historic artifact, and is not useful. It just makes the output bigger.

Since these stamps are machine generated, I'd rather keep dnscrypt-proxy expect them to be in a single standard form, especially as it is more efficient.

**Comment by dl9sau** [comment]
Hello,

> Am 02.04.2019 um 15:47 schrieb Frank Denis <notifications@github.com>:
> 
> The online stamp calculator should work with any browser. I just accessed it and it seems to work fine. What issues are you having? Any message on the console?

Tried it with macos safari, firefox (by disabling javascript blocker) and iridium browser. Presented did not change afte rinput.

> 
> its source code is here: https://github.com/jedisct1/vue-dnsstamp
> 
> There are different base64 variants, and the one used here is indeed the url-safe variant, without padding.
> 
> If Python always adds padding, you can simply remove the = characters.

Jope, that's what I did and used the chance to document that. But it would have benn nice if dnscrypt-proxy striped them on it's own during parsing the config file.

Off-topic: I've another small question. By direct mail or via github?
