### ISSUE TITLE
Feature Request: Dealing with Web Portals

### ISSUE THREAD

**Issue by oniGino** [DNSCrypt/dnscrypt-proxy#796]
Avid user of this product for some years on all my devices

I usually only need to disable dnscrypt-proxy when dealing with Web Portals (Airport WiFi etc)
I wonder if its beyond scope or not to have dnscrypt proxy daemon intelligently deal with these scenarios, Something similar to how chromium deals with them
https://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection
And offer some notification log event, when a portal is detected, or temporarily fall back to dhcp offered DNS (some security issues there)

any thoughts on this? Anyone else with this issue?

**Comment by jedisct1** [comment]
Captive portals are always an issue :(

But dealing with them is a user interface issue. It's also very specific to individual operating systems. I think macOS/iOS/Android have dedicated APIs for this.

dnscrypt-proxy has no user interface, so this is rather something that graphical frontends such as simplednscrypt could include. If a captive portal is detected, an alert box should be displayed, so that the user can confirm that DNS settings can be temporary disabled.

Automatic fallback to DHCP would be terrible from a security perspective. A MITM attack would silently disable the proxy instead of blocking the non-legitimate traffic, completely defeating the whole purpose of having encryption. 

So, really, what we need is more and better user interfaces, or integration of that features in these or existing ones.
