### ISSUE TITLE
HTTP/2 GET, PING, and long lived connections

### ISSUE THREAD

**Issue by sebdeckers** [DNSCrypt/dnscrypt-proxy#799]
Hello -- Noticed increasing traffic from `user-agent: dnscrypt-proxy` on my public DoH service. I don't record logs so details are scarce. I did notice a few things by debugging the server.

## PING
Does dnscrypt-proxy send any HTTP/2 PING frames? Seeing many of these. Could be other clients since each PING seems to be on its own HTTP/2 session, no other streams and no header/data frames are transferred.

## GET
Does dnscrypt-proxy send GET requests for the root NS? Strangely I see the following request repeated over and over. Always the exact same query string and identical sequence of `X`s in the `random_padding`.

      HTTP/2.0 GET https://commons.host/dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

The query decodes to:

```js
{ id: 51966,
  type: 'query',
  flags: 256,
  flag_qr: false,
  opcode: 'QUERY',
  flag_aa: false,
  flag_tc: false,
  flag_rd: true,
  flag_ra: false,
  flag_z: false,
  flag_ad: false,
  flag_cd: false,
  rcode: 'NOERROR',
  questions: [ { name: '.', type: 'NS', class: 'IN' } ],
  answers: [],
  authorities: [],
  additionals:
   [ { name: '.',
       type: 'OPT',
       udpPayloadSize: 4096,
       extendedRcode: 0,
       ednsVersion: 0,
       flags: 32768,
       flag_do: true,
       options: [] } ] }
```

## Long Lived Connection

What is the policy for sustaining or closing an HTTP/2 connection? Many/most connections are only a few streams (req/res) in duration. It could be more efficient to keep connections open instead of repeating the expensive TCP/TLS handshake.

Perhaps related, some client IPs have *hundreds* of 443/TCP connections at once to the same DoH server; each socket is very short lived (max a few seconds).

**Comment by jedisct1** [comment]
The proxy only establishes normal connections using the basic Go HTTP API. It never explicitly sends PING frames, I'm not even sure that the API allows it. Maybe Go silently does it under the hood but I doubt it and don't see why it would.

`POST` requests are always preferred. The proxy falls back to `GET` only if the server doesn't properly support `POST`.

The query for the root zone name servers (whose response is virtually always cached, or even hard-coded) is sent when the server starts or ever 4 hours to check that the server is alive and is actually a DoH server and not just a HTTP server.

The keepalive can be configured. By default, it is set to 30 seconds. Longer timeouts have two major downsides:
- Recovering on intermittent connections and after a client IP change would be way too long. 30 seconds is already high for roaming devices.
- Longer timeouts force servers to keep way more connections, even if most of these are useless. Initial versions of the proxy had a longer timeout, and servers ran out of file descriptors, causing cascading failures.

Some people may choose a longer timeout, or a shorter one, according to their network.

TLS session tickets are enabled by default in order to save a round-trip on reconnection. However, this causes privacy issues (IPs addresses can be linked to individual clients), so this can be disabled.

Maybe you should consider adding support for the DNSCrypt protocol in addition to DoH? It is way less CPU intensive, is stateless, and requires 5x to 10x less traffic than DoH (same as regular DNS).

**Comment by sebdeckers** [comment]
> The proxy only establishes normal connections using the basic Go HTTP API. It never explicitly sends PING frames, I'm not even sure that the API allows it. Maybe Go silently does it under the hood but I doubt it and don't see why it would.

Okay, most likely other DoH clients then.

> `POST` requests are always preferred. The proxy falls back to `GET` only if the server doesn't properly support `POST`.
>
> The query for the root zone name servers (whose response is virtually always cached, or even hard-coded) is sent when the server starts or ever 4 hours to check that the server is alive and is actually a DoH server and not just a HTTP server.

Only the root zone query is GET. All others are POST. I hope that's expected. What's considered not properly supporting POST? (My server should support both GET and POST methods, though I also prefer POST as a DoH client author and user.)

> The keepalive can be configured. By default, it is set to 30 seconds. Longer timeouts have two major downsides:
> 
> * Recovering on intermittent connections and after a client IP change would be way too long. 30 seconds is already high for roaming devices.
> * Longer timeouts force servers to keep way more connections, even if most of these are useless. Initial versions of the proxy had a longer timeout, and servers ran out of file descriptors, causing cascading failures.
> 
> Some people may choose a longer timeout, or a shorter one, according to their network.
> 
> TLS session tickets are enabled by default in order to save a round-trip on reconnection. However, this causes privacy issues (IPs addresses can be linked to individual clients), so this can be disabled.

Ah, great idea. I will check that session resumption is working properly [on my server](https://nodejs.org/api/tls.html#tls_session_resumption).

> Maybe you should consider adding support for the DNSCrypt protocol in addition to DoH? It is way less CPU intensive, is stateless, and requires 5x to 10x less traffic than DoH (same as regular DNS).

Interesting, will explore this further. I've seen the name but this is the first time reading the spec. Q: why use port 443 if it's not HTTPS?

**Comment by jedisct1** [comment]
Port 443 is less likely to be firewalled than other ports. But the protocol can use any ports, and even share port 53 with unencrypted DNS traffic.

**Comment by jedisct1** [comment]
Your server seems to support `POST` just fine :)

But a timeout or an antivirus can cause the query to fail, and be retried over `GET`. Since your server supports `POST`, the query over `GET` is likely to fail for the same reason.

The proxy will then give up (or rather, mark that server as not usable/too slow and use other servers).

Which is why you see `GET` queries for the initial probe only.

**Comment by sebdeckers** [comment]
@jedisct1 Thank you for all the clarification and explanation. Very helpful!

The H2 PING frames are probably from my own client, [Dohnut](https://github.com/commonshost/dohnut). But there is no identifying information so I can't be 100% certain. I reduced their frequency in a new release.

Also implemented the TLS session resumption in my client. Will work on a ticket keys sharing mechanism to enable TLS session resumption across all my DoH edge servers (and lower their CPU load).

Closing this since my original questions are answered. Thanks again!
