### ISSUE TITLE
[Question] Which is DNSSEC validation package you recommend to run with dnscrypt-proxy ?

### ISSUE THREAD

**Issue by Nokia808** [DNSCrypt/dnscrypt-proxy#863]
Hi. 
I searched for DNSSEC validation package & found on Fedora some packages deal with DNSSEC but I'm not sure which one is correct.

I need a GUI also, for that.

I found the following link on Internet:
https://feeding.cloud.geek.nz/posts/using-dnssec-and-dnscrypt-in-debian/

What is your recommendation, please ?
 
Please notice that I'm beginner in this field & I know about DNSSEC 1st from Firefox add-on:
https://addons.mozilla.org/en-US/firefox/addon/dnssec/
but this add-on has no code available on-line (closed source?) & has bad rating & seem to be not further maintained & I'm afraid that it can interfere with dnscrypt-proxy job ...... For that I searched Fedora packages .....

**Comment by Mikaela** [comment]
Would it be possible for dnscrypt-proxy to confirm the resolver isn't lying about DNSSEC?

On the original question, systemd-resolved can confirm DNSSEC and I think dnssec-trigger is a popular solution, but it includes whole Unbound which some features dnscrypt-proxy can already do.

**Comment by jedisct1** [comment]
Looks like most people use dnsmasq for this, even though you need to make sure that you are using a recent version since old versions had some issues with DNSSEC.

Client-side DNSSEC validation increases traffic, memory usage and latency, as it requires having many more records than the one from the original question in order to validate the whole chain.

If a client-side validation is needed, installing something like dnsmasq still seems like the cleanest thing to do instead of reimplementing this in dnscrypt-proxy.

Now, @Nokia808 was looking for a GUI. So, presumably some browser extension indicating whether the current domain is signed or not. Unfortunately, all the extensions I'm aware of have been abandoned and browsers have abandoned the idea of supporting DNSSEC as well.
