### ISSUE TITLE
Blacklist error

### ISSUE THREAD

**Issue by misaka00251** [DNSCrypt/dnscrypt-proxy#890]
I'm not sure this place is suitable for reporting this...

I'm using [your](https://download.dnscrypt.info/blacklists/domains/) blacklist, and it seems this will break some non-spam sites:

```
########## Blacklist from file:domains-blacklist-local-additions.txt ##########

# Ignored entries due to the whitelist: 2

// ...
tracker.*
```

Some sites use this subdomain to track their works, like debian's `tracker.debian.org`.

Maybe add for a warning on the wiki? The solution now is to manually add that to the whitelist.

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this!

`tracker` is indeed a keyword that can lead to quite a few false positives.
These can be added to the `domains-whitelist.txt` file so that they don't get filtered.

I'm going to add that one to the default `domains-whitelist.txt` file.

Thanks again for reporting this!

**Comment by jedisct1** [comment]
Actually... `tracker.debian.org` is already in the whitelist, but it's not really useful against the `tracker.*` rule. It should be added to `whitelist.txt` instead.
It has been added to the example whitelist.
