### ISSUE TITLE
Reimplemented generate-domains-blacklists in golang

### ISSUE THREAD

**Issue by gam-phon** [DNSCrypt/dnscrypt-proxy#894]
I have reimplemented **generate-domains-blacklists** in golang https://github.com/gam-phon/generate-domains-blacklist if you would like I can do a pull request and replace the python implementation. if there are some comments on the implementation I can do them as well.

Also if you would like I can make it within the same process as dnscrypt-proxy in different goroutine and update the list automatic if it is enabled in configuration. what do you think? I can make a pull request for this as well if you want

**Comment by gam-phon** [comment]
@jedisct1 What do you think? Should I do a pull request to replace python implementation or make it in same proccess as dnscrypto in different goroutine with automatic update? Or should we keep things as they are now?

**Comment by jedisct1** [comment]
Hi!

This is great, but Python (or any other scripting language) seems to be a good fit for that task. That's typically what scripting languages are designed for.

It also has the advantage of being simple to modify; more people are likely to be familiar with Python than Go.

So... A rewrite in a different language seems like a solution in search of a problem :)

As to merging this in the proxy itself, this makes it even more difficult to modify, but also to compose. I currently don't use the output of that script directly, but use it in another script that adds and removes a couple entries from its output. I also use that output for rspam (a spam filter) to score mail senders domains.
Having this script as a standalone tool rather than as something included in a big monolith seems more convenient.
