### ISSUE TITLE
Order of log lines during startup

### ISSUE THREAD

**Issue by Vort** [DNSCrypt/dnscrypt-proxy#901]
I was using v2.0.19 and first line after starting was.
```
[2019-07-31 13:13:16] [NOTICE] dnscrypt-proxy 2.0.19
```
Now, after upgrade to v2.0.25, first lines are:
```
[2019-07-31 14:09:44] [NOTICE] Network connectivity detected
[2019-07-31 14:09:44] [NOTICE] dnscrypt-proxy 2.0.25
```
Maybe it will be better to always show version number first?

**Comment by iWARR** [comment]
@ **jedisct1**

My close attention was always on "query.log" data order inconsistence.
This is annoing thing for me since 1.x versions until today...

Look at the example of the present log:

![now](https://user-images.githubusercontent.com/33152262/62418782-8458b600-b661-11e9-89ff-3773c4b5e0a2.png)

What I'm dreaming about (ages ago)

![todo](https://user-images.githubusercontent.com/33152262/62418788-a4887500-b661-11e9-8e3f-47cc3c3dc9d4.png)

-------------------------------

**The main idea (by defaults):**
- long and different WEB LINKS ON THE RIGHT
- (basicly) short and same names on the left

The most important things are: PASS / REJECT and LINK.
Other inputs are additional and secondary (but of course useful) things.
That's it.

--------------
I'm on Windows. Text editors - AkelPad or Notepad++
Font: Consolas, 11 (it doesn't matter, because present log formatting on Windows is ugly)

On Android I prefer even less number of  columns...

Hope, this example was useful... Good luck.

**Comment by iWARR** [comment]
Sorry for the "pictures" (I know you prefer text), but this time this is nesessary to understand how it looks in real OS (not GitHub formatting).

**Comment by iWARR** [comment]
A few words about Android version log. My propose is the next:

**If "lb_estimator" disabled in toml, then columns of ping, (ms) and server (name) would not shown.**
(look at my example on the second screenshot). 

Date | Time | PASS / REJECT | domain.example.com

would be enough (IMO) by defaults.

For example, I'm already know my best servers I use, and I prefer to have more short and accurate appearance of the `query.log`. This is important for fast usability on mobile devices, where we are limited by frames of the screen and by fuctionality/formatting of the sertain text reader on Android. Of course, we can rotate the device, but this is not always convenient way.

All this propositions are about the fast and punctual log analyse.
Accurate columns save a lot of time. And my eyes also.

-----------------
P.S. Forgot to say that I replaced `[YYYY-MM-DD HH:MM:SS]` and `some-dnscrypt-server` by myself in this screens (the real log shows this inputs correctly as usual, don't worry about this replacement, these ones are just examples).
