### ISSUE TITLE
Basic DNS response logging

### ISSUE THREAD

**Issue by WinkelCode** [DNSCrypt/dnscrypt-proxy#910]
This is something I've been missing since I started using DNSCrypt, it would be very useful if there was an option for the log to include the response from the server for forensics/troubleshooting purposes. I occasionally find myself having to match the time on network logs to find what the associated host for an IP is, this is especially an issue with CDNs.

I did some browsing through the wiki and issues but was unable to find anything about this?

Edit: Changed title to clarify what I meant.

**Comment by jedisct1** [comment]
DNS responses are not just IP addresses. They can be very large, and cannot be represented in an unstructured logging format.

Maybe [dnscap](https://github.com/DNS-OARC/dnscap) can do what you want?

**Comment by ghost** [comment]
That can be done easily if you cache in a different DNS resolver. If you don't mind the overhead you can use either BIND or unbound.
```WAN <-> dnscrypt-proxy <-> BIND```
Having worked with all three, I can say BIND has the nicest logs. Right now I only cache in dnscrypt proxy because I didn't need the overhead or those logs much.
Well, technically those are not logs but the raw cache itself, but you asked for "include the response from the server", that's exactly what you will find in the cache of either of those tools.

**Comment by WinkelCode** [comment]
I should've been clearer with what I am looking for: These are great options for a proper analysis environment but what I am talking about something that can be reasonable quickly configured on the device itself. For example, Cloudflare's "1.1.1.1" app displays the resolved IP addresses right in its troubleshooting menu so I am thinking this should be possible to implement as a logging option here?

Sometimes I just want to quickly take a look at what hosts are being contacted by an application on my machine and link them to network traffic, capturing the raw response certainly has its uses for more in depth analysis but for my intended purpose just the IPs should generally suffice.

**Comment by ghost** [comment]
You say cloudflare app as in a desktop program or phone app?
Sysmon v10 offers DNS query logging for Windows users since 2 months, check the image:
https://twitter.com/markrussinovich/status/1137466538322042880
It will report
1) program making request
2) reply of DNS server
3) time / etc


If I have missed your operating system/hardware and this is useless to you, please ignore.

**Comment by WinkelCode** [comment]
> You say cloudflare app as in a desktop program or phone app?

I mean the iOS (Android possibly does it as well) app.

> Sysmon v10 offers DNS query logging for Windows users since 2 months

I actually didn't know that Sysmon supports this now! I'm gonna look into setting it up on my Windows machine (At the moment I mostly use Windows but I often switch/use other operating systems).

Regardless, I think it would be very useful to have this built into dnscrypt-proxy as it works with pretty much on all common OS (not just Windows or just UNIX) and would offer convenient way of potentially doing further analysis using a "common" log format.

**Comment by jedisct1** [comment]
Probably not, sorry.
