### ISSUE TITLE
generate-domains-blacklists makes an empty dnscrypt-blacklist-domains.txt

### ISSUE THREAD

**Issue by Decopi** [DNSCrypt/dnscrypt-proxy#917]
I have Windows 10 and Python installed.
I am trying to build my own customized blacklist-domains file by using generate-domains-blacklists.

But when I run CMD with the execution command, an empty dnscrypt-blacklist-domains.txt is generated.
Here is the screen text with the CMD' steps and messages: https://pastebin.com/tE7DMYG8

It is my first time using Python. Am I doing something wrong?

Thks

**Comment by r4sas** [comment]
Python version?
I think here problem because script can't access to list on https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
Try open it in browser.

Otherwise you can add `-i` or `--ignore-retrieval-failure` argument to bypass that error.

`py generate-domains-blacklist.py -i > dnscrypt-blacklist-domains.txt`

**Comment by jedisct1** [comment]
maybe you are blocking domain names with “ad” in their name?

**Comment by Decopi** [comment]
@r4sas and @jedisct1 thks, It worked.
My computer is clean, latest Python, no blockers, easylist' webpage was OK on browsers, but for some unknown reason wasn't working using generate-domains-blacklists. So changed computer, and worked perfectly (including easylist).

Now I need a cron. But I'm on Windows 10.
What is better, batch or task scheduler? Pls, can you help me with the batch script or task scheduler line command?

**Comment by r4sas** [comment]
Use system Task Scheduler. All info you can find in internet.
