### ISSUE TITLE
How to debug SERVER_ERROR?

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-proxy#924]
Sometimes there are many `SERVER_ERROR` in the query log, but I can't see any related issues, I see no options in the config and parameters to help debug, even `log_level` is set to `0` already, I know reading the source code might be one method but it'll be great if there can be some more friendly ways to do it. Many thanks.

**Comment by jedisct1** [comment]
`SERVER_ERROR` is usually a timeout. A query was sent to the server, but no reply was received.

**Comment by AnyWAT** [comment]
[2019-09-08 06:28:51] [WARNING] [2.dnscrypt-cert.resolver1.dnscrypt.eu.] certificate is about to expire -- if you don't manage this server, tell the server operator about it
[2019-09-08 06:29:00] [CRITICAL] [2.dnscrypt-cert.ipredator.se.] certificate will expire today -- Switch to a different resolver as soon as possible

**Comment by PeterDaveHello** [comment]
> `SERVER_ERROR` is usually a timeout. A query was sent to the server, but no reply was received.

Interesting, I have different dnscrypt-proxy instances in the same LAN network, the one on Raspberry Pi frequently got `SERVER_ERROR`, the one on my laptop works better than that.

Have checked both has enough resource, the latest versions(the recent 3 releases), so I don't know what's going on, doesn't seem to be network connectivity issue, sometimes it even got all `SERVER_ERROR`.

I wonder before I erase the whole system, is there something else I can do, as cloudflared and Pi-hole works very well on it, doesn't seem to be an environment issue either.

**Comment by WusWus** [comment]
Hello, 

since today I have the problem that I can reach with DNScrypt-proxy websites only very difficult. 

I'm using 'Simple DNSCrypt' (v0.6.6) as GUI for dnscrypt under Windows 7 64bit. 
After having problems with version 2.0.25 today, I replaced it with the new version 2.0.26. 
Without DNSCrypt all websites are easily accessible. 

In the 'query. log' I always find 'SERVER_ERROR'. Duration to high? 
I only use selected servers (for example: 'geekdns-hk', 'jp.tiar.app', 'dnscrypt-04.adsnomore.io', 'arvind-io', 'dnscrypt-07.adsnomore.io', 'ibksturm', 'd0wn-tz-ns1', 'dnscrypt-03.adsnomore.io', 'soltysiak'), but only 'geekdns-hk' and 'opennic-ethservices' are available. 
All other servers are not reached/found. 

When 'Force TCP' is enabled, version 2.0.26/2.0.25 it's not possible to resolve websites. I only can reach my router. 

Duration of server: 
geekdns-hk'; = 250-2720 (temporarily no connection possible) 
opennic-ethservices = 180-430 (when automatic server search is enabled)

further settings in dnscrypt: 
- force_tcp = false (temporary, otherwise 'true')
- block_ipv6 = true 
- dnscrypt_servers = true
- doh_servers = false
- require_dnssec = true
- require_nolog = true
- require_nofilter = true

An upload of files is not possible at the moment because of the problems.

best regards
WusWus

**Comment by PeterDaveHello** [comment]
Just a suggestion, maybe can split SERVER_TIMEOUT error from SERVER_ERROR so it'll be more clear that some or most of them are caused by timeout but the others aren't?

**Comment by jedisct1** [comment]
That's a good idea!

**Comment by PeterDaveHello** [comment]
BTW, I'm sure there is a non-timed-out SERVER_ERROR but don't have enough info to debug it, the response is very fast, may caused by configuration issue.
