### ISSUE TITLE
[HELP] Please, youtube to invidious?

### ISSUE THREAD

**Issue by EstherMoellman** [DNSCrypt/dnscrypt-proxy#931]
Hi!

Please, is it possible to redirect any youtube' video to invidious (https://github.com/omarroth/invidious/) by using DNSCrypt?

I tried by CLOAKING and FORWARDING, but I failed.
I also tested many "*" combinations.

Days ago I posted a question at GitHub Invidious (https://github.com/omarroth/invidious/issues/739), the Dev suggested me to use `*.youtube.com invidio.us`, I tested it, but sadly it didn't work.

Thank in advance!

**Comment by jedisct1** [comment]
The Invidious web server needs to be configured to be able to respond to `youtube.com`, not just `invidio.us`. But that won't work for HTTPS (to do so, you need to add certificates to your browser, it's complicated).

**Comment by EstherMoellman** [comment]
What a pity! But thank you for the answer.

**Comment by dnscrypt-ca** [comment]
If you use Firefox you could use the [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) extension to do this.  I should note that:

1. This works on the URL bar and does not seem to affect embedded video.
2. This is a redirect rather than masking the youtube (or whatever) site with another, so the URL will change and you will be "at" the new site. 

A bit of a hack, but possibly useful.

I realize this really has nothing to do with dnscrypt-proxy but I thought it might be nice to provide a [possible] solution in case other people came looking for the same thing.  Apologies if this is unwelcome.

**Comment by EstherMoellman** [comment]
@dnscrypt-ca thank you for your (very welcome) comment.

I've been using DNScrypt for the past two years. This has been a beautiful learning path. And today, DNSCrypt for me is a kind of Swiss-knife, doing much more than just encrypting DNS.

These Swiss-knife DNSCrypt' multi-functions allowed me, for example, to replace lot of add-ons/extensions I had (mainly ad-blockers, tracker-blockers, redirectors etc). My browser performance gain was huge! So since DNSCrypt, if I can, I really try to avoid any kind of add-on/extension. Thanks to DNSCrypt, today I have a fraction of the add-ons/extensions I had 2 years ago.

So, I was aware about add-ons/extensions capable to redirect youtube to invidious. But I really hoped that my DNSCyrpt Swiss-kinfe was able to do that.
But again, thank you for your help!

For those DNSCrypt' users in my same situation, wanting to redirect youtube to invidious, I leave below a tiny JS' code able to do that, much more lightweight than any add-on/extension:

`var a = 0;`
`setInterval(function () {`
`	if (a === 0 && window.location.href.indexOf('watch?') > -1 && window.location.href.indexOf('list=WL') < 0) {`
`		a = '//invidio.us/watch?' + window.parent.location.href.split('?')[1];`
`		window.location.replace(a);`
`	}`
`}, 10);`
