### ISSUE TITLE
Cloaking rules format is the opposite of all hosts lists

### ISSUE THREAD

**Issue by 35609902357** [DNSCrypt/dnscrypt-proxy#946]
Every hosts list have the IP to redirect the request to before the domain to redirect ([example](https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts)).
So all the lists are
`127.0.0.1    example.com`
`127.0.0.1    8.8.8.8`
but cloaking rules requires
`example.com    127.0.0.1`
The documentation doesn't specify if IP addresses can be redirected, such as
`8.8.8.8    127.0.0.1`
This means that easily importing the lists is impossible and it's apparently not possible to block IP addresses.
It would be nice to have an option to be able to switch the domain and the IP to redirect to to make cloaking rules hosts list friendly. This could be accomplished by a different text file, like lists.txt

**Comment by jedisct1** [comment]
If an IP address is already known, DNS is not used. So, DNS cloaking cannot redirect IP addresses.

Cloaking is not designed for blocking. For blocking, blacklists are a better fit. Redirecting to `127.0.0.1` doesn't block, and can open security issues.

The `generate-domains-blacklist.py` script can read traditional `hosts` files, and generate smaller, simplified blacklists for `dnscrypt-proxy`. The proxy offers more flexibility than a `host` file, because it supports wildcards.

**Comment by 35609902357** [comment]
Can the `ip-blacklist.txt` and the `blacklist.txt` files be  unified in one file? Like this it would only take one single blacklist file containing both domain names and IP addresses, as they are the most common format that can be found, and in the `dnscrypt-proxy.toml` file both `blacklist_file` options could be set to point to the same blacklist file. Is it possible to do that?
