### ISSUE TITLE
Is there some libary for debug and study the dnscrypt's communication process?

### ISSUE THREAD

**Issue by hongyi-zhao** [DNSCrypt/dnscrypt-proxy#954]

**Comment by jedisct1** [comment]
A good starting point is obviously the [protocol specification](https://github.com/DNSCrypt/dnscrypt-protocol).

The first thing a DNSCrypt client does is retrieve the current certificates.

For example the stamp `sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc` contains the following information:

```text
IP address: 212.47.228.136 (default port is 443)
Provider name: 2.dnscrypt-cert.fr.dnscrypt.org
```

If we send a normal TXT DNS query to this server, on port 443, we get the certificates:

```sh
drill -p 443 TXT 2.dnscrypt-cert.fr.dnscrypt.org @212.47.228.136
...
;; ANSWER SECTION:
2.dnscrypt-cert.fr.dnscrypt.org.	28800	IN	TXT	"DNSC\000\002\000\000T	;\024\165Kb\023\028s\179w*\200\001\183\255\013\221s\219\212\219\166_\221\188\207\031]\182\210\167\159\136\186\180\167e\025\189|\172]\2090\146\221\0178DV\189\250a\031Oe\215;\243\150\177\001\029\019\214\242\239\002\189\025\199dN;y\150\239\251\152+\172S\011\230\233RF\227\128\142\141\171\1732\029\019\214\242\239\002\189\025\000\000\000\001]\156\133Y]\157\214\217"
```

The format of this certificate is documented in the specification. You can also take a look at the existing implementation to see how it's decoded. But among other things, what it contains is the ephemeral public key of the server.

Additional logging can be enabled in `dnscrypt-proxy` by setting `loglevel` to `0` and adding the `DEBUG` environment variable:

```sh
env DEBUG=1 ./dnscrypt-proxy -loglevel 0
```

This will display some information, especially about certificates, especially when something goes wrong.

The protocol itself is very simple. The client creates a key pair, send a query with its public key attached to it (that can change for every query) along with the unmodified DNS query encrypted with its private key and the server's public key. The server responds the same way, but without attaching its public key because the client already knows it.

There is also some padding both on queries and responses, to avoid learning from packet sizes. The padding is also used to avoid amplification attacks: a response cannot be larger than the question, or else TCP will be used instead of UDP.
