### ISSUE TITLE
Can logs be outputted to docker output window?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [DNSCrypt/dnscrypt-proxy#982]
Hi all,

I'm not real familiar with all of this stuff, but I use this container for my dnscrypt proxy: 

https://hub.docker.com/r/faicker/dnscrypt-proxy-2

And I have it working great (as far as I can tell; there seems to be no simple way to view whether my dns requests are encrypted or not), and now I want to be able to peruse any logs it creates via the log/commands windows in things like Portainer, Kitematic, Dockstation, etc.

I do realize that I can use tail to watch logs, but I don't really want to keep a tail window open all the time. I'd like to just be able to switch to that container in any of the above apps to view them on a whim. Is this possible?

I have edited the config file a bit, but don't really know what I'm doing, and it doesn't work. Here's what I did:

```
###############################
#        Query logging        #
###############################

##Log client queries to a file

[query_log]

  ## Path to the query log file (absolute, or relative to the same directory as the executable file)
  # file = 'query.log'
  file = 'stdout'

  ## Query log format (currently supported: tsv and ltsv)
  #format = 'tsv'
  format = 'ltsv'

  ## Do not log these query types, to reduce verbosity. Keep empty to log everything.
  # ignored_qtypes = ['DNSKEY', 'NS']

############################################
#        Suspicious queries logging        #
############################################

## Log queries for nonexistent zones
## These queries can reveal the presence of malware, broken/obsolete applications,
## and devices signaling their presence to 3rd parties.

[nx_log]

  ## Path to the query log file (absolute, or relative to the same directory as the executable file)
  # file = 'nx.log'
  file = 'stdout'

  ## Query log format (currently supported: tsv and ltsv)
  #format = 'tsv'
  format = 'ltsv'
```

Obviously those are wrong, is there another way? (without actually being in control of the container source itself)

Thanks!

**Comment by jedisct1** [comment]
```toml
[nx_log]
file = '/dev/stdout'
```

You may also need to set `log_files_max_size = 0`.

**Comment by YouveGotMeowxy** [comment]
Perfect! thank you! At least I was close! lol

Quick newbie question if you don't mind: I'm not sure what is meant by "stamps". For instance ins another thread I saw this: sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM.

What can I do with that? Is there some way to add that right to my config or something?

**Comment by jedisct1** [comment]
In order to connect to a secure DNS resolver, a lot of information is required.

The protocol, the IP address and/or hostname, the port number, the public key or other ways to verify the certificates, the server name...

DNS Stamps encode all the information required to connect as a short string. So, instead of filling in many parameters, you just have to copy and paste a string. It works for all current protocols and can be extended to other protocols as needed.

In addition to the connection parameters, DNS Stamps store some information about whether the server supports DNSSEC, doesn't log and doesn't filter. And new flags can also be added if needed.

You can take a look at the lists that `dnscrypt-proxy` loads by default (the `.md` files): https://github.com/DNSCrypt/dnscrypt-resolvers/tree/master/v2

These are simple text files, with stamps for each server. 

If you run your own server, the software will tell you what its stamp is, or you can use the online calculator here to compute it: https://dnscrypt.info/stamps/

If you are using a public list of servers, you don't really have to care about this, as you can simply use a server name to refer to it.

But if you run your own private server, or want to connect to a server that's not in the lists, stamps can be added to the `[static]` section of the configuration file.

Relays are not DNS servers, but the information to connect to them (which is actually only the type of protocol it supports, the IP and the port) is also encoded using the same format.

**Comment by YouveGotMeowxy** [comment]
Last question, I promise. :p

Can I do both, log to stdout AND to a file? Something like :

```
[nx_log]
file = '/dev/stdout, my_logfilename'
```

So I can see the recent stuff in stdout, but longer logs are stored to the file?

thanks for all the help, I really appreciate it!

**Comment by jedisct1** [comment]
Ah no, this isn't going to work.
